### ISSUE TITLE
"archinstall.lib.exceptions.HardwareIncompatibilityError" error

### ISSUE THREAD

**Issue by jdenoy** [archlinux/archinstall#651] opened 2021-10-04 14:25 UTC
Hello,

I'm facing an error installing using json config file. (Tested multiple-times)

**Error message** : archinstall.lib.exceptions.HardwareIncompatibilityError
**Version of archinstall** : direct from arch repo **archinstall-2.2.0-1**
**Hardware** : virtualbox 6.1 with with following parameters : 
![Screenshot_2021-10-04_16-21-25](https://user-images.githubusercontent.com/246715/135868687-dd9a1214-02c9-4552-86a7-1b5d180aed6a.png)

**Shell output** : [shell_output.log](https://github.com/archlinux/archinstall/files/7278718/shell_output.log)
**log file** : [install.log](https://github.com/archlinux/archinstall/files/7278668/install.log)

Thxs,

**Comment by jdenoy** [comment] 2021-11-10 11:16
Configuration was newly generated, and EFI boot is indeed not checked by default.
I just started a new install from clean vm profile on vbox and EFI unchecked (as for each tests done before)
Today I have no more problems on the install with EFI unchecked or checked, i**t'll boot if not using disk encryption**, but if I am using disk encryption then it does not boot.

![image](https://user-images.githubusercontent.com/246715/141103522-c9f2e348-4bf6-4145-b503-a7e2edef11a8.png)

For now I'm using without disk encryption in vms...

**Comment by Torxed** [comment] 2021-11-10 11:45
Would you mind posting the `user_configuration.json` here? Would be very helpful to re-run tests and verify the issue.

**Comment by jdenoy** [comment] 2021-11-17 08:53
Hello,

sure here it is (EFI unchecked, but either doesn't work): 
[user_configuration.json.txt](https://github.com/archlinux/archinstall/files/7553100/user_configuration.json.txt)

Screenshot of boot : 

![image](https://user-images.githubusercontent.com/246715/142168382-deb377d9-248d-4b44-9a27-e9d3eaf439f5.png)

**Comment by Torxed** [comment] 2021-11-17 11:27
> Hello,
> 
> sure here it is (EFI unchecked, but either doesn't work): [user_configuration.json.txt](https://github.com/archlinux/archinstall/files/7553100/user_configuration.json.txt)
> 
> Screenshot of boot :
> 
> ![image](https://user-images.githubusercontent.com/246715/142168382-deb377d9-248d-4b44-9a27-e9d3eaf439f5.png)

Perfect, thank you! The original issue of `archinstall.lib.exceptions.HardwareIncompatibilityError` is solved both here and in `master` it looks like. Since you do pass the installation and get to what appears to be a broken boot prompt.

That specific issue with GRUB *(That's the boot loader in the picture hanging)* is tracked here: #586 and the fix for it is coming in #724. That is if I've read this issue correctly, that you cannot boot GRUB with disk encryption.

I'm assuming that `EFI` checked and `systemd-boot` works as intended.
I'll there for close this issue and point all conversations regarding GRUB and encryption to #586 so we can catch all the discussions in one place. That said, if I misunderstood the issue and closed this to quickly - please let me know and I'll re-open it and investigate further!

**Closed by Torxed** 2021-11-17 11:27 UTC
