### ISSUE TITLE
Attribute error: module 'archinstall.lib' has no attribute 'gfx_drivers'

### ISSUE THREAD

**Issue by D4v1dH03** [archlinux/archinstall#263] opened 2021-04-09 22:25 UTC
When in the step of choosing the desktop environment to install, any choice of desktop environment leads to this error in the title.

I am now using archinstall in the Arch repository.

![PXL_20210409_222437389.jpg](https://user-images.githubusercontent.com/81270448/114246532-b5fe4600-9947-11eb-807a-f61763849c8f.jpg)

**Comment by dylanmtaylor** [comment] 2021-04-09 23:10
> I am now using archinstall in the Arch repository.
> 
By this do you mean you're running off the master branch?

**Comment by D4v1dH03** [comment] 2021-04-09 23:11
I tried the master branch it didn't work either

**Comment by dylanmtaylor** [comment] 2021-04-09 23:12
Can you please post the log file?

**Comment by D4v1dH03** [comment] 2021-04-09 23:14
Oh noes. I installed in a manual and traditional way successfully now and all the logs are lost!

**Comment by dylanmtaylor** [comment] 2021-04-09 23:16
Glad you're able to get a working system, would love to try to recreate this issue and get this fixed though.

**Comment by dylanmtaylor** [comment] 2021-04-09 23:16
Can you describe your selections and more info about your system? Existing partitions before the installer started? EFI or BIOS?

**Comment by D4v1dH03** [comment] 2021-04-09 23:18
I forgot the partitions.
But it is a UEFI hardware

**Comment by dylanmtaylor** [comment] 2021-04-09 23:20
Alrighty - I'll see what I can figure out about that call, I've never seen that error before, so trying to find the cause. This installer is kind of new so I guess a few bugs here and there are expected. Sorry it dropped the ball for you on your installation.

**Comment by dylanmtaylor** [comment] 2021-04-10 01:44
hmm, this is the torxed-2.2.0 branch? I checked master and 2.1.3, and neither of them matched up for the lines of guided.py - but in the screenshot it shows line 380 of guided.py as ask_user_questions(). Notably, in both the current master at commit f1b42216a7393e58a02f2e885293efe88304cada and 2.1.3 this file has less lines than this. If you tried with 2.2.0, it's a pre-release branch (but should have work anyways). I'm really trying to figure out what happened here. Did you run `pip uninstall archinstall -y` before running `python setup.py install` to switch to the new version? In order to troubleshoot this, it's very important to know exactly what version you were running, and which options were selected (the issue seems to indicate no desktops worked). Basically, I'm trying to recreate this myself so I can troubleshoot it and try to fix this bug.

**Comment by D4v1dH03** [comment] 2021-04-10 01:46
I am really sorry that I cannot reproduce it again because now my system is properly set up 
There is no reason to reinstall it.

**Comment by dylanmtaylor** [comment] 2021-04-10 01:48
> I am really sorry that I cannot reproduce it again because now my system is properly set up
> There is no reason to reinstall it.

Very understandable, nor would I want to make you go through the trouble of doing so. Since we can't reproduce this, it's probably best to close it. Any thoughts @Torxed ? If this comes up again we can revisit it.

**Comment by Torxed** [comment] 2021-04-10 07:55
Maybe I misunderstood something and you tried scripting your own installation, since archinstall is a library. In which case awesome! But I would need to see the code used. The log would also have been very helpful in debugging the issue, so I'm going to go ahead and close the issue as it's not reproducible and the line of code that caused the crash:
```
AttributeError: module 'archinstall.lib' has no attribute 'gfx_drivers'
```
Indicates a spelling error, it's supposed to be `_gfx_drivers`.
The weird thing is that [xorg.py *(first commit)*](https://github.com/archlinux/archinstall/blob/f8963421479858ff68568f1bf492cf867e1a25aa/profiles/xorg.py#L74-L84) has never looked the way your traceback claims, which also indicates a change to the code some how. It's really really strange.

Lately that variable has changed name tho to `_gfx_driver_packages`.
But to the best of my abilities, that code has never existed in this library. Investigate where you got the package and ISO from!

Maybe a fork has these changes, but I can't locate them and I've gone through the entire history of `xorg.py`.

**Closed by Torxed** 2021-04-10 07:55 UTC
