### ISSUE TITLE
archinstall put an error in my fstab

### ISSUE THREAD

**Issue by spiralw** [archlinux/archinstall#877] opened 2022-01-18 05:23 UTC
I installed an arch system earlier and it kept kicking me into emergency mode at boot and scrolling the error too far up for me to see. for... reasons, I didn't look at why that was happening since it did boot properly afterwards, so I just left it like that

just now I went to mount a drive and it threw a bunch of fstab errors, so I looked at my fstab and it contained an `archinstall` stacktrace:

```
# Static information about the filesystems.
# See fstab(5) for details.

# <file system> <dir> <type> <options> <dump> <pass>
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 33, in <module>
    sys.exit(load_entry_point('archinstall==2.3.0', 'console_scripts', 'archinstall')())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 111, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 180, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 388, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', '/mnt'))
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 264, in perform_installation
    with archinstall.Installer(mountpoint, kernels=archinstall.arguments.get('kernels', 'linux')) as installation:
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 145, in __exit__
    self.genfstab()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 273, in genfstab
    fstab_fh.write((fstab := SysCommand(f'/usr/bin/genfstab {flags} {self.target}')).decode())
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 356, in __init__
    self.create_session()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 401, in create_session
    self.session.poll()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 279, in poll
    self.make_sure_we_are_executing()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 255, in make_sure_we_are_executing
    return self.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 323, in execute
    os.execve(self.cmd[0], self.cmd, {**os.environ, **self.environment_vars})
OSError: [Errno 5] Input/output error: '/usr/bin/genfstab'
```

unfortunately I don't have any more information other than this (that I can think of including here, at least - feel free to ask for more information and I'll try to add it), but I thought I'd report this anyway

**Comment by Torxed** [comment] 2022-01-18 08:10
Well at the very least have to check the exit code before writing to the file. The only thing I can think of is that either `base` wasn't installed properly or the mountpoint Is wrong. Do you have the `install.log` by any chance?

https://archinstall.readthedocs.io/help/issues.html#log-files

**Comment by spiralw** [comment] 2022-01-18 16:43
oh, it looks like it's on the installed machine as well:
[install.log](https://github.com/archlinux/archinstall/files/7890867/install.log)

**Comment by Torxed** [comment] 2022-01-18 20:02
> oh, it looks like it's on the installed machine as well: [install.log](https://github.com/archlinux/archinstall/files/7890867/install.log)

Ah yea :) we copy it after successful installs. I can't say I see anything standing out point to why you would get a stack trace in fstab.

I'll have to run your config at home and see if I can reproduce it. I will post here in a few days with my findings.

**Comment by dylanmtaylor** [comment] 2022-01-20 19:57
I think we should check the exit code of genfstab and if it failed, not write output to /etc/fstab

**Comment by OJFord** [comment] 2022-03-26 17:20
Duplicate of / this is almost certainly the traceback I neglected to keep to be able to provide in #673.

**Closed** 2022-03-28 12:43 UTC
Labels: bug
