### ISSUE TITLE
Wireplumber and pipewire-media-session are in conflict

### ISSUE THREAD

**Issue by mativiters** [archlinux/archinstall#1980] opened 2023-08-02 23:25 UTC
Trying to install KDE Plasma with pipewire
First jack2 has a compatibility issue as is already mentioned.
When I fixed that, this time wireplumber incompatibility.

**Comment by lxbx44** [comment] 2023-08-05 09:23
> Trying to install KDE Plasma with pipewire
> First jack2 has a compatibility issue as is already mentioned.
> When I fixed that, this time wireplumber incompatibility.
> 

It happened the same to me, when choosing the audio interface in the archinstall, instead of chosing pipewire or pulseaudio, i choose "none".
Then you will be able to finish the installation without any problems. Then you simply install pipewire manually, so you can handle all the errors (havent done that yet, so idk if that works, i will tell you if it works)

**Comment by fabianmuehlberger** [comment] 2023-08-17 07:47
Duplicate of #1973

**Closed** 2023-09-14 09:59 UTC
