### ISSUE TITLE
After finish installation, yes OR no return to original shell, without chroot into newly created installation

### ISSUE THREAD

**Issue by peracchi** [archlinux/archinstall#1393] opened 2022-07-21 20:50 UTC
Tried several times, changing some options to see if makes difference.

Frequently I do installations of Arch Linux from current ISO on Proxmox (both on local machine and on VPS).

This bug apparently appeared on `archlinux-2022.07.01-x86_64.iso`.

It's very useful to chroot at the end of the installation to adjust some things before the final reboot, I'm missing this functionality.

**Comment by vegantom** [comment] 2022-07-23 12:29
Just tried this, can confirm. Replicated in a UEFI Q35 KVM.
Selected Yes(default):
Had to manually mount /dev/vda2 (root partition) and then arch-crhoot into that mount point.

**Comment by wllacer** [comment] 2022-07-27 16:53
I can confirm it on the master branch. @peracchi and @vegantom  in which one is happening to you ?

**Comment by vegantom** [comment] 2022-07-27 16:55
Whatever is on the July ISO downloaded from:
https://archlinux.org/download/

**Comment by dylanmtaylor** [comment] 2022-07-27 16:57
The code for this hasn't changed in a very long time, but I'm sure it used to work. I wonder what changed.

https://github.com/archlinux/archinstall/blob/master/examples/guided.py#L260

**Comment by peracchi** [comment] 2022-07-27 17:12
As I said, this behavior began only on july ISO...

To continue configuration after drop to shell I issue:

`root@archiso ~ # clear ; arch-chroot /mnt/archinstall`

and then make my changes/configurations.

**Comment by SamirPS** [comment] 2022-07-31 20:11
weird because drop to shell launch also arch-chroot :
https://github.com/archlinux/archinstall/blob/9194f6d85965f435f8d0ae44ba20e73cc761eb44/archinstall/lib/installer.py#L524

**Comment by jeffmhubbard** [comment] 2022-08-28 00:56
I'm having this issue with `archinstall` on the 2022.08.05 ISO also.

**Comment by Torxed** [comment] 2022-08-28 07:35
We'll sort this out before the next release, should be a very small fix. Just gotta find out why :)

**Comment by Torxed** [comment] 2022-08-28 22:19
Small variable comparison error, fixed now :) Thanks to everyone who reported it.

**Closed by Torxed** 2022-08-28 22:19 UTC
Labels: bug
