### ISSUE TITLE
Can't install, No such file or directory

### ISSUE THREAD

**Issue by Jonikster** [archlinux/archinstall#774] opened 2021-11-26 22:39 UTC
So, I launched Archinstall on my laptop. But after downloading the necessary components, I got errors like No such file or directory, Related too boot.
I tried different Archinstall parameters, but it cannot be installed.
I should also add that I'm blind, and was adding to the list of packages Espeakup and ORCA. But with the same settings of the installer, my friend was able to install Arch Linux...
I'm adding log file.
Help me please!
[install.log](https://github.com/archlinux/archinstall/files/7610832/install.log)

**Comment by dylanmtaylor** [comment] 2021-11-27 15:38
Hello, which version of ArchInstall did you use? I appreciate that you need accessibility tools, if you start the ISO with accessibility tools enabled with the 2.3.0 release, we detect that and automatically install and enable espeak on the installed system. I would suggest trying again with 2.3.0 when it is avaialable in the December 1st ISO when it releases (or use the ISO from the tagged release commit -- it will be the same version the Arch project ships).

**Comment by Jonikster** [comment] 2021-11-27 16:51
I use last version now from 01.11.
I'm so sorry, I didn't find new iso.
Just now I don't know better distribution than Arch Linux. I really hope to use it.
Can you send the link where I can download new iso with new ArchInstall?

**Comment by Torxed** [comment] 2021-11-27 18:05
> I use last version now from 01.11. I'm so sorry, I didn't find new iso. Just now I don't know better distribution than Arch Linux. I really hope to use it. Can you send the link where I can download new iso with new ArchInstall?

It will be released 01.12 (in 4 days)

**Comment by Torxed** [comment] 2021-11-27 18:06
A bleeding edge version can be found here: https://github.com/archlinux/archinstall/suites/4475156927/artifacts/119103181

**Comment by DestroyerXyz** [comment] 2021-11-27 20:27
@Jonikster Or you can just update archinstall in the current archiso using `pacman -S archinstall`.

**Comment by wllacer** [comment] 2021-11-27 22:00
issue has the same log info as issue #646. For some reason format of the boot partition fails

**Comment by Jonikster** [comment] 2021-11-27 22:34
I tried the image of 26.11, on the virtual machine, sound works, but doesn't work on the real!
Now I will try to update archinstall with pacman, ok.

**Comment by dylanmtaylor** [comment] 2021-11-28 02:42
> I tried the image of 26.11, on the virtual machine, sound works, but doesn't work on the real! Now I will try to update archinstall with pacman, ok.

So it successfully installed but you don't have working sound on the installed system? Strange. That seems like a different issue than this one though. Definitely a valid concern if it isn't working. All the accessibility packages and sound related packages should be installed if you boot the iso with accessibility tools.

**Comment by dylanmtaylor** [comment] 2021-11-28 03:02
The accessibility tools handling was added in https://github.com/archlinux/archinstall/commit/72d02a391dd1f2aedaeaac59b943d8655366bb3e. I'm wondering if missing something like orka would be the issue. Are you not having a functioning espeakup on the console or is this in the desktop environment e.g. GNOME?

**Comment by DestroyerXyz** [comment] 2021-11-28 06:48
I think the main problem happens at `Could not strap in packages: 256`. The logging is not very verbose. A very similar kind of issue happened to me and I investigated a little bit and found that the Linux root filesystem was not created but the script was already trying to edit the fstab.

**Comment by Jonikster** [comment] 2021-11-28 09:38
Yes, I was tried to download Accessible Mode, and the console opened! But sound doesn't work.
So, I launched an image from 01.11, executed:
pacman -Sy
pacman -S archinstall
It should be said that during installation I was not able to create a user.
Installation completed without errors. But when I rebooted the device, I got some kind of log.
I tried to make a video with it, but as I know, it's not very clearly visible:
https://youtu.be/kfvDVOGe1RY
I installed Mate. It didn't start.
I tried it on a virtual machine. And as I understood from OCR recognition, I got the authorization window. But my root password doesn't work, the installer doesn't offer other users creating.
But as I understand it, on a real machine I have another window with some logs.

**Comment by Torxed** [comment] 2021-11-28 09:38
> I think the main problem happens at `Could not strap in packages: 256`. The logging is not very verbose. A very similar kind of issue happened to me and I investigated a little bit and found that the Linux root filesystem was not created but the script was already trying to edit the fstab.

Tha should be fixed in the new release that was released three days ago

**Comment by DestroyerXyz** [comment] 2021-11-28 09:43
> > I think the main problem happens at `Could not strap in packages: 256`. The logging is not very verbose. A very similar kind of issue happened to me and I investigated a little bit and found that the Linux root filesystem was not created but the script was already trying to edit the fstab.
> 
> Tha should be fixed in the new release that was released three days ago

Yes it doesn't happen on the latest release

**Comment by Torxed** [comment] 2021-11-28 10:23
> > > I think the main problem happens at `Could not strap in packages: 256`. The logging is not very verbose. A very similar kind of issue happened to me and I investigated a little bit and found that the Linux root filesystem was not created but the script was already trying to edit the fstab.
> > 
> > 
> > Tha should be fixed in the new release that was released three days ago
> 
> Yes it doesn't happen on the latest release

I'll investigate, but this specific error shouldn't allow the code to continue because we raise an exception in v2.3.0: https://github.com/archlinux/archinstall/blob/7fd26817a1e303088da4e64481eb98fa85b3815b/archinstall/lib/installer.py#L255-L257

And as long as there's no `try` on any `pacstrap` calls and as long as `with` context is used on the `archinstall.Installer()` these errors should be raised to the user: https://github.com/archlinux/archinstall/blob/7fd26817a1e303088da4e64481eb98fa85b3815b/archinstall/lib/installer.py#L130-L143

I can probably try and reproduce this issue by unplugging the network during any pacstrap in the installer.

**Comment by Torxed** [comment] 2021-11-28 10:29
> on a real machine I have another window with some logs.

The video shows your boot process which has failed to mount `/root` properly, so it dropped you into a EFI recovery shell.
I'm not sure why that is, it's trying to mount `new_root` which I have never seen before. I'll go through your logs one more time and see if I find anything out of the ordinary.

**Comment by Jonikster** [comment] 2021-11-28 11:08
> The video shows your boot process which has failed to mount `/root` properly, so it dropped you into a EFI recovery shell. I'm not sure why that is, it's trying to mount `new_root` which I have never seen before. I'll go through your logs one more time and see if I find anything out of the ordinary.

Anyway, on the virtual machine, I cannot log in after installation. Moreover, during installation, I don't install users.
I could with Chroot after installation, but I hope on Archinstall.

**Comment by Jonikster** [comment] 2021-11-28 11:37
Well! I could boot into Mate with root (!), but or the sound doesn't work, or ORCA. Although I pointed out among packages.
When I was able to install the system on a virtual machine with an old ArchInstall installer with the creation of users, it worked.

**Comment by dylanmtaylor** [comment] 2021-11-28 13:27
> my root password doesn't work, the installer doesn't offer other users creating. But as I understand it, on a real machine I have another window with some logs.

The installer offers to let you create a super user if you do not supply a root password

**Comment by Jonikster** [comment] 2021-11-28 13:50
Ok, i will try. But I still don't understand why I couldn't run Mate on a real machine, and why there is no sound in the virtual machine.

**Comment by Jonikster** [comment] 2021-11-28 19:03
So. I tried to install Arch Linux with the image from 01.11, but with the new ArchInstall, without root, but with the Super user.
I got a window, unsure that the same, but Mate didn't boot.
https://youtu.be/-zguapHu0rw

**Comment by DestroyerXyz** [comment] 2021-11-28 21:07
@Jonikster It's good if you are doing this to find bugs and improve the project or just for fun but don't except archinstall to give you a completely usable desktop system as it is still in an early alpha stage

**Comment by Torxed** [comment] 2021-11-28 21:17
> I should also add that I'm blind, and was adding to the list of packages Espeakup and ORCA. But with the same settings of the installer, my friend was able to insta

@Jonikster mentioned that he is blind, so I'm not sure it's a desktop in that sense?
Either way, @Jonikster would you be able to provide us with the following three things:
* `/var/log/archinstall/install.log`
* `/var/log/archinstall/user_configuration.json`
* `/var/log/archinstall/user_disk_layouts.json`

**Comment by Torxed** [comment] 2021-11-29 11:22
> > @Jonikster would you be able to provide us with the following three things:
> > 
> > * `/var/log/archinstall/install.log`
> > * `/var/log/archinstall/user_configuration.json`
> > * `/var/log/archinstall/user_disk_layouts.json`
> 
> [install.log](https://github.com/archlinux/archinstall/files/7616782/install.log) About .json files, github don't support them, I just add .log to end of file. [user_configuration.json.log](https://github.com/archlinux/archinstall/files/7616804/user_configuration.json.log) [user_disk_layout.json.log](https://github.com/archlinux/archinstall/files/7616809/user_disk_layout.json.log)

I suspect that you might have additional installations on one or more of your harddrives or using specific hardware?

Because in the video the boot process is looking for a partition with the `PARTUUID` of `f584cada-3026-4750-a9b8-60f5d87fe5f5`. However the installation that was performed partitioned and used a `PARTUUID` of `7304ca13-d1ad-45b7-8c39-7980075ca898` as it's root partition.

We can verify this by *(just right after running the installer to completion)* running `cat /mnt/archinstall/boot/loader/entries/*` and it should show `options root=PARTUUID=7304ca13-d1ad-45b7-8c39-7980075ca898` and not `options root=PARTUUID=f584cada-3026-4750-a9b8-60f5d87fe5f5`. Also running `lsblk -o+PARTUUID` should verify the `PARTUUID`'s as well.

If you however do not have multiple devices, then maybe the hardware you are using have RAID enabled in BIOS? or that you're running Intel VMD? In both cases the installation will continue but error out during boot. We're currently tracking that issue in #671.

**Comment by Jonikster** [comment] 2021-11-29 12:27
I use one SSD and USB with Arch Linux. Don't have other.
When I start the image, I get DRM error. That's all.
In addition, I can't boot from Boot Menu.
ArchInstall doesn't help in the installation more, but makes force to learn manual installation! 😊

**Comment by Jonikster** [comment] 2021-12-01 19:00
Hello!
So, I have tried the last image of Arch Linux from 01.12.2021.
And the sound doesn't work in Accessibility Installer!
It works in the virtual machine, but doesn't work in real.
The old image works in virtual, and in real machine.
Where can I report it?
P.S.
I was able to install all the components with ArchInstall in the virtual machine with the new image! It works!

**Comment by Torxed** [comment] 2022-02-07 18:21
Just dropping by to say I'll investigate this soon, I'm fixing some partitioning issues after which stability work commences (accessibility being one of them).

**Comment by mhussaincov93** [comment] 2022-02-07 19:27
cheers!

**Comment by svartkanin** [comment] 2022-09-04 10:34
@Torxed should we consider this as resolved or is there anything we can investigate here?

**Comment by Torxed** [comment] 2022-09-19 18:59
I believe this is fixed and can be closed.
Just a note to the visually impaired, we're working on getting Orca setup. To follow that progress see the separate issue ticket over at https://github.com/archlinux/archinstall/issues/1472

If however the issue remains, feel free to open a new ticket!

**Closed by Torxed** 2022-09-19 18:59 UTC
