### ISSUE TITLE
failed to connect to bus

### ISSUE THREAD

**Issue by spleaque** [archlinux/archinstall#2771] opened 2024-11-03 17:37 UTC
### Which ISO version are you using?

 2024.11.01

### The installation log

```json
Setting up swap on zram
Installing packages: ['zram-generator']
Enabling service systemd-zram-setup@zram0.service
Adding bootloader Systemd-boot to /dev/nvme0n1p1
Installing systemd bootloader
Installing packages: ['efibootmgr']
Identifying root partition by PARTUUID: d3a634b9-43d9-4b0b-a86e-0936d1c3d05b
kernel parameters: root=PARTUUID=d3a634b9-43d9-4b0b-a86e-0936d1c3d05b zswap.enabled=0 rootflags=subvol=@ rw rootfstype=btrfs
Installing packages: ['networkmanager']
Installing packages: ['network-manager-applet']
Enabling service NetworkManager.service
Creating user arch
Setting password for arch
Enabling sudo permissions for arch
Installing audio server: Pipewire
Installing packages: ['pipewire', 'pipewire-alsa', 'pipewire-jack', 'pipewire-pulse', 'gst-plugin-pipewire', 'libpulse', 'wireplumber']
['/usr/bin/arch-chroot', '/mnt/archinstall', 'su', '-', 'arch', '-c', 'systemctl enable --user pipewire-pulse.service'] exited with abnormal exit code [1]: [0;1;31mFailed to connect to bus: No medium found[0m


Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 356, in run_as_a_module
    main()
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 331, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 246, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', Path('/mnt')))
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 116, in perform_installation
    with Installer(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 111, in __exit__
    raise exc_val
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 173, in perform_installation
    audio_config.install_audio_config(installation)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/models/audio_configuration.py", line 46, in install_audio_config
    PipewireProfile().install(installation)
  File "/usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py", line 40, in install
    self._enable_pipewire_for_all(install_session)
  File "/usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py", line 35, in _enable_pipewire_for_all
    install_session.arch_chroot('systemctl enable --user pipewire-pulse.service', run_as=user.username)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 632, in arch_chroot
    return self.run_command(cmd)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 626, in run_command
    return SysCommand(f'/usr/bin/arch-chroot {self.target} {cmd}')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 366, in __init__
    self.create_session()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 415, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 198, in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'su', '-', 'arch', '-c', 'systemctl enable --user pipewire-pulse.service'] exited with abnormal exit code [1]: [0;1;31mFailed to connect to bus: No medium found[0m



Archinstall experienced the above error. If you think this is a bug, please report it to
https://github.com/archlinux/archinstall and include the log file "/var/log/archinstall/install.log".

Hint: To extract the log from a live ISO 
curl -F'file=@/var/log/archinstall/install.log' https://0x0.st
```

#### Description of the issue

I was installing Arch on a Dell Inspiron 5515 laptop and suddenly this error pops up. Failed to connect to bus: No medium found. Please help me. I'm not using a virtual machine BTW.  http://0x0.st/XGtC.log

**Comment by dev-aphex** [comment] 2024-11-03 19:55
same as [ Failed installation: pipewire-pulse.service could not be started #2764 ](https://github.com/archlinux/archinstall/issues/2764)

**Comment by spleaque** [comment] 2024-11-04 00:55
> [ Failed installation: pipewire-pulse.service could not be started #2764 ](https://github.com/archlinux/archinstall/issues/2764)
> 
> do not select a sound server and install manually afterwards
> 
> `pacman -S pipewire wireplumber pipewire-pulse pipewire-alsa` `systemctl --user enable --now pipewire.service wireplumber.service pipewire-pulse.service`

Thank you so much!

**Comment by svartkanin** [comment] 2024-11-04 03:16
Given its a duplicate of https://github.com/archlinux/archinstall/issues/2764 I'll close this

**Closed** 2024-11-04 03:16 UTC

**Comment by wpreisingCS50** [comment] 2024-11-05 15:54
Also experiencing this issue but @spleaque's suggestion fixed it for me! I ran those steps during the "post installation configuration" and worked like a charm. Thanks mate!
