### ISSUE TITLE
Error Install

### ISSUE THREAD

**Issue by palaboy** [archlinux/archinstall#1713] opened 2023-04-01 16:42 UTC
archinstall v2.5.4-1

![archinstall error](https://user-images.githubusercontent.com/2505495/229303583-af0de691-0fd8-4bdd-a213-871940a81663.png)

**Comment by Ar1soN** [comment] 2023-04-01 16:58
I have the same problem

**Comment by RotaN8** [comment] 2023-04-01 17:30
Check this guys: #1712 
I was having the same issue and I found that, before asking search the currently issues (including closed ones) to check if it is already solved ;)

**Comment by Torxed** [comment] 2023-04-01 21:58
Duplicate of https://github.com/archlinux/archinstall/pull/1704

**Closed by Torxed** 2023-04-01 21:58 UTC
