### ISSUE TITLE
Error while using the latest Arch ISO

### ISSUE THREAD

**Issue by mmahmoudian** [archlinux/archinstall#2158] opened 2023-10-12 12:06 UTC
I have used `´archinstall` before and it always worked beautifully, but today I tried the latest Arch ISO (`archlinux-2023.09.01-x86_64.iso` with sha1sum `96267f75de79681d476e17d94cab21cdac3a6192`) and I hit this error:

![image](https://github.com/archlinux/archinstall/assets/390889/43bc1ad8-f6b6-45e6-83c1-9f8b07898179)

I tried it few times and every time it failed. So I tried my best to replicate the config I had:

[user_credentials.json](https://github.com/archlinux/archinstall/files/12881894/user_credentials.json)
[user_configuration.json](https://github.com/archlinux/archinstall/files/12881895/user_configuration.json)

But when I do `archinstall --config /user_configuration.json --cred /user_credentials.json` it works just fine!!

This got me suspicious that the process of loading the config is not the same as the process of making the config and them install. So I recorded the whole thing from scratch (from creating a VM up to the error): 

[Peek 2023-10-12 15-04.webm](https://github.com/archlinux/archinstall/assets/390889/91e5007e-7c22-490d-8fb1-35026551b5a1)

<details>
<summary>In case you want to build the same exact VM, this XML can be used (click to expand)</summary>

```xml
<domain type="kvm">
  <name>archlinux_sway_cleaninstall</name>
  <uuid>8531ea27-8148-4505-926a-e00cfe3c8d38</uuid>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://archlinux.org/archlinux/rolling"/>
    </libosinfo:libosinfo>
  </metadata>
  <memory unit="KiB">2097152</memory>
  <currentMemory unit="KiB">2097152</currentMemory>
  <vcpu placement="static">1</vcpu>
  <os>
    <type arch="x86_64" machine="pc-q35-8.1">hvm</type>
    <boot dev="hd"/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <vmport state="off"/>
  </features>
  <cpu mode="host-passthrough" check="none" migratable="on"/>
  <clock offset="utc">
    <timer name="rtc" tickpolicy="catchup"/>
    <timer name="pit" tickpolicy="delay"/>
    <timer name="hpet" present="no"/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <pm>
    <suspend-to-mem enabled="no"/>
    <suspend-to-disk enabled="no"/>
  </pm>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type="file" device="disk">
      <driver name="qemu" type="qcow2" discard="unmap"/>
      <source file="/home/mehrad/.local/share/libvirt/images/archlinux_sway_cleaninstall.qcow2"/>
      <target dev="vda" bus="virtio"/>
      <address type="pci" domain="0x0000" bus="0x04" slot="0x00" function="0x0"/>
    </disk>
    <disk type="file" device="cdrom">
      <driver name="qemu" type="raw"/>
      <target dev="sda" bus="sata"/>
      <readonly/>
      <address type="drive" controller="0" bus="0" target="0" unit="0"/>
    </disk>
    <controller type="usb" index="0" model="qemu-xhci" ports="15">
      <address type="pci" domain="0x0000" bus="0x02" slot="0x00" function="0x0"/>
    </controller>
    <controller type="pci" index="0" model="pcie-root"/>
    <controller type="pci" index="1" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="1" port="0x10"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x0" multifunction="on"/>
    </controller>
    <controller type="pci" index="2" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="2" port="0x11"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x1"/>
    </controller>
    <controller type="pci" index="3" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="3" port="0x12"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x2"/>
    </controller>
    <controller type="pci" index="4" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="4" port="0x13"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x3"/>
    </controller>
    <controller type="pci" index="5" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="5" port="0x14"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x4"/>
    </controller>
    <controller type="pci" index="6" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="6" port="0x15"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x5"/>
    </controller>
    <controller type="pci" index="7" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="7" port="0x16"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x6"/>
    </controller>
    <controller type="pci" index="8" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="8" port="0x17"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x7"/>
    </controller>
    <controller type="pci" index="9" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="9" port="0x18"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x0" multifunction="on"/>
    </controller>
    <controller type="pci" index="10" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="10" port="0x19"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x1"/>
    </controller>
    <controller type="pci" index="11" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="11" port="0x1a"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x2"/>
    </controller>
    <controller type="pci" index="12" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="12" port="0x1b"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x3"/>
    </controller>
    <controller type="pci" index="13" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="13" port="0x1c"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x4"/>
    </controller>
    <controller type="pci" index="14" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="14" port="0x1d"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x5"/>
    </controller>
    <controller type="sata" index="0">
      <address type="pci" domain="0x0000" bus="0x00" slot="0x1f" function="0x2"/>
    </controller>
    <controller type="virtio-serial" index="0">
      <address type="pci" domain="0x0000" bus="0x03" slot="0x00" function="0x0"/>
    </controller>
    <interface type="user">
      <mac address="52:54:00:32:16:3a"/>
      <model type="virtio"/>
      <address type="pci" domain="0x0000" bus="0x01" slot="0x00" function="0x0"/>
    </interface>
    <serial type="pty">
      <target type="isa-serial" port="0">
        <model name="isa-serial"/>
      </target>
    </serial>
    <console type="pty">
      <target type="serial" port="0"/>
    </console>
    <channel type="unix">
      <target type="virtio" name="org.qemu.guest_agent.0"/>
      <address type="virtio-serial" controller="0" bus="0" port="1"/>
    </channel>
    <channel type="spicevmc">
      <target type="virtio" name="com.redhat.spice.0"/>
      <address type="virtio-serial" controller="0" bus="0" port="2"/>
    </channel>
    <input type="tablet" bus="usb">
      <address type="usb" bus="0" port="1"/>
    </input>
    <input type="mouse" bus="ps2"/>
    <input type="keyboard" bus="ps2"/>
    <graphics type="spice" autoport="yes">
      <listen type="address"/>
      <image compression="off"/>
    </graphics>
    <sound model="ich9">
      <address type="pci" domain="0x0000" bus="0x00" slot="0x1b" function="0x0"/>
    </sound>
    <audio id="1" type="spice"/>
    <video>
      <model type="virtio" heads="1" primary="yes"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x0"/>
    </video>
    <redirdev bus="usb" type="spicevmc">
      <address type="usb" bus="0" port="2"/>
    </redirdev>
    <redirdev bus="usb" type="spicevmc">
      <address type="usb" bus="0" port="3"/>
    </redirdev>
    <watchdog model="itco" action="reset"/>
    <memballoon model="virtio">
      <address type="pci" domain="0x0000" bus="0x05" slot="0x00" function="0x0"/>
    </memballoon>
    <rng model="virtio">
      <backend model="random">/dev/urandom</backend>
      <address type="pci" domain="0x0000" bus="0x06" slot="0x00" function="0x0"/>
    </rng>
  </devices>
</domain>
```

</details>

**Comment by svartkanin** [comment] 2023-10-12 19:49
Can you please submit the log file/var/log/atchinstall/install.log

**Comment by Torxed** [comment] 2023-10-12 20:43
2:03 in to the video, you're running `archinstall` version 2.6.0 which is a few versions behind.
This happens due to the latest ISO being built 2023.09.01 and we've released versions since then.

Your best bet is to update archinstall specifically with `pacman -Sy archinstall` *(and if you run out of disk space, our README will instruct you on how to increase it)*. After that most bugs should be fixed :)

**Comment by mmahmoudian** [comment] 2023-10-13 04:08
Thanks, I'll try and report back.

But assuming that I've hit this with a very simple config, others will also hit this others would hit his too (although surprisingly I didn't find any other bug reports in this repo, and the iso is already out for a month?), so can this be pushed to Arch folks to update this in their iso?

**Comment by Torxed** [comment] 2023-10-13 06:57
I'm part of the Arch folks hehe. The issue is the signing key for the ISO could not for personal reasons sign the ISO this month and the signing process is sadly manual to a very faulty degree.

Others have reported this issue but under many various titles hehe.

So both issues are known and being worked on, however there is no clear consensus as to which is the best way to deal with the ISO so it's taken a few years to tackle:/

**Comment by numbawon** [comment] 2023-10-14 06:33
I was able to do a fresh install from the latest September iso.

When booting from the iso, I had press e to edit the boot string and add the 'cow_spacesize=4G' to the entry then press ctrl-x to boot.
Once booted, 'timedatectl set-ntp true' you can use 1, true, or yes to turn it on. 
Next I 'pacman -Sy archinstall python systemd'
then ran 'archinstall'

I'd be curious if anybody else has success. I know from TONS of reading there is a python bug and a systemd but both in play from previous verisons, and also that archinstall has a dependency for accurate time. I also feel like based on the latest release dates of these packages, the October iso would have had these fixes in place but there isn't an October iso for some reason.

Also I did this on a Windows 11 host via Hyper-V machine. I was able to validate the exact output from OP, which I think was the systemd update fixed that. You can start the archinstall script, but it fails during install

The other bug I was getting had to do with Python, where you can run the archinstall script and it fails to run the script. 

but YMMV, these are mostly my own reading and observations. I plan to reinstall the above mentioned process on another machine tomorrow to validate.

**Comment by Torxed** [comment] 2023-10-14 08:46
> October iso would have had these fixes in place but there isn't an October iso for some reason.

I explained why above.

> you can run the archinstall script and it fails to run the script.

This is because `archinstall` was built against `python3.11`, and the way Python looks up modules with `python -m <module>` it fails because `python3.10` will only look in it's module library - whereas `archinstall` is installed to the `python3.11` module library *(it's just a path essentiall)*.

I'm going to close this ticket as the only workaround until a new ISO is out, is doing what's in the README and comments in this thread:

1. Add boot parameter `cow_spacesize=4G` or as per README `copytoram=y` to automatically adjust the size to your platforms capabilities
2. Do `pacman -Sy archinstall python` *(If you're running a really old ISO with an old Python version, otherwise just `pacman -Sy archinstall` should save you some time and space)*
3. Run archinstall as usual

I can only apologize for the inconvenience on behalf of Arch, we're working towards automating the ISO build process in a secure and manageable way.

**Closed by Torxed** 2023-10-14 08:46 UTC
