### ISSUE TITLE
archinstall --config $yourconfigfile --creds &yourcredsfile dont work

### ISSUE THREAD

**Issue by solisinvictum** [archlinux/archinstall#2536] opened 2024-06-12 22:02 UTC
Like title.

To reproduce:

1) download latest iso from archlinux.org
2) start archinstall
3) configure everything from top to bottom
4) save both configs to /root/ for example
5) quit archinstall
6) start archinstall with:  archinstall --config /root/user_configuration.json --creds /root/user_credentials.json
7) see error output:

```
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_model.py", line 1113, in _fetch_lsblk_info
    result = SysCommand(cmd).decode()
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 365, in __init__
    self.create_session()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 414, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 197, in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/lsblk', '--json', '--bytes', '--output', '+name,path,pkname,size,log-sec,pttype,ptuuid,rota,tran,partn,partuuid,parttype,uuid,fstype,fsver,fsavail,fsuse%,type,mountpoint,mountpoints,fsroots', '/dev/sda1'] exited with abnormal exit code [32]: lsblk: /dev/sda1: not a block device
{
   "blockdevices": [

   ]
}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/archinstall", line 5, in <module>
    from archinstall import run_as_a_module
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 11, in <module>
    from .lib import disk
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/__init__.py", line 1, in <module>
    from .device_handler import device_handler, disk_layouts
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 649, in <module>
    device_handler = DeviceHandler()
                     ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 38, in __init__
    self.load_devices()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 74, in load_devices
    lsblk_info = get_lsblk_info(partition.path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_model.py", line 1136, in get_lsblk_info
    if infos := _fetch_lsblk_info(dev_path):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_model.py", line 1121, in _fetch_lsblk_info
    raise DiskError(f'Failed to read disk "{dev_path}" with lsblk')
archinstall.lib.exceptions.DiskError: Failed to read disk "/dev/sda1" with lsblk
```

8) try again only with: archinstall --config /root/user_configuration.json 
9) this works, but credentials are missing.

**Comment by svartkanin** [comment] 2024-06-22 02:22
I'm unable to reproduce this. Can you please provide the log file /var/log/archinstall/install.log

**Comment by codefiles** [comment] 2024-07-06 13:33
Duplicate of #1993

**Closed** 2024-08-24 07:30 UTC
