### ISSUE TITLE
error waiting for events:unsupported

### ISSUE THREAD

**Issue by adaaaaaa** [archlinux/archinstall#842] opened 2022-01-05 20:20 UTC
11.01 is fine
but 12.01 and 01.01 come out that error...

**Comment by Torxed** [comment] 2022-01-05 20:51
Do you have a screenshot, traceback or some other information as to what `events:unsupported` means?
I don't think I've ever seen it so I don't know what you're referring to unfortunately.

**Comment by adaaaaaa** [comment] 2022-01-05 21:45
https://user-images.githubusercontent.com/23206387/148294086-c1632cca-35ed-4b49-b763-7f0fc126e5d9.mp4

@Torxed

**Comment by Torxed** [comment] 2022-01-05 21:50
This error is before `archinstall` even runs.
It looks to me like you have a hardware issue.

I would probably as over at IRC or in the Arch forums for general support, as it looks like the boot menu for the official Arch Linux ISO. Is that assumption correct?

**Comment by adaaaaaa** [comment] 2022-01-05 21:58
> have a hardware issue

nope.Manjaro ISO and 11.01 archiso is OK.


> it looks like the boot menu for the official Arch Linux ISO

yes , it's 12.01 ISO and  the same error appear in 01.01
@Torxed

**Comment by Torxed** [comment] 2022-01-05 22:10
> nope.Manjaro ISO and 11.01 archiso is OK.

A lot change in between the ISO versions. And sometimes there's regression in `linux-firmware` or some other package that makes for hardware issues. This is maybe one of those times.

Since this is related to the Arch Linux ISO and not archinstall (two separate projects), I will go ahead and close this as we'd like to keep only archinstall related issues open in this repository.

Hop over to https://bbs.archlinux.org/ and ask for general boot help with the latest ISO.

**Closed by Torxed** 2022-01-05 22:10 UTC
