### ISSUE TITLE
Could not configure GRUB - /boot/efi

### ISSUE THREAD

**Issue by georgeabr** [archlinux/archinstall#2449] opened 2024-04-07 13:53 UTC
Install log file here - http://0x0.st/XiLP.log  
I did a `pacman -Sy archinstall` on the April 2024 live cd first.  
Specified mountpoint is `/boot/efi` in manual partitioning.   
Relevant log entries  
```
GRUB boot partition: /dev/nvme0n1p1
GRUB EFI partition: /dev/nvme0n1p1
Installing packages: ['efibootmgr']
Could not configure GRUB: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'grub-mkconfig', '-o', '/boot/efi/grub/grub.cfg'] exited with abnormal exit code [1]: /usr/bin/grub-mkconfig: line 270: /boot/efi/grub/grub.cfg.new: No such file or directory
```

**Comment by codefiles** [comment] 2024-04-09 02:11
Duplicate of #2372

**Closed** 2024-04-09 05:13 UTC
