### ISSUE TITLE
Errors when tring to install to specific partition. "'<' not supported between instances of 'dict' and 'dict'"

### ISSUE THREAD

**Issue by JeremiahCheatham** [archlinux/archinstall#1305] opened 2022-06-04 13:28 UTC
Laptop has single drive no upgrade path. Windows/Linux. My old arch install uses first partition for /boot and  5th for archlinux.
setting /boot mount point then wiping 5th setting to btrfs with compression then adding @, @home, @log, @pkg, @.snapshots as sub. The result doesn't visually look the same as if i choose to wipe. But not sure if that has anything to do with it.

````
Hardware model detected: LENOVO 82HU; UEFI mode: True
Processor model detected: AMD Ryzen 7 5700U with Radeon Graphics
Memory statistics: 6203852 available out of 7546472 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
Virtualization detected: None; is VM: None
Graphics devices detected: dict_keys(['Advanced Micro Devices, Inc. [AMD/ATI] Lucienne (rev c1)'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '688.2M'}, {'name': 'sda', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202206', 'uuid': '2022-06-01-15-35-22-00', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '7.2G', 'children': [{'name': 'sda1', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202206', 'uuid': '2022-06-01-15-35-22-00', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '775M'}, {'name': 'sda2', 'fstype': 'vfat', 'fsver': 'FAT16', 'label': 'ARCHISO_EFI', 'uuid': '785A-FB3F', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '86M'}]}, {'name': 'nvme0n1', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '476.9G', 'children': [{'name': 'nvme0n1p1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': 'SYSTEM_DRV', 'uuid': '7438-0E47', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '260M'}, {'name': 'nvme0n1p2', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '16M'}, {'name': 'nvme0n1p3', 'fstype': 'ntfs', 'fsver': None, 'label': 'Windows-SSD', 'uuid': '14BA3B01BA3ADEC4', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '237.4G'}, {'name': 'nvme0n1p4', 'fstype': 'ntfs', 'fsver': None, 'label': 'WINRE_DRV', 'uuid': 'DC923C29923C0B12', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '1000M'}, {'name': 'nvme0n1p5', 'fstype': 'btrfs', 'fsver': None, 'label': None, 'uuid': 'dc367d31-29ee-40a9-9bf5-6cfe0c32fe6f', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '60G'}, {'name': 'nvme0n1p6', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': None, 'uuid': '02C2-2896', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '60G'}]}]}
Testing connectivity to the Arch Linux mirrors ...
Marked partition as bootable because mountpoint was set to /boot.
Hardware model detected: LENOVO 82HU; UEFI mode: True
Processor model detected: AMD Ryzen 7 5700U with Radeon Graphics
Memory statistics: 6200500 available out of 7546472 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
Virtualization detected: None; is VM: None
Graphics devices detected: dict_keys(['Advanced Micro Devices, Inc. [AMD/ATI] Lucienne (rev c1)'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '688.2M'}, {'name': 'sda', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202206', 'uuid': '2022-06-01-15-35-22-00', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '7.2G', 'children': [{'name': 'sda1', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202206', 'uuid': '2022-06-01-15-35-22-00', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '775M'}, {'name': 'sda2', 'fstype': 'vfat', 'fsver': 'FAT16', 'label': 'ARCHISO_EFI', 'uuid': '785A-FB3F', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '86M'}]}, {'name': 'nvme0n1', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '476.9G', 'children': [{'name': 'nvme0n1p1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': 'SYSTEM_DRV', 'uuid': '7438-0E47', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '260M'}, {'name': 'nvme0n1p2', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '16M'}, {'name': 'nvme0n1p3', 'fstype': 'ntfs', 'fsver': None, 'label': 'Windows-SSD', 'uuid': '14BA3B01BA3ADEC4', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '237.4G'}, {'name': 'nvme0n1p4', 'fstype': 'ntfs', 'fsver': None, 'label': 'WINRE_DRV', 'uuid': 'DC923C29923C0B12', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '1000M'}, {'name': 'nvme0n1p5', 'fstype': 'btrfs', 'fsver': None, 'label': None, 'uuid': 'dc367d31-29ee-40a9-9bf5-6cfe0c32fe6f', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '60G'}, {'name': 'nvme0n1p6', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': None, 'uuid': '02C2-2896', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '60G'}]}]}
Testing connectivity to the Arch Linux mirrors ...
Marked partition as bootable because mountpoint was set to /boot.
 -- Chosen configuration --
{
    "HSM": null,
    "__separator__": null,
    "additional-repositories": [],
    "archinstall-language": "English",
    "audio": "pipewire",
    "bootloader": "systemd-bootctl",
    "config_version": "2.5.0",
    "debug": false,
    "desktop-environment": "kde",
    "gfx_driver": "AMD / ATI (open-source)",
    "harddrives": [
        "/dev/nvme0n1"
    ],
    "hostname": "Arch",
    "kernels": [
        "linux"
    ],
    "keyboard-layout": "uk",
    "mirror-region": {
        "United Kingdom": {
            "http://archlinux.uk.mirror.allworldit.com/archlinux/$repo/os/$arch": true,
            "http://lon.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
            "http://mirror.bytemark.co.uk/archlinux/$repo/os/$arch": true,
            "http://mirror.cov.ukservers.com/archlinux/$repo/os/$arch": true,
            "http://mirror.netweaver.uk/archlinux/$repo/os/$arch": true,
            "http://mirrors.manchester.m247.com/arch-linux/$repo/os/$arch": true,
            "http://mirrors.melbourne.co.uk/archlinux/$repo/os/$arch": true,
            "http://www.mirrorservice.org/sites/ftp.archlinux.org/$repo/os/$arch": true,
            "https://archlinux.uk.mirror.allworldit.com/archlinux/$repo/os/$arch": true,
            "https://lon.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
            "https://mirror.bytemark.co.uk/archlinux/$repo/os/$arch": true,
            "https://mirror.cov.ukservers.com/archlinux/$repo/os/$arch": true,
            "https://mirror.netweaver.uk/archlinux/$repo/os/$arch": true,
            "https://mirrors.melbourne.co.uk/archlinux/$repo/os/$arch": true,
            "https://www.mirrorservice.org/sites/ftp.archlinux.org/$repo/os/$arch": true
        }
    },
    "mount_point": null,
    "nic": {},
    "ntp": true,
    "packages": [
        "firefox",
        "pacman-contrib",
        "compsize"
    ],
    "plugin": null,
    "profile": {
        "path": "/usr/lib/python3.10/site-packages/archinstall/profiles/desktop.py"
    },
    "save_config": null,
    "script": "guided",
    "silent": false,
    "swap": true,
    "sys-encoding": "UTF-8",
    "sys-language": "en_GB",
    "timezone": "Europe/London",
    "version": "2.5.0"
}
{
    "/dev/nvme0n1": {
        "partitions": [
            {
                "ESP": true,
                "PARTUUID": "7438-0E47",
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "vfat"
                },
                "mountpoint": "/boot",
                "size": 532480,
                "start": 2048,
                "type": "primary",
                "wipe": false
            },
            {
                "ESP": false,
                "PARTUUID": "",
                "boot": false,
                "encrypted": false,
                "filesystem": {
                    "format": ""
                },
                "mountpoint": null,
                "size": 32768,
                "start": 534528,
                "type": "primary",
                "wipe": false
            },
            {
                "ESP": false,
                "PARTUUID": "14BA3B01BA3ADEC4",
                "boot": false,
                "encrypted": false,
                "filesystem": {
                    "format": "ntfs"
                },
                "mountpoint": null,
                "size": 497887232,
                "start": 567296,
                "type": "primary",
                "wipe": false
            },
            {
                "ESP": false,
                "PARTUUID": "DC923C29923C0B12",
                "boot": false,
                "encrypted": false,
                "filesystem": {
                    "format": "ntfs"
                },
                "mountpoint": null,
                "size": 2048000,
                "start": 998166528,
                "type": "primary",
                "wipe": false
            },
            {
                "ESP": false,
                "PARTUUID": "dc367d31-29ee-40a9-9bf5-6cfe0c32fe6f",
                "boot": false,
                "btrfs": {
                    "subvolumes": {
                        "@": {
                            "mountpoint": "/",
                            "options": [
                                "compress"
                            ]
                        },
                        "@.snapshots": {
                            "mountpoint": "/.snapshots",
                            "options": [
                                "compress"
                            ]
                        },
                        "@home": {
                            "mountpoint": "/home",
                            "options": [
                                "compress"
                            ]
                        },
                        "@log": {
                            "mountpoint": "/var/log",
                            "options": [
                                "compress"
                            ]
                        },
                        "@pkg": {
                            "mountpoint": "/var/cache/pacman/pkg",
                            "options": [
                                "compress"
                            ]
                        }
                    }
                },
                "encrypted": false,
                "filesystem": {
                    "format": "btrfs",
                    "mount_options": [
                        "compress=zstd"
                    ]
                },
                "mountpoint": null,
                "size": 125829120,
                "start": 498454528,
                "type": "primary",
                "wipe": true
            },
            {
                "ESP": false,
                "PARTUUID": "02C2-2896",
                "boot": false,
                "encrypted": false,
                "filesystem": {
                    "format": "vfat"
                },
                "mountpoint": null,
                "size": 125829120,
                "start": 624283648,
                "type": "primary",
                "wipe": false
            }
        ]
    }
}
Could not locate mount information for /dev/nvme0n1p1: ['/usr/bin/findmnt', '--json', '-R', '/dev/nvme0n1p1'] exited with abnormal exit code [256]: b''
Re-using partition instance: Partition(path=/dev/nvme0n1p1, size=0.3, PARTUUID=7438-0E47, fs=vfat)
Could not locate mount information for /dev/nvme0n1p1: ['/usr/bin/findmnt', '--json', '-R', '/dev/nvme0n1p1'] exited with abnormal exit code [256]: b''
Marking partition Partition(path=/dev/nvme0n1p1, size=0.3, PARTUUID=7438-0E47, fs=vfat) as bootable.
Setting boot on on (parted) partition index 1
Filesystem(blockdevice=BlockDevice(/dev/nvme0n1, size=476.9GB, free_space=1031kB+127GB+335kB, bus_type=nvme), mode=1).load_layout() doesn't know how to work without 'wipe' being set or UUID () was given and found.
Could not locate mount information for /dev/nvme0n1p2: ['/usr/bin/findmnt', '--json', '-R', '/dev/nvme0n1p2'] exited with abnormal exit code [256]: b''
Could not get UUID/PARTUUID of Partition(path=/dev/nvme0n1p2, size=0.0, PARTUUID=, fs=): Could not get PARTUUID for /dev/nvme0n1p2 using 'blkid -s PARTUUID -o value /dev/nvme0n1p2'
Could not locate mount information for /dev/nvme0n1p3: ['/usr/bin/findmnt', '--json', '-R', '/dev/nvme0n1p3'] exited with abnormal exit code [256]: b''
Re-using partition instance: Partition(path=/dev/nvme0n1p3, size=237.4, PARTUUID=14BA3B01BA3ADEC4, fs=ntfs)
Could not locate mount information for /dev/nvme0n1p2: ['/usr/bin/findmnt', '--json', '-R', '/dev/nvme0n1p2'] exited with abnormal exit code [256]: b''
Could not get UUID/PARTUUID of Partition(path=/dev/nvme0n1p2, size=0.0, PARTUUID=, fs=): Could not get PARTUUID for /dev/nvme0n1p2 using 'blkid -s PARTUUID -o value /dev/nvme0n1p2'
Could not locate mount information for /dev/nvme0n1p4: ['/usr/bin/findmnt', '--json', '-R', '/dev/nvme0n1p4'] exited with abnormal exit code [256]: b''
Re-using partition instance: Partition(path=/dev/nvme0n1p4, size=1.0, PARTUUID=DC923C29923C0B12, fs=ntfs)
Could not locate mount information for /dev/nvme0n1p2: ['/usr/bin/findmnt', '--json', '-R', '/dev/nvme0n1p2'] exited with abnormal exit code [256]: b''
Could not get UUID/PARTUUID of Partition(path=/dev/nvme0n1p2, size=0.0, PARTUUID=, fs=): Could not get PARTUUID for /dev/nvme0n1p2 using 'blkid -s PARTUUID -o value /dev/nvme0n1p2'
Could not locate mount information for /dev/nvme0n1p5: ['/usr/bin/findmnt', '--json', '-R', '/dev/nvme0n1p5'] exited with abnormal exit code [256]: b''
Re-using partition instance: Partition(path=/dev/nvme0n1p5, size=60.0, PARTUUID=dc367d31-29ee-40a9-9bf5-6cfe0c32fe6f, fs=btrfs)
Formatting /dev/nvme0n1p5 -> btrfs
Could not locate mount information for /dev/nvme0n1p2: ['/usr/bin/findmnt', '--json', '-R', '/dev/nvme0n1p2'] exited with abnormal exit code [256]: b''
Could not get UUID/PARTUUID of Partition(path=/dev/nvme0n1p2, size=0.0, PARTUUID=, fs=): Could not get PARTUUID for /dev/nvme0n1p2 using 'blkid -s PARTUUID -o value /dev/nvme0n1p2'
Could not locate mount information for /dev/nvme0n1p6: ['/usr/bin/findmnt', '--json', '-R', '/dev/nvme0n1p6'] exited with abnormal exit code [256]: b''
Re-using partition instance: Partition(path=/dev/nvme0n1p6, size=60.0, PARTUUID=02C2-2896, fs=vfat)
Could not locate mount information for /dev/nvme0n1p5: ['/usr/bin/findmnt', '--json', '-R', '/dev/nvme0n1p5'] exited with abnormal exit code [256]: b''
Could not locate mount information for /dev/nvme0n1p5: ['/usr/bin/findmnt', '--json', '-R', '/dev/nvme0n1p5'] exited with abnormal exit code [256]: b''
Mounting BTRFSPartition(path=/dev/nvme0n1p5, size=60.0, PARTUUID=8065b810-3e62-41dd-8578-7ebfe59dc144, fs=btrfs) to /mnt/archinstall/
Setting up subvolumes: {'@': {'mountpoint': '/', 'options': ['compress']}, '@home': {'mountpoint': '/home', 'options': ['compress']}, '@log': {'mountpoint': '/var/log', 'options': ['compress']}, '@pkg': {'mountpoint': '/var/cache/pacman/pkg', 'options': ['compress']}, '@.snapshots': {'mountpoint': '/.snapshots', 'options': ['compress']}}
Attempting to create subvolume at /mnt/archinstall/@
Attempting to create subvolume at /mnt/archinstall/@home
Attempting to create subvolume at /mnt/archinstall/@log
Attempting to create subvolume at /mnt/archinstall/@pkg
Attempting to create subvolume at /mnt/archinstall/@.snapshots
'<' not supported between instances of 'dict' and 'dict'
````

**Comment by Torxed** [comment] 2022-06-04 13:57
Thank you for the report, we'll check it out! :)

**Comment by JeremiahCheatham** [comment] 2022-06-04 14:37
Yeah any info you can give me since at the moment i don't have a working laptop until i can install arch again.

**Comment by svartkanin** [comment] 2022-06-04 22:05
@Torxed the update for subvolumes #1297 may possibly fix it but I'm not entirely sure. 

@JeremiahCheatham if you feel like it, you could try cloning the repo, checking out branch "git checkout fix-1278" and giving it a try with "python -m archinstall" :)

**Comment by JeremiahCheatham** [comment] 2022-06-04 22:22
Yeah I'm happy to give it a go.

**Comment by JeremiahCheatham** [comment] 2022-06-04 22:52
i followed these instructions.
https://github.com/archlinux/archinstall#using-a-live-iso-image
and when i am in the folder with git checkout fix-1278
error pathspec fix-1278 did not match any files known to git.

**Comment by svartkanin** [comment] 2022-06-04 23:04
Ahh sorry, the branch is of course in my repo since I raised the pr.

Can you try

```
git clone https://github.com/svartkanin/archinstall
cd archinstall
git checkout fix-1278
```

**Comment by JeremiahCheatham** [comment] 2022-06-05 00:12
Yeah mate that did work. I did have to manually create all the @ @home @log @pkg @.snapshots isnt there a way it could be an option like if you wipe the drive.

So some issues compression was set to zlib? before it was zstd? can i change it? there is no ntfs support. Bluetooth service is not enabled. also for some reason the entire plasma set is install except plasma-sdk seems odd given the size of that package. pacman-contrib need to be installed by default. if btrfs is chosen then compsize needs to be installed too.

Would be super cool if sudo didn't require password i know how to change it i'm just saying would be nice. Also why parallel downloads is not enabled by default.

**Comment by svartkanin** [comment] 2022-06-05 01:01
They should be auto generated when using the "disk layput -> wipe everything -> btrfs" option, have you tried that? If the subvolumes are just not shown in the preview table that's only a visual bug we're aiming to fix soon.

Yes the compression should be set to zstd, if that is not the case I'll have a look if that was a regression:)

For the rest of the mentioned issues hopefully @Torxed can give an update since they had been discussed in the past i think :)

**Comment by JeremiahCheatham** [comment] 2022-06-05 01:10
No i definitely haven't tried it since it would wipe out all my drives and windows which was the reason for this bug report in the first place. Why if i don't pick a partition it gives that same option to setup all the btrfs subs

**Comment by svartkanin** [comment] 2022-06-05 01:42
Ahh i see, then you should be able to go into "disk layout -> select what to do -> create a new partition -> suggest layout -> choose partition -> btrfs"

That will create the new btrfs layout only for the selected partition

**Comment by JeremiahCheatham** [comment] 2022-06-05 11:24
The partition already exist so I used wipe partition.

**Comment by Torxed** [comment] 2022-06-07 11:32
> I have the same problem, dualboot with windows, when selecting a specific partition I can't boot. subvolums should be generated automatically when specifying the installation partition. many bugs in this new script.

Please do define many and which they are in that case. We did a lot of dual-boot testing prior to launch so there is defenetly something that we do differently here :)

**Comment by niluzz** [comment] 2022-06-07 11:35
> are

**Comment by Torxed** [comment] 2022-06-07 12:43
@niluzz do you happen to have the user_disk_layout.json and install log? A `lsblk` output would also be useful to debug this issue :) Thanks for helping out by providig information!

**Comment by niluzz** [comment] 2022-06-07 13:27
> @niluzz do you happen to have the user_disk_layout.json and install log? A `lsblk` output would also be useful to debug this issue :) Thanks for helping out by providig information!

![image](https://user-images.githubusercontent.com/33814142/172392052-ca78148f-7f4a-424d-a48e-c6428a20a0bb.jpeg)
![image](https://user-images.githubusercontent.com/33814142/172392094-8edf8dab-7a0e-48fd-a8fc-162ffff0c368.jpeg)

**Comment by Torxed** [comment] 2022-06-07 18:07
You can "paste" them online if you wish, and if they don't contain any sensitive information.
Follow the steps here: https://archinstall.readthedocs.io/help/issues.html#log-files

Because the pictures truncate the output a bit sadly, and we're missing the last few partitions that is important in your particular case.

**Comment by Torxed** [comment] 2022-06-09 05:12
@niluzz Asesome, thank you! I think I found the issue that prohibits you from continuing at least, and that is: `"wipe": false` on the ROOT volume. That tells archinstall to not touch the volume so no root partition/layout is ever created - I think :)

When that is corrected, before installing make sure no otjer partition than the ones intended is marked with either `wipe` or `encrypt` as those are destructive actions :)

Issue is a bit different from OP I think although it shares similarities

**Comment by niluzz** [comment] 2022-06-09 12:44
@Torxed thank you very much, you await a correction. no time to do a manual install!

**Comment by svartkanin** [comment] 2022-09-04 11:06
@Torxed I think things are resolved here with the partition logic changes done recently

**Comment by Torxed** [comment] 2022-09-05 09:59
Yea this should be solved now.
Apologies for not closing all of these.

If it still happens we'll circle back but the partitioning changes should have solved most of these.

**Closed by Torxed** 2022-09-05 09:59 UTC
Labels: bug
