### ISSUE TITLE
pls add bcachefs to atomatic format options

### ISSUE THREAD

**Issue by ba-batz** [archlinux/archinstall#2376] opened 2024-02-28 21:15 UTC
"Bcachefs is an advanced new filesystem for Linux, with an emphasis on reliability and robustness and the complete set of features one would expect from a modern filesystem." - https://bcachefs.org/

**Comment by codefiles** [comment] 2024-03-02 00:51
Duplicate of #2201

**Closed** 2024-03-02 02:36 UTC
