### ISSUE TITLE
Error message but boots up just fine

### ISSUE THREAD

**Issue by gamingmsi** [archlinux/archinstall#1414] opened 2022-08-10 08:32 UTC
I've installed this month's ISO with _archinstall_ script and when it boots up it quickly presents a message: `error: file '/grub/locale/C.gmo' not found.` and boots up just fine without issues. I've installed Arch previous month but this hasn't happened.

![Untitled](https://user-images.githubusercontent.com/20128417/183854337-3450852e-dde6-46fa-98cf-2c97a4de071e.png)

Again, not a big deal since **arch linux boots up fine and works with no issues**, just wanted to share this in case anyone else has this message.

Is there a manual fix for this? I just find it annoying.

**Comment by Torxed** [comment] 2022-08-10 08:50
IIRC didn't upstream add `C` as the default locale? Could it be related to that introduction?

**Comment by agiudiceandrea** [comment] 2022-08-25 09:33
I can confirm the issue.
One workaround is to execute `cp /usr/share/locale/en_US/LC_MESSAGES/mit-krb5.mo /boot/grub/locale/C.gmo`.
Another workaround is to add `LANG=C` in `/etc/default/grub` and then execute `grub-mkconfig -o /boot/grub/grub.cfg`.

**Comment by svartkanin** [comment] 2023-09-17 10:54
I couldn't reproduce this. I will go ahead and close the issue for now as completed, if this still happens we can re-open it, a log file would be quite helpful to debug it then

**Closed by svartkanin** 2023-09-17 10:54 UTC
Labels: bug
