### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encryption password'

### ISSUE THREAD

**Issue by yatazet** [archlinux/archinstall#1715] opened 2023-04-01 23:57 UTC
When I finished configuring the Disk layout item, the Disk encryption item was empty, I saw on bloggers who used this script that the item said "None". I think that's why I can't use the script. I tried to run it on a Virtual Machine and on a laptop, but there and there was this error.

**Comment by 0xTux** [comment] 2023-04-02 01:36
The current archinstall script on Arch Live ISO is broken. The issue has been fixed in this repo though. You should clone this repo in live ISO and exec the install script.

**Comment by Torxed** [comment] 2023-04-02 07:38
Duplicate of #1704, fixed in #1705 and published in [v2.5.5](https://github.com/archlinux/archinstall/releases/tag/v2.5.5) a few minutes ago :)

**Closed by Torxed** 2023-04-02 07:38 UTC

**Comment by jalovisko** [comment] 2023-04-02 23:22
Sorry for bumping the closed issue, but I just want to add that simply updating archinstall with pacman also seems to do the trick.

**Comment by Torxed** [comment] 2023-04-04 07:07
Yepp, you can access it by doing `pacman -Sy archinstall` : )

**Comment by llllOllOOll** [comment] 2023-04-05 17:29
Thank you, guys! That's solve my problem!

**Comment by LogicalLokesh** [comment] 2023-04-09 21:47
Oh my! this is my first-time installing arch, wasted 5 hours trying to get the solution for this error. and the install-script was the culprit.

**Comment by Apoorv012** [comment] 2023-04-26 14:20
This is my first time too. Faced the issue too. updating archlinux fixed. :)

**Comment by HubKing** [comment] 2023-04-27 06:58
This was an embarrassing bug. I think, to prevent future cases like this, archinstall, at the start if Internet connection is available, should check if the current version has a critical bug like this and tell users to run pacman -Sy archinstall to update it and exit.

**Comment by ipaqmaster** [comment] 2023-04-29 03:38
Yeah not fantastic. I fired up a VM today for a test and tried `archinstall` only to hit `AttributeError: 'NoneType' object has no attribute 'encryption password'` without going near that area.  Immediately came here to see what's going on and there's already fix discussion early in the thread.

What's confusing me is how there hasn't been an emergency/new archiso build to replace the broken package from the April 1st 2023 ISO. So most people trying Archlinux for the first time this month expecting to use `archinstall` would've gotten stuck, only a percentage searching and finding this thread with the answer where many wouldn't have.

This was on `archlinux-2023.04.01-x86_64.iso` and there doesn't seem to be a newer version despite this problem being baked in for the whole month. A whole month of the latest archiso without people being able to use `archinstall` without tinkering. Maybe this serves as a good introduction for new Arch users to the experience? (I kid 😉)

There should be a pipeline and tests for the archinstall scripts so they can be tagged as working before being built into archiso. Tests would've caught this problem before the problematic commit made it to the ISO.

**Comment by Apoorv012** [comment] 2023-04-29 07:12
Little mistakes happen. I like the idea of suggesting to update the version, if internet access is available.
Apart from that, probably just making a minor update to the iso will also be great.

**Comment by MALossov** [comment] 2023-05-02 17:29
This error still appears in ISO(2023.4), thanks so much for your idea.
