### ISSUE TITLE
all grub installations fail

### ISSUE THREAD

**Issue by kronikpillow** [archlinux/archinstall#2373] opened 2024-02-24 16:51 UTC
I'v been having issues with archinstaller for 3 days when trying to install btrfs grub and default or custom - pre mounted layout ... anything i try when it comes to installing grub, fails ... even the default layout 

in the below layout im using a "OpenSUSE Btrfs pre-mounted" layout style that i'v been working on, my custom script based installer for setting up my system works, but i wanted to streamline the process down to me only creating the partition layout, pre-mounting it, and then using archinstaller to finish the job, it keeps failing ... irony is systemd-boot installed on that same layout without a problem

here is the log:
http://0x0.st/H53y.log

Overall, it looks like a problem with GRUB not properly detecting or interacting with the EFI partition during install. Making sure ESP is formatted properly, Let me know if you need any other info

**Comment by codefiles** [comment] 2024-03-10 22:33
Duplicate of #2372

**Closed** 2024-03-10 23:12 UTC
