### ISSUE TITLE
Old boot loader entry persists after formatting

### ISSUE THREAD

**Issue by marcelja** [archlinux/archinstall#322] opened 2021-04-17 15:29 UTC
I used the guided installer and selected that I want to format my entire nvme drive. After completing the installation and rebooting, the boot manager tried to boot into the partition of my previous install. I checked the boot loader entries and saw that my old configuration file was there as well.

Shouldn't the file get deleted when the drive is formatted?

**Comment by Torxed** [comment] 2021-04-19 10:09
Correct, it should. I'm assuming that you were running the official ISO? Because hopefully this should be working in `v2.1.4` (There is a release candidate out with an unofficial ISO for testing). It was the safety mechanisms of dual-boot protection that were a bit to strong and preserved the boot partition at all costs.

**Comment by marcelja** [comment] 2021-04-19 10:40
Yes, official ISO. I see. Thank you!

**Comment by dylanmtaylor** [comment] 2021-04-22 22:43
Can you please test this with the ISO on https://github.com/archlinux/archinstall/releases/tag/v2.1.4-RC2 and let me know if it is fixed for you? That will very likely become the final 2.1.4 release.

**Comment by marcelja** [comment] 2021-04-24 09:00
I tested that release and it works fine. Only one boot loader entry:
```
$ ls /boot/loader/entries/
2021-04-24_08-49-27.conf
```

**Comment by Torxed** [comment] 2021-04-26 13:06
So wiping the entire drive *should* now properly dispose of any previous boot partition information and was fixed in [v2.1.4](https://github.com/archlinux/archinstall/releases/tag/v2.1.4) *(released yesterday)*. However, if re-using a boot partition with any of the two options:
 1. Use `/mnt` as is (introduced in v2.1.4)
 2. Keep partition layout

Old boot entries will have to be cleared up manually.
I should write up a guide about this specific "by design" issue so people get some help in removing old entries.
But I'll close this as it seams to have resolved the original issue, if that's not the case I'd be happy to re-open the issue.

**Closed by Torxed** 2021-04-26 13:06 UTC
Labels: bug
