### ISSUE TITLE
BTRFS subvolumes to support tools like Snapper with rollbacks etc.

### ISSUE THREAD

**Issue by Anonymo** [archlinux/archinstall#93] opened 2021-01-22 20:43 UTC
Just a question/feature request?

Would it be possible to have an option for BTRFS that sets up subvolumes like OpenSUSE and/or any Timeshift/Snapper compatible way?

https://rootco.de/2018-01-19-opensuse-btrfs-subvolumes/

https://endeavouros.com/docs/encrypted-installation-2/btrfsonluks-verbose-version/
https://endeavouros.com/docs/encrypted-installation-2/btrfsonluks-quick-copypaste-version/

**Comment by Torxed** [comment] 2021-01-22 21:24
I see no reason why we couldn't support this.
I'm not super experienced with complex setups and all the inner workings of BTRFS, but I do like this:

>  ‘full system rollback’ ... so snapper does not accidentally destroy user data when rolling back

Priority wise, logging comes before most other things right now (which should be done by the weekend), after which formatting is getting a major overhaul (first step is to add optional "skip this step and use existing partition tables" so advanced users can set up any file system they want, like this one).
Hopefully by the end of next week or so, both logging and formatting will be done and tested for release - which should partially resolve this. I'll mention this issue in the PR's and releases until this specific feature is fully implemented.

Great suggestion and thank you! :)

**Comment by Torxed** [comment] 2021-03-20 21:20
I'm making this into a feature creep putting it in v2.1.3 instead, mainly because of the already massive changes in v2.1.2 and I would like to test the new partition-er out thoroughly before tweaking it further.

The new partitioning in v2.1.2 is done, which enables us to implement BTRFS sub volumes prior to running the installer. But due to the complexity changes of this partition-er upgrade I want the implemented changes to stabilize a bit before adding more features to it.

It's personally one of the more interesting changes for the next version tho, as I really want the "rollback" features that comes with it : )

**Comment by XEmpty** [comment] 2021-04-28 16:37
btrfs subvolu still doesn't work. i trying that new experimental features but at the end i got error like , /mnt is read as mount... but isn't a "target" and "target = None". Custom partition scheme on /mnt with BTRFS filestystem, work only without mounted subvol on /mnt (root). 😵‍💫

**Comment by mirsella** [comment] 2021-04-28 17:04
@XEmpty the issue is still marked as open, so yes it's still not working. it's in the next [milestone](https://github.com/archlinux/archinstall/milestone/5) so the devs will be working on it when they can. 
in the milestone they said they will try to finish everything before May 27.

**Comment by Torxed** [comment] 2021-04-28 18:49
> btrfs subvolu still doesn't work. i trying that new experimental features but at the end i got error like , /mnt is read as mount... but isn't a "target" and "target = None". Custom partition scheme on /mnt with BTRFS filestystem, work only without mounted subvol on /mnt (root). 😵‍💫

Humm, could you specify the error? Perhaps a trace back or `/var/log/archinstall/install.log`  *(would need to give that before rebooting, or if you manage to mount the root parttion, where it is also copied to)* which contains some debug information for us to work with. The whole subvolumes and stuff is completely new to archinstall so we don't really have any features for it as mirsella points out (thanks btw). But the whole "use /mnt as is" needs to be improved, so it would be appreciated to see how your setup looks like :)

**Comment by XEmpty** [comment] 2021-04-29 12:49
my setup it's simple subvoluming on basic partition like /root and /home.

* Format /dev/boot_part as fat32 /boot
* Format /dev/root_part as btrfs /root
- mount root in /mnt -> create @ and @home subvol (btrfs sub cre ...)
- umount and mount again with para `rw,noatime,ssd,...subvol=@ /dev/root_part /mnt
- mkdir /mnt home & boot
- mount rw,noatime...subvol=@home /dev/root_part  /mnt/home
- mount /dev/boot_part /boot

i don't have anymore that file, so i just quote that error : "Partition (path=/dev/root_part[/@], size=1, fs=btrfs, mounted=/mnt) .. was given a mountpoint but the actual mountpoint differs: None

**Comment by Torxed** [comment] 2021-04-29 12:52
I'll try to re-produce this issue with the information given :)

**Comment by Anonymo** [comment] 2021-05-06 15:54
Someone made a script to do this btrfs install with grub, in case you wanted a good example on how to setup.

https://github.com/classy-giraffe/easy-arch/blob/main/easy-arch.sh

**Comment by mirsella** [comment] 2021-05-06 17:54
there a lot of examples of how to install an arch with btrfs and supporting subvolumes, it should be pretty helpful. 
there is some follow-up guide, so with English to explain more, that could be helpful to complement the script.

I'm really looking forward for the support of subvolumes and so snapper/timeshift etc

**Comment by Torxed** [comment] 2021-05-12 08:04
Just dropping in a note that I'm working on the partitioning logic in #426, this might delay `v2.2.0` bit because of the scale of the changes that needs to be tested and stuff. But as soon as the partitioning re-work is stable and the business logic of dealing with partitions have been cleared up - I'll start working on BTRFS improvements in general. Including people using `/mnt` as is with sub volumes and how we detect/deal with them.

**Comment by Torxed** [comment] 2021-05-22 15:59
This is being worked on and is partially done in #426.
But the change is too big to be reasonably pushed for v2.2.0 in time - Which is why it will be introduced next month in v2.3.0 instead of delaying v2.2.0 which also has GRUB support and other things people are constantly requesting to see released sooner rather than later.

**Comment by Anonymo** [comment] 2021-05-22 16:02
> 
> 
> This is being worked on and is partially done in #426.
> But the change is too big to be reasonably pushed for v2.2.0 in time - Which is why it will be introduced next month in v2.3.0 instead of delaying v2.2.0 which also has GRUB support and other things people are constantly requesting to see released sooner rather than later.

Thanks for the update.  Communication has been great.  I know the whole installer has been a huge undertaking with features/bugs and the sort, so thank you.

**Comment by Torxed** [comment] 2021-09-06 18:15
#426 Became too big, this feature will come in a separate PR to not mix the overall rework of the partitioning logic to support this feature.

**Comment by Torxed** [comment] 2021-09-18 09:24
Just a small notification that I've started to work on this.
Work will be slow as I use it as a break from the other general partitioning logic. But they go hand in hand and I want to learn more about subvolumes, so I'll go slowly about this change.

**Comment by Torxed** [comment] 2021-10-30 16:01
![screenshot](https://user-images.githubusercontent.com/861439/139540513-93dab089-d6c8-4b92-9b5f-1b79aeb3c5b1.jpg)

**Closed** 2021-10-30 18:52 UTC
Labels: enhancement

**Comment by mirsella** [comment] 2021-11-01 22:50
master is supposed to work ? Personally it crash, I'll retry tomorrow and send the logs

**Comment by Torxed** [comment] 2021-11-02 08:45
> master is supposed to work ? Personally it crash, I'll retry tomorrow and send the logs

Should work yes. I did get some feedback on this feature which I'll address in a bit :)

**Comment by mirsella** [comment] 2021-11-02 15:26
it did work without luks, thanks you ! but when trying to encrypt + btrfs then it crash.
`ModuleNotFoundError: No module named 'archinstall.lib.disk.luks'`

**Comment by Torxed** [comment] 2021-11-02 15:29
> it did work without luks, thanks you ! but when trying to encrypt + btrfs then it crash. `ModuleNotFoundError: No module named 'archinstall.lib.disk.luks'`

Thank you for testing that. I don't have access to internet at the moment so haven't been able to test that. And the refactoring did come with some of these import issues :) I'll get to fixing it!
