### ISSUE TITLE
The “Enable Testing Repositories” option remains non-functional

### ISSUE THREAD

**Issue by Weather-OS** [archlinux/archinstall#2375] opened 2024-02-28 15:32 UTC
**Archinstall version**: 2.7.1-1

**How to reproduce**:
Enable the `testing` repo inside arch install.

**Observed Behavior**:
The `testing` repo remains commented out in both /mnt/archinstall/etc/pacman.conf and /etc/pacman.conf

**Expected behavior**
The `testing` repo should be enabled within the chroot’s pacman.conf file.

**Comment by codefiles** [comment] 2024-03-02 00:49
Duplicate of #2335 but this has a better title.

**Closed** 2024-03-02 02:35 UTC
