### ISSUE TITLE
partprobe /dev/sdc fails (where /dev/sdc is the installer flash drive)

### ISSUE THREAD

**Issue by timakro** [archlinux/archinstall#1075] opened 2022-04-18 18:53 UTC
Unrelated to archinstall, `partprobe /dev/sdc`, where `/dev/sdc` is the installer flash drive, fails right from the start after booting from the installer flash drive (NOT inside VM, don't know if it matters).

The issue is that version 2.4.0.RC2 of archinstall runs that command (version 2.3.3 does not) and fails. I will attach a photo of the stack trace from my phone.
![20220418_203843](https://user-images.githubusercontent.com/8438790/163860002-7376c11e-e02e-4032-b503-4aa80e83208c.jpg)

**Comment by Torxed** [comment] 2022-04-19 18:16
I'm happy at least that the error is properly raised now days.
This would normally have silently continued causing potential harm to actual installations.

But that said, we'll need to find a way around this.
We want partprobe to cause hard failures when run on anything the installer touches. But we should perhaps avoid broad partprobes and also avoid the installation medium *(is this a good idea? what if the user chose "boot to memory" and want to wipe the USB drive?)*

**Comment by timakro** [comment] 2022-04-19 18:43
> We want partprobe to cause hard failures when run on anything the installer touches.

Why? I thought the point of partprobe is to update the partition table after the installer writes new partitions to disk. This would mean we would want to run partprobe *exactly* on the things the installer touches.

> But we should perhaps avoid broad partprobes

Yes, we can't run `partprobe` without parameters as that gives the error as well. From looking at the code I don't think we are doing this right now.

So I'm thinking the only point at which we should run partprobe is after we write partitions to disk on that disk. That would avoid the error. Am I missing something?

As for the installing Arch to the USB drive scenario, I have no idea. Maybe partprobe on the USB drive just magically works when you choose "boot to memory"? I haven't tested this.

**Comment by Torxed** [comment] 2022-04-19 22:00
> Why? I thought the point of partprobe is to update the partition table after the installer writes new partitions to disk. This would mean we would want to run partprobe on _exactly_ the things the installer touches.

Apologies, perhaps my phrasing was poorly chosen. When partprobe fails, we want it to cause a hard failure until we can figure out a stable way around what the root cause it :)

> From looking at the code I don't think we are doing this right now.

We have two places that I know of:
 * https://github.com/archlinux/archinstall/blob/1515fb9fdeeb807b1301bc803d625dfebca8aaca/archinstall/lib/luks.py#L121
 * https://github.com/archlinux/archinstall/blob/fa87d85708331ad45f28906217f94937bae474fe/archinstall/lib/disk/helpers.py#L424

The later I hope/think we don't call any longer and is simply there as a helper that should get removed.
The former is only called if `cryptsetup` fails - which should happen very rarely.
And that logic has to be changed urgently anyway because `lsblk` is unreliable especially in junction with running `partprobe`.

**Comment by svartkanin** [comment] 2023-09-17 09:15
This is most likely resolved by now with the rewrites in the past

**Closed by svartkanin** 2023-09-17 09:15 UTC
