### ISSUE TITLE
Crash upon trying to install

### ISSUE THREAD

**Issue by freq-mod** [archlinux/archinstall#1722] opened 2023-04-03 20:54 UTC
Hitting install after configuring the build results in:
`Traceback (most recent call last):`
`File "/usr/bin/archinstall", line 8, in <module>`
`sys.exit(run_as_a_module())`
`File "usr/lib/python3.10/site_packages/archinstall/__init__.py", line312, in run_as_a_module`
`script.execute()`
`File "usr/lib/python3.10/site_packages/archinstall/lib/profiles.py", line 195, in execute`
`self.spec.loader.exec_module(sys.modules[self.namespace])`
`File"<frozen.importlib.bootstrap_external>", line 883, in exec_module`
`File"<frozen.importlib.bootstrap>", line 241, in call_with_frames_removed`
`File "usr/lib/python3.10/site_packages/archinstall/examples/guided.py", line 293, in <module>`
`config_output = ConfigurationOutput(archinstall.arguments)`
`File "usr/lib/python3.10/site_packages/archinstall/lib/configuration.py", line49, in __init__`
`self.process_config()`
`File "usr/lib/python3.10/site_packages/archinstall/lib/configuration.py", line 75, in _process_config`
`self.user_credentails['encryption_password']= self.config[key].encryption_password`
`AttributeError: 'NoneType' object has no attribute 'encryption_password'`

It happens all the time, preventing the installation of Arch Linux, at the very least with following configuration:

> archinstall language: english
> keyboard_layout: pl
> mirror region: Poland
> harddrive: external /dev/sda, btrfs, no encryption, 2 partitions (boot and root)
> bootloader: systemd-bootctl
> swap: true
> root password: set
> user account specified, with password and superuser 
> profile: desktop, kde
> audio: pipewire
> kernel: linux
> additional packages: firefox, thunderbird, vim, mpv
> configure network: copy from installation media
> timezone: Europe/Warsaw

Sorry if it is a duplicate.

**Comment by rediz** [comment] 2023-04-04 06:15
I get this same error aswell. pretty much same config, but using mirrors from Finland, best-effort partitions with separate /home and xfs. Profile: minimal and so on.
iso image version 2023.04.01

Totally manual installation without the script works, but i was going to test install few different setups first with the install script.
Physical hardware: Lenovo T440s -laptop.

**Comment by rediz** [comment] 2023-04-04 06:36
Not sure if said / posted somewhere, but it seems that once you have network configured you can run pacman -S archinstall, there is update available and after that the install script works.

**Comment by Torxed** [comment] 2023-04-04 07:05
Yepp, duplicate of https://github.com/archlinux/archinstall/issues/1704
Fixed in https://github.com/archlinux/archinstall/releases/tag/v2.5.5
Access it by doing `pacman -Sy archinstall`.

**Closed by Torxed** 2023-04-04 07:05 UTC
