### ISSUE TITLE
No such file or directory: '/mnt/boot/loader/loader.conf' 

### ISSUE THREAD

**Issue by stephenvsawyer** [archlinux/archinstall#634] opened 2021-09-16 19:33 UTC
This is still happening with the latest ISO. I can see it’s been a problem pretty much since archinstall was released. It happens to me every single time I try to use archinstall it fails to create the efi partition.

**Comment by stephenvsawyer** [comment] 2021-09-16 19:51
Edit: I resolved this by booting into a live environment, using Gnome Disks to delete all partitions on the disk, then the Arch install works fine. So seems like the archinstall simply needs to delete all existing partitions before starting which is what it’s supposed to do anyway. Should be a very simple fix.

**Comment by Torxed** [comment] 2021-09-17 13:34
The latest `master` branch should solve these issues. But we need to polish the new partitioning helper/guide before it gets released :)

I'll close this as it's a dupe of https://github.com/archlinux/archinstall/issues/592 and it contains more details on the subject as well as some workarounds.

**Closed by Torxed** 2021-09-17 13:34 UTC
