### ISSUE TITLE
locale language only en_US

### ISSUE THREAD

**Issue by hnsylzg** [archlinux/archinstall#2041] opened 2023-09-09 02:02 UTC
archlinux-2023.09.01-x86_64.iso

**Comment by hnsylzg** [comment] 2023-09-09 10:44
in archlinux-2023.09.01-x86_64.iso, locale language only has the en_US option, but multiple languages can be selected in archlinux-2023.08.01-x86_64.iso

**Comment by amonetlol** [comment] 2023-09-16 01:10
Here is a preview of the options that appear.

[![locale-language.png](https://i.postimg.cc/635X4Jm7/locale-language.png)](https://postimg.cc/5HGGDG11)

When you type / , no option appears

**Comment by svartkanin** [comment] 2023-09-16 04:27
Very interesting, I'll have a look

**Comment by svartkanin** [comment] 2023-09-16 23:37
@amonetlol I'm unable to reproduce this 
![image](https://github.com/archlinux/archinstall/assets/19396770/c8195741-bf7b-4aac-8e1d-51ef2c0c3566)
![image](https://github.com/archlinux/archinstall/assets/19396770/6119b827-fa6f-4fa9-911b-a9c21aff634c)
![image](https://github.com/archlinux/archinstall/assets/19396770/812804c6-24ab-4831-a540-16ad6ac6d704)


How do you run archinstall? Is it a special script?

**Comment by amonetlol** [comment] 2023-09-17 20:43
@svartkanin

I don't do anything special, just set the keyboard layout. However, if I go directly to archinstall it has the same result.

[![archinstall](https://img.youtube.com/vi/A4sGlCxOjNU/maxresdefault.jpg)](https://youtu.be/A4sGlCxOjNU)

vmware-workstation: 17.0.2-2

**Comment by svartkanin** [comment] 2023-09-18 10:26
Thanks for the video that was very helpful! 
Unfortunately I still can't reproduce this :thinking: 
I did the exact same steps as in the video on a  VM using the latest master and the current shipped version on the ISO but both seem to work fine. 

The locale languages are populated from the file `/etc/locale.gen` could you have a look at this file and see what's inside?

**Comment by amonetlol** [comment] 2023-09-18 20:09
@svartkanin 

![Locale.gen](https://github.com/archlinux/archinstall/assets/65382640/a20c837f-89be-49a3-b457-9e1dc911656c)

Found the problem. When the system is loading, some errors about cloud-init appear. This must be the reason for the generation of incomplete locale.gen

I manually inserted the pt_BR language in /etc/locale.gen and now it appears listed as an option.

![Screenshot_2023-09-18-17-06-26_3840x1080](https://github.com/archlinux/archinstall/assets/65382640/5631b7a9-cee8-445a-9464-c23c5ad30c48)

**Comment by svartkanin** [comment] 2023-09-18 20:46
Yep seems like cloud-init initialised it that way, not something archinstall can do about

**Comment by codefiles** [comment] 2023-09-19 00:19
I considered this as a possibility in my comment here https://github.com/archlinux/archinstall/pull/1423#issuecomment-1236515008.

> - Provide [localedata/SUPPORTED](https://sourceware.org/git/?p=glibc.git;a=blob;f=localedata/SUPPORTED;h=c8b63cc2fe2b4547f2fb1bff6193da68d70bd563;hb=HEAD) as /usr/share/i18n/SUPPORTED. Though the contents of the glibc localedata/SUPPORTED file is used to create /etc/locale.gen, it would be beneficial if it was also supplied separately as /usr/share/i18n/SUPPORTED since the contents of /etc/locale.gen can be overwritten as it is intended to be edited. It appears this file is being distributed in this manner with the glibc packages in other distributions such as Debian and Gentoo.

The file `/usr/share/i18n/SUPPORTED` is now provided with the glibc package. I will submit a fix for this that reads options from that file instead of `/etc/locale.gen` as well as appends entries to `/etc/locale.gen` when they are not found in the file to be uncommented but are indeed valid.

**Closed** 2023-09-19 20:51 UTC
