### ISSUE TITLE
Double compression on BTRFS subvolumes?

### ISSUE THREAD

**Issue by mcexit** [archlinux/archinstall#1592] opened 2022-12-13 08:30 UTC
Adding compression to each BTRFS subvolume managed to somehow add both `compress=zstd` and `compress=zlib:3` options to my `/etc/fstab` causing it to default to using `zlib` instead of `zstd`.

```text
UUID=5166753d-a8b3-46e8-b0a0-f9808948e86f / btrfs rw,compress=zstd,relatime,compress=zlib:3,ssd,space_cache=v2,subvolid=256,subvol=/@ 0 0
```

I also had to manually add compress options on at least one subvolume on a separate drive, despite selecting to add compression to every subvolume.

**Comment by kronikpillow** [comment] 2023-01-26 08:33
I have encountered the same issue, plus if you just use the default suggested layout it doesnt apply compression at all, even thou it is specified as zstd mount option in the installer

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment] 2023-06-26 13:33
This issue was earlier reported and explained in #1571

**Comment by codefiles** [comment] 2024-03-11 00:53
Yes, this is a duplicate of #1571

**Closed** 2024-03-11 06:33 UTC
