### ISSUE TITLE
Sway and polkit.

### ISSUE THREAD

**Issue by eskiq** [archlinux/archinstall#1443] opened 2022-08-29 18:04 UTC
I installed Arch successfully with a Sway DE, but was unable to start it bcs there wasn't polkit package with it. Maybe it would be better to add polkit when choosing Sway as a DE.

**Comment by Torxed** [comment] 2022-08-29 19:44
Duplicate of https://github.com/archlinux/archinstall/issues/1294

**Closed by Torxed** 2022-08-29 19:44 UTC
