### ISSUE TITLE
CRITICAL: Using guided manual partitioning tool causes certain partitions to be wrongfully encrypted 

### ISSUE THREAD

**Issue by nic-hartley** [archlinux/archinstall#998] opened 2022-02-21 05:34 UTC
Steps to reproduce:

1. Have a computer with an OS already on it
2. Set up two new paritions to be ready for Arch (in my particular case, an encrypted `/` and unencrypted `/boot`)
3. Run `archinstall`
4. Designate the two new partitions as mountpoints
5. Mash Ctrl+C in horror as other partitions you never said to use are caught in the wild spray and brutally murdered
6. Realize that you've only had your other system's `/boot` nuked, so you can still get the actual data, at least. Probably. You hope.

I don't know what possessed archinstall to throw LUKS at a partition I never told it to use -- especially when *I did not enable disk encryption for this install* -- but it sure fuckin did, and the only saving grace is that it printed "Formatting [my boot partition]" *before* it started gleefully trying to brick my machine instead of "Formatted [my boot partition] and [my data partition]" *after*.

I suspect, though for obvious reasons I refuse to try, that "deleting" the old partitions I want to preserve may be the correct answer. If that's the case, then (a) that's an incredibly poorly named option, and I don't even see it documented anywhere and (b) how about archinstall just *doesn't* randomly decide to wipe directories which haven't been, say, assigned a mountpoint, that seems like a blindingly obviously correct heuristic for which partitions will be used in the new system.

If you'll excuse me, I'll be trying to salvage this machine, now. And probably installing... idk, Mint or something. I've never had *that* installer randomly decide to destroy my computer before.

**Comment by Torxed** [comment] 2022-02-21 09:14
Apologies for this near-wipe-experience.

Do you mind posting the [install.log](https://archinstall.readthedocs.io/help/issues.html#log-files)?

**Comment by wllacer** [comment] 2022-02-21 12:43
@nic-hartley. You are right it is a severe problem, and we shouldn't allow letting archinstall to "shoot itself in the foot". Some of the defaults are, maybe, more dangerous than we expect, and some text less obvious we think.
In order to reproduce (it's the best way to ascertain which workflows are not clear/secure enough) i have some questions to you. The more you can remember of the exact way you tried to install, the more you can help us  to get rid of the problem
It seems you have a system a bit like this
```
disk1
├─boot partition
├─data partition1
├─data partition 2
├─free space or  reusable partitions
``` 
and you have created something like
```
disk1
├─boot partition
├─data partition1
├─data partition 2
├─arch partition for /boot
├─arch partition for /
```
Might I ask if you have created this partitions with Archinstall or with a system tool (parted, fdisk, ...?) From the wording of your report it seems it has been done BEFORE executing archinstall. 
* If this is the case, where did you mount them? Normally we expect to use for the installation what is mounted under `/mnt/archinstall` or using the argument `mount_point`, and when the program ask for a harddisk to install we skip the answer, and then use this default. Do you remember having done this ? And what else did you select
* If you did use Archinstall to define the partitions, I suppose you used the "Select what .... drive)" option and not the wipe one1, and , in the submenu didn't use the "Suggest " option, but defined all the partition needs by hand. Am I right ?
*

**Comment by nic-hartley** [comment] 2022-02-21 14:09
@Torxed Not at the moment -- I had to rush to get this computer set up and in the process I forgot to grab things that might have made diagnosing this bug easier. In my defense it was like two in the morning. Once I have my stuff backed up I can try to reproduce it and get you the logs then.

@wllacer Sure.

I started with two partitions, `old:/boot` (an unencrypted vfat boot partition) and `old:/` (an ext4-on-LUKS partition; no LVM involved). I shrank `old:/` to make room to create a `new:/boot` (an unencrypted vfat boot partition) and `new:/` (an unencrypted ext4 partition). All the partition management was done with `parted` and after setting up the partitions I did confirm my old setup still booted.

When I started the installer I indeed selected the disk that all four partitions were on, then the option to pick and choose specific partitions. I put `new:` down to be mounted at `/`, `new:/boot` to be mounted at `/boot` and encrypted, and didn't interact with anything else. I didn't have them mounted ahead of time; I was planning to use archinstall to do that because I remembered it being labeled an "experimental feature" in older versions. 

Later, after the "warning: formatting!" countdown (this might be a pain point worth addressing: which drives will it be formatting?) I saw `old:/boot` in the messages saying it was being encrypted, and sure enough, after I canceled it had become a LUKS partition.

I said I didn't ask for LUKS, and that's certainly what I *intended*, but on reflection it's also possible I mashed another key by accident while hitting enter, which would make more sense why it started putting LUKS on things.

**Comment by wllacer** [comment] 2022-02-21 17:25
@nic-hartley It is invaluable what you told us, I've seen from it, a couple of things which can be improved -or better controled.

Most probably, Archinstall allowed you to define the `new:/boot` partition as encrypted, which is a big NO-NO under UEFI. We shouldn't allow that. OTOH, you ended up defining two boot partitions on the same disk. Haven't tried this in years, but, from your report, it is a thing we should take care. I don't even know if this is still possible, but, even then we should send a warning.

The ability of using pre-mounted partitions is now pretty solid. Only remember that the default mountpoint is `/mnt/archinstall` and if you are running the latest Arch Linux CD, you can change it with the argument `mount-point=/whatever`.

If you want to run some tests, try first using the argument `--dry-run`. It won't do anything, but create some json configuration files at the `/var/archinstall/log` which describe -and you can later use- what you are going to do. In case of doubt of what they do, sending them to us will help a lot. 
The "formatting ... message should give you the drives you're about to change; and the actual action happens after it, so you still have a chance to abort (not the first time myself)
And try not to do it at 2 AM. 90% chance of something very strange happening (experienced me) ;-)

**Comment by marfeljoergsen** [comment] 2022-02-23 20:26
I can confirm, having *exactly* the same experience - and issue. I blindly trusted that a new tool such as "archinstall" would not have such a severe issue as here. The problem is that I was at work and haven't got too much time to setup my pc, while I'm working on my other pc. So I also didn't collect a log-file, am just writing to confirm my experience and tell about it:

1. I got a brand new Dell XPS 15. It came pre-installed with Windows 11, so I started upgrading BIOS and everything, disabled "secure boot", booted Ubuntu from USB, use gparted to shrink the NTFS-windows partition to make room for dual-boot linux. I created a swap-partition (33 gb), a boot-partition (1 gb) - and a root-partition (remaining free space). Next, I booted into Arch Linux.
2. I read about this new tool and wanted to save time, so I used this tool - again with encrypted root-partition (ext4) - bot /boot should be unencrypted. 
3. I didn't read everything too careful - I never thought/imagined that this tool would even *think* of touching/encrypting NTFS-partitions. But it did - it encrypted almost all my partitions (not /boot though)...

I was on work and my manager doesn't like me spending too much time on these things, he prefer I install my laptop outside normal office hours. So I don't have log-files. Luckily I always now start fresh pc's with creating a clonezilla image of the whole harddisk (all partitions). I've now restored the whole harddisk (all partitions), from the clonezilla image. So I didn't lose anything - but please fix this issue, it should *NEVER* touch e.g. NTFS-partitions. I also remember I think it didn't touch the "microsoft reserved data"-partition - but this is a critical issue and critical behaviour. If I were a new Arch Linux user and didn't have a backup I would be soooo disappointed at losing my whole Windows-installation and having to mess with getting that back. There's also some BIOS restoration/upgrade stuff on these partitions I think - so this issue should hopefully have high priority. I hope this helps a bit (by the way I also got a python exception when I originally tried to install to an LVM-partition - you can ignore this, if you wish, it'll probably be fixed another time and is not critical, as losing partitions is).

**Comment by Torxed** [comment] 2022-02-23 20:52
I get that this is bad as pointed out, but I'd also like to point out that it's isolated incidents and by that I mean we will need very specific steps to reproduce this. Archinstall used to be *to* restrictive, and not wipe anything at all. Which was a design choice at the time to avoid issues like these. We've since then let some of those restrictions loose gradually and with each step we never got reports of any wrongdoing. Now we're here, and we need to dial it back and/or figure out the bug that's causing this - as it's not a feature :)

What I gather mostly from the information so far, is that in both cases you manually (outside of archinstall) prepared partitions?
And despite the output showing promising configurations - it wiped or otherwise encrypted the wrong partitions?

Did you:
 * At all use the guided manual partitioning tool that we have
 * Did you prepare your partitions outside of archinstall - but instructed archinstall to encrypt one of them?

**Comment by marfeljoergsen** [comment] 2022-02-23 21:07
@Torxed : Yes, I didn't use the guide manual partitioning tool + yes, I prepared my partitions with "gparted", outside of archinstall, as I usually do. Sorry, I don't want to hijack this, I updated my reply earlier in case there's a relation/connection to our problems. I think I should refrain from writing more here, unless I can be more concrete and accurate, which I unfortunately cannot at the moment. @nic-hartley : Sorry if your issue isn't the same as mine with automatic encryption of my NTFS-partitions, I'm unsure if you actually mean "wiped" or "just" encrypted which happened to my Windows/NTFS-partitions...

**Comment by Torxed** [comment] 2022-02-23 21:14
No worries, any information is helpful :) I'll run a battery of tests during the weekend :)

**Comment by marfeljoergsen** [comment] 2022-02-23 21:24
Okay, got some more to add then: I just ran through the installer again: Again used gparted to setup my partitions (as I always do)... This time I *DID* choose to encrypt only my root-partition (I was unsure earlier, if I might've forgotten this step). I also assigned a 1 gb partition to /boot - and that's it (because I learned earlier it complained about my swap-partition, I can always add that after rebooting the new system). Once the partition-stuff was approved and looked allright, I saw: `Press Enter to continue` and `! Formatting [BlockDevice(/dev/nvme0n1, size=1907.7GB, free_space=.......bus_type=nvme)] in 5...4...3...2 ^C.1^C` - as you see, this time I pressed CTRL+C several times... This message just sounds completely *WRONG* in my ears - it should *NOT* format the whole nvme0n1 - this should be easy to fix/look into, hopefully (I'm unsure if it wanted to do what it said - or if the message was/is just wrong)! I'm actually a bit too scary to try this again, will wait some months and just do the manual arch linux installation now, sorry - but I hope this helps a bit, thanks for the good work though, I would really love if this installer was reliable but my feeling is that it isn't...

**Comment by Torxed** [comment] 2022-02-23 22:51
Ok so there is an entry in the configuration to manage the harddrive. Archinstall is acting on that. But there is no disk layout, so i'm wonderin what archinstall would do.

**Comment by Torxed** [comment] 2022-02-24 12:31
Just to clarify, using the above attached configuration (or a very similar one, just harddrive name changed) the installer will not format any drives unless `--disk_layouts` is given (in master). It will say that it's formatting, but it won't actually format because there's no disk layout configuration to act upon. The warning message comes from `--conf` containing a harddrive.

At which point, the installer will fail because there's nothing mounted under `/mnt/archinstall`.
But manually mounting things to `/mnt/archinstall` AND having an entry in `--conf` will again - not perform any disk operations even if the warning message claims it will - and then proceed with the installation against `/mnt/archinstall`.

By just running it against a new drive without any layout, but in conf:
![screenshot](https://user-images.githubusercontent.com/861439/155523565-1ae0d7fb-a065-4552-9012-31186552fe6d.jpg)

By manually setting it up and using a `--conf` without `--disk_layouts`:
![screenshot](https://user-images.githubusercontent.com/861439/155524404-7e739731-8875-49a7-9c14-d8254c112a8c.jpg)


![screenshot](https://user-images.githubusercontent.com/861439/155524447-54d88556-8624-48a3-b6e8-16b1b82a64ed.jpg)

No formatting was done (but a warning message because the drive was mentioned in `--conf`, but again, we only act on disk operations defined in `--disk_layouts`):
![screenshot](https://user-images.githubusercontent.com/861439/155524540-1da0398a-24b1-45cf-a2da-d31c1e03743d.jpg)

**Comment by Torxed** [comment] 2022-02-24 12:38
I'll have to run some more tests to conclude that the "CRITICAL" part of this is valid or not.
But at the very least, removing the "Formatting X in 5... 4..." would be good.. Since it should only be shown IF we're formatting.

**Comment by wllacer** [comment] 2022-02-24 12:49
@torxed
Both reports (from @nic-hartley  and @marfeljoergsen ) share a couple of commonalities. 
* __Both intended to use encryption__ and in both cases Archinstall extended this beyond what was planed.
* __Both install over previously partitioned systems__. It seems that they don't premount them in `/mnt/archinstall` (or whatever), and proceed to manually manage them afterwards
* __both define a separate boot partition__[¹], 

I'd bet the most important issue here is the first. Why it happens is probably it is related to the other two. The first thing we must try is to ensure there is no strange codepath. 
 There is also a fat chance that it comes from user input.  In `v2.3.1` the manual disk management menus (`manage_new_and_existing_partitions`)  are not the most visually clean, so an data input error is hard to pick before it is too late. This has improved notably in `master`. OTOH we do little of sanity checks there. It has a good side -you are not constrained in what you can do, specially if using Archinstall as a library- and two bad ones -run time errors during the actual install phase or GAU's like this issue. We could introduce some basic sanity checks, but rather as warnings [²]

The second and third problems are minor (more exposure to our ability to use premounted setups, and deny the chance to encrypt an EFI partition).
Perhaps we should have a standard path for dual installations (like we have now for default "full disk" installations)

I've run in more problems than expected creating a test environment (sady, can't test with Windows), so i've been unable to help more with this issue.

[¹] See the [wiki ](https://wiki.archlinux.org/title/Dual_boot_with_Windows), and why it is a "bad idea"®. Quote:
>
>Mind that an additional EFI system partition should not be created, as it may [prevent Windows from booting](https://support.microsoft.com/en-us/help/2879602/unable-to-boot-if-more-than-one-efi-system-partition-is-present). Simply [mount the existing partition](https://wiki.archlinux.org/title/EFI_system_partition#Mount_the_partition).
...
>The boot loader needs to support chainloading other EFI applications to do dual boot Windows / Linux.

This is a thing we should be checking during Archinstall processing. (Same as not allowing EFI partitions to be encrypted. How is what is not that easy.
[²] I am working on a successor to the actual menus (to support Btrfs and some other UI niceties) , and with the new partition management you wrote it's easier now. I've been quiet on this front for a while (real life and some UI showstoppers, i just solved) but I hope to produce something "real soon now"

**Comment by Torxed** [comment] 2022-02-24 13:00
@wllacer: Yea that's my main issue.
There's really no steps to reproduce this.. It's just information of what went wrong.
So I'm running tests "blindly" and trying to mimic their configurations.

The last tests I can run, is to mark partitions using the manual tool we supply :)

**Comment by nic-hartley** [comment] 2022-02-24 13:01
> @wllacer The "formatting ... message should give you the drives you're about to change; and the actual action happens after it, so you still have a chance to abort (not the first time myself) 

It shows the *drive*, yes. Which is useless when I'm expecting it to muck with that drive. It should show the partitions it's modifying. Sorry for misspeaking. 

> @marfeljoergsen Sorry if your issue isn't the same as mine with automatic encryption of my NTFS-partitions, I'm unsure if you actually mean "wiped" or "just" encrypted which happened to my Windows/NTFS-partitions...

Mine was "just" encrypted, but with a password I don't know. It's probably guessable, because barring some *truly* mysterious behavior, it'll be one of the keys next to my enter button.

> @Torxed I'll have to run some more tests to conclude that the "CRITICAL" part of this is valid or not.

You have two reports from users who were startled to find boot drives overwritten unexpectedly. You have a critical issue in your software, and while it may be "merely" a UX or documentation problem, *that's still a critical issue*.

I'd like to note that I didn't panic because of a scary message. I panicked because *my boot drive was encrypted* and my data drive looked like it would be next, all despite me not interacting with either in the installer and naively assuming that would mean they'd be left alone.

I still think the best option is to simply not touch any partitions which haven't been assigned a mount point, and if the user requests something that would conflict with that, print a warning and ask them what to do.

**Comment by Torxed** [comment] 2022-02-24 13:06
> You have two reports from users who were startled to find boot drives overwritten unexpectedly. You have a critical issue in your software, and while it may be "merely" a UX or documentation problem, _that's still a critical issue_.

Sure, but I have to exclude that it's not user error in the sense that the tool is doing what it's supposed to and we need to update documentation. The users (and me included) are always in charge, and we have the countdown and other measures in place for this reason. We also supply `--dry-run` to see what the tool would do. And so on.

Critical for me would be if the tool does something when told not to. Which it currently **does not do** if archinstall is used in 90% of the disk-options we provide. I'm debugging the rest of the 10% to make sure the last few code paths doesn't do what you say by means of a bug.

I get that it sucks, and yes it's not good.
But there's different levels of hell and if this is a bug caused by intended use - then I'd be ready to drop a patch tonight in a urgent `v2.3.2`.



> I still think the best option is to simply not touch any partitions which haven't been assigned a mount point, and if the user requests something that would conflict with that, print a warning and ask them what to do.

That's the intended functionality you're describing :)



> my boot drive was encrypted

And this is what I'm trying to reproduce, but find it hard to.
If you have `/var/log/archinstall/user_disk_layout.json` that would be helpful at this stage. As that's probably the last piece of the puzzle to find out what is different from my now 80+ tests - and your scenario of doom.

**Comment by Torxed** [comment] 2022-02-24 14:22
Ok so I think I've found or at least been able to reproduce the issue.
And as suspected it's tied to the manual partitioning (tested with multi-disk setup):
![archinstall](https://user-images.githubusercontent.com/861439/155540081-160494fe-eaa7-4b11-87c1-fcf956e5b4bb.gif)

If two disks are selected, where `/boot` is to be re-used *(not formatted)* it will format that partitioning anyway possibly, and for some reason also `/dev/sda2` despite never really being told to. And then it formats `/dev/sdb1` instead of `/dev/sdb2`.

Or at least this is the initial observation.
Above in the video is the recording of the steps. And below is a picture of the "result" in progress.

Here are:
 * `--conf`: https://0x0.st/oKpN.json
 * `--creds`: https://0x0.st/oK94.json
 * `--disk_layouts`: https://0x0.st/oKpb.json

![screenshot](https://user-images.githubusercontent.com/861439/155540976-19f291d0-3069-4627-b8ae-d01d6b2909ba.jpg)

And here are the resulting partitions use:
![screenshot](https://user-images.githubusercontent.com/861439/155541032-9da70161-b69f-4333-85ea-cac9a4905006.jpg)

Expected layout:
 * `/dev/sda1` on `/boot`
 * `/dev/sdb2` on `/` (encrypted)

And it appears that archinstall used those partitions when mounting etc, but that formatting or at least warning messages about formatting was issued.

**Comment by Torxed** [comment] 2022-02-24 14:23
Waht puzzles me is that `/dev/sdb1` and `/dev/sdb2` got encrypted.

**Comment by Torxed** [comment] 2022-02-26 14:31
Working on a fix, if i get it done by tomorrow ill drop v2.3.2 as a patch release, and this is the only change it will contain :)

currently running tests and adding debugging/log outputs.

**Comment by Torxed** [comment] 2022-02-28 13:31
This has been fixed in v2.3.2 and release is out. Waiting for TU to package it and ship it, hopefully on tomorrow's ISO. Although this release was a bit too tight onto the release schedule of the ISO, so might not make it - but users can always do `pacman -Su archinstall` once it drops in the repos :)

Thanks for reporting this and bringing it to our attention!

**Closed by Torxed** 2022-02-28 13:31 UTC
Labels: bug

**Comment by gabrc52** [comment] 2022-05-20 04:52
I just downloaded the latest arch iso and it still has this issue (it encrypted my EFI system partition and all partitions). Is there any way we can get to update the ISO with the latest archinstall/packages in general?

**Comment by dylanmtaylor** [comment] 2022-05-20 04:54
> I just downloaded the latest arch iso and it still has this issue (it encrypted my EFI system partition and all partitions). Is there any way we can get to update the ISO with the latest archinstall/packages in general?

pacman -Sy archinstall

**Comment by gabrc52** [comment] 2022-05-20 05:34
Got it. So it's two weeks from now. I think this bug is critical enough that it might need a bigger warning or a new update to the arch iso. This is probably not the right place to ask, though. 

It seems that my partitions were also wiped before encryption: after decrypting the partitions, they seem to be blank with no files on them. Thankfully I had no valuable data on them.

**Comment by Torxed** [comment] 2022-05-20 06:38
I agree that this was bad, but we do not really have a way of reaching out to the users. Maybe archinstall can curl a static `WARNING.rd` file from `master` and if it exists it can render the content on execution?

The best we can do now is to inform users to use:
https://github.com/archlinux/archinstall#using-a-live-iso-image

As the issue is fixed, and I'm about to release it, I am just waiting for one more small tweak to that specific fix

**Comment by marfeljoergsen** [comment] 2022-05-21 10:59
Suggestion: When the script is started, write out a warning message in capital letters: "PLEASE BACKUP YOUR PARTITIONS USING E.G. CLONEZILLEA BEFORE RUNNING THIS TOOL". At least Clonezilla saved my ass... But I would say that if we're the only persons affected by (or who has even noticed)  this bug, that is far better than I expected.

**Comment by Torxed** [comment] 2022-05-21 11:35
We can't really be placing warnings for every common sense thing people should be doing. It's not our responsability to educate though messages in the TUI.

That feels more like a reaction to our bug. And I think a better approach would be to some how have a registry via git that allows for archinstall to push warnings for critical bugs with the tool.

**Comment by timblaktu** [comment] 2023-04-21 20:22
I just hit this as well, same basic use case as the others, trying to use archinstall to install arch on a disk already containing uefi boot, win11/ntfs partitions. In my case i also had pre-created btrfs partitions in the remaining free space, used the manual partitioning tool where the only thing i specified was the btrfs subvolume layout. No encryption was specified at any time during my archinstall runs.

Im not yet sure what happened to the disk, but i did get the scary FORMATTING entire disk message, which is what brought me here. 

I got several  `Could not find <UUID> in disk after 5 tried` errors, followed by this crash:

![20230421_131856.jpg](https://user-images.githubusercontent.com/12355715/233727798-5c2a7260-1a35-41fe-8960-1e63c3350cfc.jpg)

**Comment by Torxed** [comment] 2023-04-21 20:27
> ![20230421_131856.jpg](https://user-images.githubusercontent.com/12355715/233727798-5c2a7260-1a35-41fe-8960-1e63c3350cfc.jpg)

Hi, I know it might sound strange but you're using an old version.
Do `pacman -Sy archinstall` and that should be fixed :)

**Comment by timblaktu** [comment] 2023-04-21 21:06
Actually I'm using 2.5.5, specifically re- installed in the archiso live env using `pacman -Sy archinstall` to workaround the first bug i hit in the april iso (that one about not handling empty values in sime map).

This thing ive hit now (re:UUIDs) appears to be an open issue recently reported.
