### ISSUE TITLE
Recurrent problems Archinstall 

### ISSUE THREAD

**Issue by tippunmon** [archlinux/archinstall#1610] opened 2022-12-30 14:00 UTC
Despite several attempts archinstall will not load, keep getting failure message as per enclosed
![20221229_112034](https://user-images.githubusercontent.com/121677925/210078142-4e16cdc2-f6be-46dc-a483-b41423660a87.jpg)

**Comment by ghartausz** [comment] 2022-12-30 14:56
I have had the same issue multiple times.
Strangely enough sometimes it goes without this issue.

**Comment by DzenowaRAVE** [comment] 2022-12-31 23:20
I ended up having this issue every time I tried to install. I have no found any work around yet, not sure why this happens.

**Comment by tippunmon** [comment] 2023-01-01 12:37
Yes, didn't used to happen, have successfully used the archinstall script in the past. Doesn't always happen.  3 attempts the other day, 3rd one was successful the other two failed. Hmmmmm.



Sent from my Galaxy



-------- Original message --------
From: DżenowaRAVE ***@***.***>
Date: 31/12/2022 23:20 (GMT+00:00)
To: archlinux/archinstall ***@***.***>
Cc: tippunmon ***@***.***>, Author ***@***.***>
Subject: Re: [archlinux/archinstall] Recurrent problems Archinstall (Issue #1610)


I ended up having this issue every time I tried to install. I have no found any work around yet, not sure why this happens.

**Comment by TuxMC-sys** [comment] 2023-01-05 04:38
I had the same issue; the workaround I found was unplugging the ISO flash drive once booted up; it's all in ram.

**Comment by tippunmon** [comment] 2023-01-05 07:27
Great point, thanks for that.



Sent from my Galaxy



-------- Original message --------
From: Linux Rustling ***@***.***>
Date: 05/01/2023 04:38 (GMT+00:00)
To: archlinux/archinstall ***@***.***>
Cc: tippunmon ***@***.***>, Author ***@***.***>
Subject: Re: [archlinux/archinstall] Recurrent problems Archinstall (Issue #1610)


I had the same issue; the workaround I found was unplugging the ISO flash drive once booted up; it's all in ram.

**Comment by fabricionaweb** [comment] 2023-01-06 11:07
> 

ok, this worked to me, thanks!

**Comment by tippunmon** [comment] 2023-01-06 12:17
Yes this works just brilliantly. Great tip,thanks

**Comment by tippunmon** [comment] 2023-01-11 18:05
Yes, worked great for me too once I removed the usb stick



Sent from my Galaxy



-------- Original message --------
From: DżenowaRAVE ***@***.***>
Date: 11/01/2023 18:02 (GMT+00:00)
To: archlinux/archinstall ***@***.***>
Cc: tippunmon ***@***.***>, Author ***@***.***>
Subject: Re: [archlinux/archinstall] Recurrent problems Archinstall (Issue #1610)


I had the same issue; the workaround I found was unplugging the ISO flash drive once booted up; it's all in ram.

Can confirm this worked out great for me, I think it has something to do with the USB medium conflicting with the script after all is loaded to RAM.

**Comment by chang-zhao** [comment] 2023-01-25 23:29
It's a duplicate of #1557

**Comment by KenEkanem** [comment] 2023-03-24 01:05
@chang-zhao thanks for the link, can we get someone to close this issue

**Comment by tippunmon** [comment] 2023-03-24 05:58
Fair comment,  apologies.

**Closed** 2023-03-24 05:58 UTC
