### ISSUE TITLE
Disk is not changing

### ISSUE THREAD

**Issue by DHCPCD9** [archlinux/archinstall#1402] opened 2022-08-01 11:32 UTC
Hello everyone, I found a bug which is doesn't changing disk if you already choose one.

How to reproduce:
- Select disk
- Select another one
- And on install/pratition managing you will see first disk instead of second.

**Comment by svartkanin** [comment] 2022-09-04 11:18
@DHCPCD9 sorry but I can't reproduce this, could you try to run this on the latest master and see if it still happens?

**Comment by svartkanin** [comment] 2023-09-17 09:51
This should be fixed

**Closed by svartkanin** 2023-09-17 09:51 UTC
