### ISSUE TITLE
[Feature request] add a swap partition to the default partition scheme

### ISSUE THREAD

**Issue by 1ace** [archlinux/archinstall#323] opened 2021-04-18 18:59 UTC
A couple of weeks ago I had to setup my new work laptop and decided to use the installer script to speed things up, but I only realized a few days later that it hadn't created a swap partition, preventing the hibernation feature from being able to work.

I think the default setup should have a swap partition, and maybe if you think some of the users for this script will not want a swap partition you can add an option to remove it (I can't think of a use case where disk space would be more precious than the features enabled by having a swap partition, but I'm assuming they can exist).

**Comment by Torxed** [comment] 2021-04-19 10:12
Duplicate of #175. We're working on safely bringing in Swap for all use cases, and swap on ZRAM or something similar. The current roadmap aims at having this implemented not this version but the next one (v2.2.0). If you have any additional input feel free to chime in on #175 :)

**Closed by Torxed** 2021-04-19 10:12 UTC
