### ISSUE TITLE
Not even sure anymore

### ISSUE THREAD

**Issue by Jamesedward11** [archlinux/archinstall#1503] opened 2022-10-04 16:11 UTC
[install.log](https://github.com/archlinux/archinstall/files/9708727/install.log)
I changed settings to avoid the problem i had last time. Whats the issue now?

**Comment by Jamesedward11** [comment] 2022-10-04 16:30
i downloaded a package called "arch-install-tools" and im gonna try again

**Comment by Torxed** [comment] 2022-10-05 10:48
Duplicate of #1495

**Closed by Torxed** 2022-10-05 10:48 UTC
