### ISSUE TITLE
No sof-firmware package after installing

### ISSUE THREAD

**Issue by speckitor** [archlinux/archinstall#2969] opened 2024-11-30 14:36 UTC
I have an MSI Katana gf76 laptop, I tested installing arch via archinstall with pipewire and pulseaudio and there was no sof-firmware package auto installed, so I had no sound. Is it ok?

**Comment by Torxed** [comment] 2024-11-30 18:48
That is currently the expected behavior.
We don't have anyway to map hardware <--> packages at the moment, so any custom firmware needed will have to be installed post-installation.

Apologize for the inconvenience, I'll close this ticket since I can't see a way to solve this as there's no feasible way to detect required hardware packages.

**Closed by Torxed** 2024-11-30 18:48 UTC

**Comment by speckitor** [comment] 2024-12-05 14:30
What do you think about adding question like "Do you want to install sof-firmware?" after selecting pipewire or pulseaudio.

**Comment by Torxed** [comment] 2024-12-05 16:37
Personally I don't have a preference other than feeling iffy about adding more menu options that only satisfies some people, because it adds maintaining of code/packages we need to keep track of. There's potentially other packages that would be required to add as well, like libffado for instance. 

How popular/required is `sof-firmware`?
Perhaps this could be a reason to?

**Comment by codefiles** [comment] 2024-12-06 22:34
This was addressed in 128db1cd.

The code has been rearranged since then but it looks to still be active to me.

https://github.com/archlinux/archinstall/blob/fbdb3c4f37cab50d22f893349e1cdc1fad2000fd/archinstall/lib/models/audio_configuration.py#L45-L46

@speckitor
Provide a log?
