### ISSUE TITLE
archinstall failed /dev/sda1 log attached

### ISSUE THREAD

**Issue by frozen905** [archlinux/archinstall#2019] opened 2023-08-20 17:13 UTC
Hi there, thanks for help 

https://[0x0.st/HLEM.txt](https://0x0.st/HLEM.txt)

ArchInstall failed and I used the guide to upload the log file.

Log output tells me to create a post here!!!

**Comment by fabianmuehlberger** [comment] 2023-08-20 20:47
Have you checket the other issues for duplicate first? There are already about 5 issues created with the same problem.

please add your issue to:  #1971 

Additionally: It seems you are using a VM? I  think that others also have a problem related to VMs or not using UEFI

**Comment by fabianmuehlberger** [comment] 2023-08-27 05:48
Duplicate of #1971

**Closed** 2023-09-14 10:05 UTC
