### ISSUE TITLE
Grub selected as bootmanager - no grub after flawless installation

### ISSUE THREAD

**Issue by arcolinuxz** [archlinux/archinstall#1653] opened 2023-02-26 07:09 UTC
archinstall 2.5.2-1
archlinux-2023.02.01-x86_64.iso
https://in-mirror.garudalinux.org/archlinux/iso/2023.02.01/

Here I choose to have grub

https://youtu.be/rnAMEnK-QL0?t=44

that resulted in this 

https://youtu.be/rnAMEnK-QL0?t=192

then I tested out the systemd-boot choice here

https://youtu.be/rnAMEnK-QL0?t=424

and got an installation just fine

https://youtu.be/rnAMEnK-QL0?t=560

Maybe you are aware of the issue or it was mentioned on another issue - I did go through the list of open issues

Ps. I had some issues to get it started - probably the internet not being there on virtualbox for some seconds
https://youtu.be/rnAMEnK-QL0?t=274

**Comment by Neo-29** [comment] 2023-02-26 11:38
I can confirm the issue using virtmanager too.
Grub is installed, although not automatically detected when booting.
Using misc device in uefi settings on virtmanager works and give access to grub.

**Comment by Torxed** [comment] 2023-02-28 20:37
Is it possible that GRUB can't write the EFI vars correctly?

> probably the internet not being there on virtualbox for some seconds

It looks like it's just the keyring missing keys as per usual.
We've added a fix to wait for the keyring update service before executing #1647

**Comment by cgglyle** [comment] 2023-07-04 13:07
I also encountered this situation.
```
verison:

archinstall 2.5.6

archlinux-2023.07.01-x86_64.iso

VirtualBox Graphical User Interface Version 7.0.8 r156879
```


In particular, I tried multiple scenarios( all enable encryption ):

In `uefi` state, using grub boot causes this.

In the `uefi` state, using systemd-boot works perfectly fine.



In the `boot` state, using grub works.

I did not try to use systemd-boot in the `boot` state.

**Comment by svartkanin** [comment] 2023-09-17 11:31
There were a lot of changes recently and this should be resolved in the most recent release

**Closed by svartkanin** 2023-09-17 11:31 UTC
