### ISSUE TITLE
`systemd-boot` only shows an option to boot into firmware configuration menu.

### ISSUE THREAD

**Issue by atirut-w** [archlinux/archinstall#720] opened 2021-11-16 09:13 UTC
The only notable thing I did when installing was using Zen kernel. Not sure if this also happens with normal Linux kernel.

**Comment by Torxed** [comment] 2021-11-16 15:43
I'm having trouble reproducing this.
I tried with a fresh install using only Zen kernel on a EFI system using systemd-boot as the loader and it produces this:

![screenshot](https://user-images.githubusercontent.com/861439/142015297-3672d616-17e7-403f-b9d5-c7aa8b32b097.jpg)

![screenshot](https://user-images.githubusercontent.com/861439/142017153-4faf3f3e-309d-4a65-b752-2ec39aed5049.jpg)

![screenshot](https://user-images.githubusercontent.com/861439/142017266-e258c2a5-6568-47f0-beec-a7349f991602.jpg)

**Comment by Torxed** [comment] 2021-11-16 16:20
Doubtful, but if you can attach the `/var/log/archinstall/install.log` *(either from the ISO or the installed system, a copy exists on both places)* I could probably track down the issue.

**Comment by atirut-w** [comment] 2021-11-16 16:39
It happened on my main machine and I already got it set up, sorry. Maybe my HW setup could help?

**Comment by Torxed** [comment] 2021-11-16 19:35
> It happened on my main machine and I already got it set up, sorry. Maybe my HW setup could help?

Hardware *should* be irrelevant here, so that won't help much. If you don't have `/var/log/archinstall/install.log` I will go ahead and close this issue as I cannot reproduce it without that file. I have however updated the boot loader entries with more detailed information thanks to this issue.

**Closed by Torxed** 2021-11-16 19:35 UTC

**Comment by atirut-w** [comment] 2021-11-16 19:37
Sorry, don't have the log file. Ig this is getting closed.

**Comment by wbrawner** [comment] 2021-11-22 18:43
I ran into this today actually, though with the `linux-lts` kernel selected. The issue in my case was that the `/boot/loader/entries/` conf file had `linux /vmlinuz-linux` and `initrd /initramfs-linux.img` instead of `linux /vmlinuz-linux-lts` and `initrd /initramfs-linux-lts.img`. Fixing those lines solved the problem for me. I can share the logs from that installation if necessary.

**Comment by Torxed** [comment] 2021-11-22 19:37
> I ran into this today actually, though with the `linux-lts` kernel selected. The issue in my case was that the `/boot/loader/entries/` conf file had `linux /vmlinuz-linux` and `initrd /initramfs-linux.img` instead of `linux /vmlinuz-linux-lts` and `initrd /initramfs-linux-lts.img`. Fixing those lines solved the problem for me. I can share the logs from that installation if necessary.

This should be solved in `master` since, did you use the official Arch Linux ISO or the latest code from github?

**Comment by wbrawner** [comment] 2021-11-22 20:16
I cloned the repo from github

**Comment by Torxed** [comment] 2021-11-22 20:20
Then I'd love the `/var/log/archinstall/install.log` specifically : )

**Comment by wbrawner** [comment] 2021-11-22 20:34
The contents of the log file are below. To clarify, I cloned the repo with git, then `cd`'d into it and ran `python archinstall`.

```
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '662.7M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '1.8T', 'children': [{'name': 'sda1', 'fstype': 'ntfs', 'fsver': None, 'label': None, 'uuid': 'E478A60C78A5DE14', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '1.8T'}]}, {'name': 'sdb', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '119.2G', 'children': [{'name': 'sdb1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': None, 'uuid': '1C91-8446', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '488.3M'}, {'name': 'sdb2', 'fstype': 'ext4', 'fsver': '1.0', 'label': None, 'uuid': '911458f0-ad34-4024-b339-bf7c2401f334', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '976M'}, {'name': 'sdb3', 'fstype': 'crypto_LUKS', 'fsver': '2', 'label': None, 'uuid': '4dde8da8-5b37-4392-85e7-d0ab9055fa61', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '117.8G'}]}, {'name': 'sdc', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '28.6G', 'children': [{'name': 'sdc1', 'fstype': 'exfat', 'fsver': '1.0', 'label': 'Ventoy', 'uuid': 'CC92-6D91', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '28.6G', 'children': [{'name': 'ventoy', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202109', 'uuid': '2021-09-01-11-25-35-00', 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/bootmnt'], 'type': 'dm', 'size': '832.3M'}]}, {'name': 'sdc2', 'fstype': 'vfat', 'fsver': 'FAT16', 'label': 'VTOYEFI', 'uuid': '133B-CFB9', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '32M'}]}, {'name': 'nvme0n1', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '931.5G'}]}
Unknown blockdevice type for /dev/mapper/ventoy: dm
You can skip selecting a drive and partitioning and use whatever drive-setup is mounted at /mnt (experimental)
 * Passwords did not match * 
Verifying that additional packages exist (this might take a few seconds)
Hardware time and other post-configuration steps might be required in order for NTP to work. For more information, please check the Arch wiki.
-- Guided template chosen (with below config) --
{
    "!encryption-password": "******",
    "!root-password": "******",
    "audio": "pipewire",
    "bootloader": "systemd-bootctl",
    "filesystem": "btrfs",
    "harddrive": {
        "model": "Samsung SSD 970 EVO Plus 1TB",
        "path": "/dev/nvme0n1",
        "size": "931.5G"
    },
    "hostname": "fractal",
    "kernels": [
        "linux-lts"
    ],
    "keyboard-language": "us",
    "mirror-region": {
        "United States": {
            "https://america.mirror.pkgbuild.com/$repo/os/$arch": true,
            "https://arch.hu.fo/archlinux/$repo/os/$arch": true,
            "https://arch.mirror.constant.com/$repo/os/$arch": true,
            "https://archmirror1.octyl.net/$repo/os/$arch": true,
            "https://arlm.tyzoid.com/$repo/os/$arch": true,
            "https://dfw.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
            "https://ftp.sudhip.com/archlinux/$repo/os/$arch": true,
            "https://iad.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
            "https://iad.mirrors.misaka.one/archlinux/$repo/os/$arch": true,
            "https://mirror.arizona.edu/archlinux/$repo/os/$arch": true,
            "https://mirror.clarkson.edu/archlinux/$repo/os/$arch": true,
            "https://mirror.dal10.us.leaseweb.net/archlinux/$repo/os/$arch": true,
            "https://mirror.ette.biz/archlinux/$repo/os/$arch": true,
            "https://mirror.hackingand.coffee/arch/$repo/os/$arch": true,
            "https://mirror.kaminski.io/archlinux/$repo/os/$arch": true,
            "https://mirror.lty.me/archlinux/$repo/os/$arch": true,
            "https://mirror.mia11.us.leaseweb.net/archlinux/$repo/os/$arch": true,
            "https://mirror.phx1.us.spryservers.net/archlinux/$repo/os/$arch": true,
            "https://mirror.pit.teraswitch.com/archlinux/$repo/os/$arch": true,
            "https://mirror.sfo12.us.leaseweb.net/archlinux/$repo/os/$arch": true,
            "https://mirror.theash.xyz/arch/$repo/os/$arch": true,
            "https://mirror.umd.edu/archlinux/$repo/os/$arch": true,
            "https://mirror.wdc1.us.leaseweb.net/archlinux/$repo/os/$arch": true,
            "https://mirrors.kernel.org/archlinux/$repo/os/$arch": true,
            "https://mirrors.lug.mtu.edu/archlinux/$repo/os/$arch": true,
            "https://mirrors.mit.edu/archlinux/$repo/os/$arch": true,
            "https://mirrors.ocf.berkeley.edu/archlinux/$repo/os/$arch": true,
            "https://mirrors.radwebhosting.com/archlinux/$repo/os/$arch": true,
            "https://mirrors.rit.edu/archlinux/$repo/os/$arch": true,
            "https://mirrors.rutgers.edu/archlinux/$repo/os/$arch": true,
            "https://mirrors.sonic.net/archlinux/$repo/os/$arch": true,
            "https://mirrors.xtom.com/archlinux/$repo/os/$arch": true,
            "https://ord.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
            "https://plug-mirror.rcac.purdue.edu/archlinux/$repo/os/$arch": true,
            "https://repo.ialab.dsu.edu/archlinux/$repo/os/$arch": true,
            "https://tick-tack.mynetgear.com/archlinux/$repo/os/$arch": true,
            "https://zxcvfdsa.com/arch/$repo/os/$arch": true
        }
    },
    "nic": {
        "NetworkManager": true,
        "nic": "Use NetworkManager to control and manage your internet connection"
    },
    "ntp": true,
    "packages": [
        "vim",
        "htop",
        "tmux",
        "git",
        "curl",
        "chromium"
    ],
    "profile": {
        "path": "/usr/lib/python3.9/site-packages/archinstall/profiles/desktop.py"
    },
    "script": "guided",
    "superusers": {
        "wbrawner": {
            "!password": "******"
        }
    },
    "sys-encoding": "utf-8",
    "sys-language": "en_US",
    "timezone": "US/Mountain",
    "users": {}
}
Wiping BlockDevice(/dev/nvme0n1) by using partition format 1
Using and formatting the entire BlockDevice(/dev/nvme0n1).
Adding partition to BlockDevice(/dev/nvme0n1)
Adding partition to BlockDevice(/dev/nvme0n1)
Set the root partition Partition(path=/dev/nvme0n1p2, size=931G, real_device=/dev/nvme0n1, fs=btrfs) to use filesystem btrfs.
Partition Partition(path=/dev/nvme0n1p1, size=512M, fs=vfat, rel_mountpoint=/boot) is a boot partition and has content inside.
Did not format Partition(path=/dev/nvme0n1p1, size=512M, fs=vfat, rel_mountpoint=/boot) because .safe_to_format() returned False or .allow_formatting was False.
Encrypting Partition(path=/dev/nvme0n1p2, size=931G, real_device=/dev/nvme0n1, fs=btrfs, rel_mountpoint=/) (This might take a while)
Formatting /dev/mapper/luksloop -> btrfs
Mounting Partition(path=/dev/mapper/luksloop, size=-1, real_device=/dev/nvme0n1p2, fs=btrfs) to /mnt
Mounting Partition(path=/dev/nvme0n1p1, size=512M, fs=vfat, rel_mountpoint=/boot) to /mnt/boot
Waiting for automatic mirror selection (reflector) to complete.
A new package mirror-list has been created: /etc/pacman.d/mirrorlist
Installing packages: ['base', 'base-devel', 'linux-firmware', 'linux-lts', 'btrfs-progs', 'amd-ucode']
Adding bootloader systemd-bootctl to Partition(path=/dev/nvme0n1p1, size=-1, fs=vfat, mounted=/mnt/boot)
Installing packages: ('efibootmgr',)
Identifying root partition by PART-UUID on Partition(path=/dev/nvme0n1p2, size=-1, real_device=/dev/nvme0n1, fs=crypto_LUKS): '419dcf11-f9f3-4037-b338-ce8e347e4b3c'.
Installing packages: ('networkmanager',)
Enabling service NetworkManager.service
This audio server will be used: pipewire
Installing packages: ['pipewire', 'pipewire-alsa', 'pipewire-jack', 'pipewire-media-session', 'pipewire-pulse', 'gst-plugin-pipewire', 'libpulse']
Installing packages: ['vim', 'htop', 'tmux', 'git', 'curl', 'chromium']
Installing network profile Profile(desktop)
Installing packages: ['nano', 'vim', 'openssh', 'htop', 'wget', 'iwd', 'wireless_tools', 'wpa_supplicant', 'smartmontools', 'xdg-utils']
Installing network profile Profile(kde)
Installing network profile Profile(xorg)
Installing packages: ('dkms',)
Installing packages: ('xorg-server xorg-xinit nvidia-dkms',)
Installing packages: ['plasma-meta', 'konsole', 'kate', 'dolphin', 'sddm', 'plasma-wayland-session', 'egl-wayland']
Enabling service sddm
Creating user wbrawner
Setting password for wbrawner
Enabling sudo permissions for wbrawner.
Installing and activating NTP.
Installing packages: ('ntp',)
Enabling service ntpd
Keyboard language for this installation is now set to: us
For post-installation tips, see https://wiki.archlinux.org/index.php/Installation_guide#Post-installation
Updating /mnt/etc/fstab
Installation completed without any errors. You may now reboot.
Disk states after installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '662.7M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '1.8T', 'children': [{'name': 'sda1', 'fstype': 'ntfs', 'fsver': None, 'label': None, 'uuid': 'E478A60C78A5DE14', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '1.8T'}]}, {'name': 'sdb', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '119.2G', 'children': [{'name': 'sdb1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': None, 'uuid': '1C91-8446', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '488.3M'}, {'name': 'sdb2', 'fstype': 'ext4', 'fsver': '1.0', 'label': None, 'uuid': '911458f0-ad34-4024-b339-bf7c2401f334', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '976M'}, {'name': 'sdb3', 'fstype': 'crypto_LUKS', 'fsver': '2', 'label': None, 'uuid': '4dde8da8-5b37-4392-85e7-d0ab9055fa61', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '117.8G'}]}, {'name': 'sdc', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '28.6G', 'children': [{'name': 'sdc1', 'fstype': 'exfat', 'fsver': '1.0', 'label': 'Ventoy', 'uuid': 'CC92-6D91', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '28.6G', 'children': [{'name': 'ventoy', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202109', 'uuid': '2021-09-01-11-25-35-00', 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/bootmnt'], 'type': 'dm', 'size': '832.3M'}]}, {'name': 'sdc2', 'fstype': 'vfat', 'fsver': 'FAT16', 'label': 'VTOYEFI', 'uuid': '133B-CFB9', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '32M'}]}, {'name': 'nvme0n1', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '931.5G', 'children': [{'name': 'nvme0n1p1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': None, 'uuid': '5748-3203', 'fsavail': '445.4M', 'fsuse%': '13%', 'mountpoints': ['/mnt/boot'], 'type': 'part', 'size': '512M'}, {'name': 'nvme0n1p2', 'fstype': 'crypto_LUKS', 'fsver': '2', 'label': None, 'uuid': '2e29680a-5212-4281-ae76-550cf1653585', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '931G', 'children': [{'name': 'luksloop', 'fstype': 'btrfs', 'fsver': None, 'label': None, 'uuid': 'dd880bf4-961f-40d4-878f-ce5bcd2e288c', 'fsavail': '924.1G', 'fsuse%': '1%', 'mountpoints': ['/mnt'], 'type': 'crypt', 'size': '931G'}]}]}]}
```

**Comment by Torxed** [comment] 2021-11-22 21:02
> The contents of the log file are below. To clarify, I cloned the repo with git, then `cd`'d into it and ran `python archinstall`.
> 
> ```
> Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '662.7M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '1.8T', 'children': [{'name': 'sda1', 'fstype': 'ntfs', 'fsver': None, 'label': None, 'uuid': 'E478A60C78A5DE14', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '1.8T'}]}, {'name': 'sdb', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '119.2G', 'children': [{'name': 'sdb1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': None, 'uuid': '1C91-8446', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '488.3M'}, {'name': 'sdb2', 'fstype': 'ext4', 'fsver': '1.0', 'label': None, 'uuid': '911458f0-ad34-4024-b339-bf7c2401f334', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '976M'}, {'name': 'sdb3', 'fstype': 'crypto_LUKS', 'fsver': '2', 'label': None, 'uuid': '4dde8da8-5b37-4392-85e7-d0ab9055fa61', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '117.8G'}]}, {'name': 'sdc', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '28.6G', 'children': [{'name': 'sdc1', 'fstype': 'exfat', 'fsver': '1.0', 'label': 'Ventoy', 'uuid': 'CC92-6D91', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '28.6G', 'children': [{'name': 'ventoy', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202109', 'uuid': '2021-09-01-11-25-35-00', 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/bootmnt'], 'type': 'dm', 'size': '832.3M'}]}, {'name': 'sdc2', 'fstype': 'vfat', 'fsver': 'FAT16', 'label': 'VTOYEFI', 'uuid': '133B-CFB9', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '32M'}]}, {'name': 'nvme0n1', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '931.5G'}]}
> Unknown blockdevice type for /dev/mapper/ventoy: dm
> You can skip selecting a drive and partitioning and use whatever drive-setup is mounted at /mnt (experimental)
>  * Passwords did not match * 
> Verifying that additional packages exist (this might take a few seconds)
> Hardware time and other post-configuration steps might be required in order for NTP to work. For more information, please check the Arch wiki.
> -- Guided template chosen (with below config) --
> {
>     "!encryption-password": "******",
>     "!root-password": "******",
>     "audio": "pipewire",
>     "bootloader": "systemd-bootctl",
>     "filesystem": "btrfs",
>     "harddrive": {
>         "model": "Samsung SSD 970 EVO Plus 1TB",
>         "path": "/dev/nvme0n1",
>         "size": "931.5G"
>     },
>     "hostname": "fractal",
>     "kernels": [
>         "linux-lts"
>     ],
>     "keyboard-language": "us",
>     "mirror-region": {
>         "United States": {
>             "https://america.mirror.pkgbuild.com/$repo/os/$arch": true,
>             "https://arch.hu.fo/archlinux/$repo/os/$arch": true,
>             "https://arch.mirror.constant.com/$repo/os/$arch": true,
>             "https://archmirror1.octyl.net/$repo/os/$arch": true,
>             "https://arlm.tyzoid.com/$repo/os/$arch": true,
>             "https://dfw.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
>             "https://ftp.sudhip.com/archlinux/$repo/os/$arch": true,
>             "https://iad.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
>             "https://iad.mirrors.misaka.one/archlinux/$repo/os/$arch": true,
>             "https://mirror.arizona.edu/archlinux/$repo/os/$arch": true,
>             "https://mirror.clarkson.edu/archlinux/$repo/os/$arch": true,
>             "https://mirror.dal10.us.leaseweb.net/archlinux/$repo/os/$arch": true,
>             "https://mirror.ette.biz/archlinux/$repo/os/$arch": true,
>             "https://mirror.hackingand.coffee/arch/$repo/os/$arch": true,
>             "https://mirror.kaminski.io/archlinux/$repo/os/$arch": true,
>             "https://mirror.lty.me/archlinux/$repo/os/$arch": true,
>             "https://mirror.mia11.us.leaseweb.net/archlinux/$repo/os/$arch": true,
>             "https://mirror.phx1.us.spryservers.net/archlinux/$repo/os/$arch": true,
>             "https://mirror.pit.teraswitch.com/archlinux/$repo/os/$arch": true,
>             "https://mirror.sfo12.us.leaseweb.net/archlinux/$repo/os/$arch": true,
>             "https://mirror.theash.xyz/arch/$repo/os/$arch": true,
>             "https://mirror.umd.edu/archlinux/$repo/os/$arch": true,
>             "https://mirror.wdc1.us.leaseweb.net/archlinux/$repo/os/$arch": true,
>             "https://mirrors.kernel.org/archlinux/$repo/os/$arch": true,
>             "https://mirrors.lug.mtu.edu/archlinux/$repo/os/$arch": true,
>             "https://mirrors.mit.edu/archlinux/$repo/os/$arch": true,
>             "https://mirrors.ocf.berkeley.edu/archlinux/$repo/os/$arch": true,
>             "https://mirrors.radwebhosting.com/archlinux/$repo/os/$arch": true,
>             "https://mirrors.rit.edu/archlinux/$repo/os/$arch": true,
>             "https://mirrors.rutgers.edu/archlinux/$repo/os/$arch": true,
>             "https://mirrors.sonic.net/archlinux/$repo/os/$arch": true,
>             "https://mirrors.xtom.com/archlinux/$repo/os/$arch": true,
>             "https://ord.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
>             "https://plug-mirror.rcac.purdue.edu/archlinux/$repo/os/$arch": true,
>             "https://repo.ialab.dsu.edu/archlinux/$repo/os/$arch": true,
>             "https://tick-tack.mynetgear.com/archlinux/$repo/os/$arch": true,
>             "https://zxcvfdsa.com/arch/$repo/os/$arch": true
>         }
>     },
>     "nic": {
>         "NetworkManager": true,
>         "nic": "Use NetworkManager to control and manage your internet connection"
>     },
>     "ntp": true,
>     "packages": [
>         "vim",
>         "htop",
>         "tmux",
>         "git",
>         "curl",
>         "chromium"
>     ],
>     "profile": {
>         "path": "/usr/lib/python3.9/site-packages/archinstall/profiles/desktop.py"
>     },
>     "script": "guided",
>     "superusers": {
>         "wbrawner": {
>             "!password": "******"
>         }
>     },
>     "sys-encoding": "utf-8",
>     "sys-language": "en_US",
>     "timezone": "US/Mountain",
>     "users": {}
> }
> Wiping BlockDevice(/dev/nvme0n1) by using partition format 1
> Using and formatting the entire BlockDevice(/dev/nvme0n1).
> Adding partition to BlockDevice(/dev/nvme0n1)
> Adding partition to BlockDevice(/dev/nvme0n1)
> Set the root partition Partition(path=/dev/nvme0n1p2, size=931G, real_device=/dev/nvme0n1, fs=btrfs) to use filesystem btrfs.
> Partition Partition(path=/dev/nvme0n1p1, size=512M, fs=vfat, rel_mountpoint=/boot) is a boot partition and has content inside.
> Did not format Partition(path=/dev/nvme0n1p1, size=512M, fs=vfat, rel_mountpoint=/boot) because .safe_to_format() returned False or .allow_formatting was False.
> Encrypting Partition(path=/dev/nvme0n1p2, size=931G, real_device=/dev/nvme0n1, fs=btrfs, rel_mountpoint=/) (This might take a while)
> Formatting /dev/mapper/luksloop -> btrfs
> Mounting Partition(path=/dev/mapper/luksloop, size=-1, real_device=/dev/nvme0n1p2, fs=btrfs) to /mnt
> Mounting Partition(path=/dev/nvme0n1p1, size=512M, fs=vfat, rel_mountpoint=/boot) to /mnt/boot
> Waiting for automatic mirror selection (reflector) to complete.
> A new package mirror-list has been created: /etc/pacman.d/mirrorlist
> Installing packages: ['base', 'base-devel', 'linux-firmware', 'linux-lts', 'btrfs-progs', 'amd-ucode']
> Adding bootloader systemd-bootctl to Partition(path=/dev/nvme0n1p1, size=-1, fs=vfat, mounted=/mnt/boot)
> Installing packages: ('efibootmgr',)
> Identifying root partition by PART-UUID on Partition(path=/dev/nvme0n1p2, size=-1, real_device=/dev/nvme0n1, fs=crypto_LUKS): '419dcf11-f9f3-4037-b338-ce8e347e4b3c'.
> Installing packages: ('networkmanager',)
> Enabling service NetworkManager.service
> This audio server will be used: pipewire
> Installing packages: ['pipewire', 'pipewire-alsa', 'pipewire-jack', 'pipewire-media-session', 'pipewire-pulse', 'gst-plugin-pipewire', 'libpulse']
> Installing packages: ['vim', 'htop', 'tmux', 'git', 'curl', 'chromium']
> Installing network profile Profile(desktop)
> Installing packages: ['nano', 'vim', 'openssh', 'htop', 'wget', 'iwd', 'wireless_tools', 'wpa_supplicant', 'smartmontools', 'xdg-utils']
> Installing network profile Profile(kde)
> Installing network profile Profile(xorg)
> Installing packages: ('dkms',)
> Installing packages: ('xorg-server xorg-xinit nvidia-dkms',)
> Installing packages: ['plasma-meta', 'konsole', 'kate', 'dolphin', 'sddm', 'plasma-wayland-session', 'egl-wayland']
> Enabling service sddm
> Creating user wbrawner
> Setting password for wbrawner
> Enabling sudo permissions for wbrawner.
> Installing and activating NTP.
> Installing packages: ('ntp',)
> Enabling service ntpd
> Keyboard language for this installation is now set to: us
> For post-installation tips, see https://wiki.archlinux.org/index.php/Installation_guide#Post-installation
> Updating /mnt/etc/fstab
> Installation completed without any errors. You may now reboot.
> Disk states after installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '662.7M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '1.8T', 'children': [{'name': 'sda1', 'fstype': 'ntfs', 'fsver': None, 'label': None, 'uuid': 'E478A60C78A5DE14', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '1.8T'}]}, {'name': 'sdb', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '119.2G', 'children': [{'name': 'sdb1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': None, 'uuid': '1C91-8446', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '488.3M'}, {'name': 'sdb2', 'fstype': 'ext4', 'fsver': '1.0', 'label': None, 'uuid': '911458f0-ad34-4024-b339-bf7c2401f334', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '976M'}, {'name': 'sdb3', 'fstype': 'crypto_LUKS', 'fsver': '2', 'label': None, 'uuid': '4dde8da8-5b37-4392-85e7-d0ab9055fa61', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '117.8G'}]}, {'name': 'sdc', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '28.6G', 'children': [{'name': 'sdc1', 'fstype': 'exfat', 'fsver': '1.0', 'label': 'Ventoy', 'uuid': 'CC92-6D91', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '28.6G', 'children': [{'name': 'ventoy', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202109', 'uuid': '2021-09-01-11-25-35-00', 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/bootmnt'], 'type': 'dm', 'size': '832.3M'}]}, {'name': 'sdc2', 'fstype': 'vfat', 'fsver': 'FAT16', 'label': 'VTOYEFI', 'uuid': '133B-CFB9', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '32M'}]}, {'name': 'nvme0n1', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '931.5G', 'children': [{'name': 'nvme0n1p1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': None, 'uuid': '5748-3203', 'fsavail': '445.4M', 'fsuse%': '13%', 'mountpoints': ['/mnt/boot'], 'type': 'part', 'size': '512M'}, {'name': 'nvme0n1p2', 'fstype': 'crypto_LUKS', 'fsver': '2', 'label': None, 'uuid': '2e29680a-5212-4281-ae76-550cf1653585', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '931G', 'children': [{'name': 'luksloop', 'fstype': 'btrfs', 'fsver': None, 'label': None, 'uuid': 'dd880bf4-961f-40d4-878f-ce5bcd2e288c', 'fsavail': '924.1G', 'fsuse%': '1%', 'mountpoints': ['/mnt'], 'type': 'crypt', 'size': '931G'}]}]}]}
> ```

Ah, that still uses the official version.
You have to cd into the git repository and do:
```
cp examples/guided.py ./
python guided.py
```

**Comment by wbrawner** [comment] 2021-11-22 21:23
Ah, that makes sense. Thanks for the help!
