### ISSUE TITLE
guided install fails with error for key-checks

### ISSUE THREAD

**Issue by triplem** [archlinux/archinstall#911] opened 2022-01-26 08:02 UTC
When installing the gnome package with the latest ArchIso (2022.01.01) the installation fails with an error in the key-check for the package libspeechd.
Obviously the workaround is to install a minimal system without gnome and do a pacman -S archlinux-keyring. 

Could this be implemented in the guided installer itself?

**Comment by Torxed** [comment] 2022-01-26 08:50
Duplicate of https://github.com/archlinux/archinstall/issues/907.
Discussion about implement `pacman -S archlinux-keyring` is ongoing there.

I would just like to verify any side effects of running `pacman -S archlinux-keyring` blindly before committing to it.

**Closed by Torxed** 2022-01-26 08:50 UTC
