### ISSUE TITLE
Could not decode JSON

### ISSUE THREAD

**Issue by ardx812** [archlinux/archinstall#1573] opened 2022-11-21 19:05 UTC
![rn_image_picker_lib_temp_a254e94a-4127-4020-826b-0d83fff9d4b8](https://user-images.githubusercontent.com/107469659/203138414-1cf95c68-6640-4b21-a4ba-113e505d2d1b.jpg)
Hi, I'm getting this weird issue on my PC.

**Comment by codefiles** [comment] 2022-11-22 00:11
Duplicate of #1557

**Comment by svartkanin** [comment] 2023-09-17 11:10
This is resolved with all the rewrites

**Closed by svartkanin** 2023-09-17 11:10 UTC
