### ISSUE TITLE
Failed Install [Log]

### ISSUE THREAD

**Issue by Rustmilian** [archlinux/archinstall#2321] opened 2024-01-02 19:38 UTC
https://0x0.st/H6mz.log

**Comment by Rustmilian** [comment] 2024-01-02 20:05
I was able to get around this by by manually removing /dev/sda3 with parted

**Comment by codefiles** [comment] 2024-01-03 00:21
Thank you for submitting a log.

From the log:

```
Formatting filesystem: /usr/bin/mkfs.btrfs -f /dev/sda2
Unable to determine new uuid: /dev/sda2
LsblkInfo(name='sda2', path=PosixPath('/dev/sda2'), pkname='sda', size=Size(value=21474836480, unit=<Unit.B: 1>, sector_size=SectorSize(value=512, unit=<Unit.B: 1>)), log_sec=512, pttype='gpt', ptuuid='dd7a4dce-5c68-4cb7-b30b-ff28f0f1882f', rota=False, tran=None, partn=2, partuuid='e1f59779-7bcb-41bd-b0ad-3c4e5c459d51', parttype='0fc63daf-8483-4772-8e79-3d69d8477de4', uuid=None, fstype=None, fsver=None, fsavail=None, fsuse_percentage=None, type='part', mountpoint=None, mountpoints=[], fsroots=[], children=[])
```

Duplicate of #2305

**Closed** 2024-01-03 10:23 UTC
