### ISSUE TITLE
unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by darman96** [archlinux/archinstall#2892] opened 2024-11-19 23:27 UTC
### Which ISO version are you using?

2024-11-01

### The installation log

```json
https://0x0.st/XnQe.log
```

#### Description of the issue

I tried installing arch via archinstall and got following error:
unsupported operand type(s) for +: 'NoneType' and 'str'

Specs:
Ryzen 5900X
AMD RX 6800XT
32GB RAM
480GB SSD

**Comment by darman96** [comment] 2024-11-19 23:30
I selected the Hyprland Desktop profile at first and then tried the minimal profile with the same result.

**Comment by codefiles** [comment] 2024-11-20 03:35
Probably caused by https://github.com/archlinux/archinstall/issues/2851#issuecomment-2481340098

There is still a bug after the fix for that linked issue though. If hostname is purposely clearned by the user, with backspace for example, then `ask_hostname()` will return None. This will cause the error seen in the log given here. This is fixed by the linked pull request.

**Closed** 2024-11-20 05:32 UTC
