### ISSUE TITLE
[256]: b'mount: /mnt/archinstall/dev: udev already mounted on /mnt/archinstall/dev

### ISSUE THREAD

**Issue by colossalchicken** [archlinux/archinstall#1506] opened 2022-10-06 03:33 UTC
How do I fix this?
```
['/usr/bin/arch-chroot', '/mnt/archinstall', 'systemctl', 'enable', 'fstrim.timer'] exited with abnormal exit code [256]: b'mount: /mnt/archinstall/dev: udev already mounted on /mnt/archinstall/dev.\r\n       dmesg(1) may have more information after failed mount system call.\r\n==> ERROR: failed to setup chroot /mnt/archinstall\r\n'
```

```
Hardware model detected: ASUSTeK COMPUTER INC. VivoBook_ASUSLaptop E210MAB_E210MA; UEFI mode: True
Processor model detected: Intel(R) Celeron(R) N4020 CPU @ 1.10GHz
Memory statistics: 3026688 available out of 3837184 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
Virtualization detected: None; is VM: None
Graphics devices detected: dict_keys(['Intel Corporation GeminiLake [UHD Graphics 600] (rev 06)'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '866.3M'}, {'name': 'sda', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_GUI_XFCE_202207', 'uuid': '2022-07-19-10-53-45-00', 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/bootmnt'], 'type': 'disk', 'size': '1.8T', 'children': [{'name': 'sda2', 'fstype': 'vfat', 'fsver': 'FAT16', 'label': 'ARCHISO_EFI', 'uuid': 'DB27-ED1B', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '80M'}]}, {'name': 'mmcblk0', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '58.2G'}, {'name': 'mmcblk0boot0', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '4M'}, {'name': 'mmcblk0boot1', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '4M'}]}
Testing connectivity to the Arch Linux mirrors ...
Updating archlinux-keyring ...
Setting font: LatGrkCyr-8x16
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot0
Could not get free space on /dev/mmcblk0boot0: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot0', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot0: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot0:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot1
Could not get free space on /dev/mmcblk0boot1: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot1', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot1: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot1:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Hardware model detected: ASUSTeK COMPUTER INC. VivoBook_ASUSLaptop E210MAB_E210MA; UEFI mode: True
Processor model detected: Intel(R) Celeron(R) N4020 CPU @ 1.10GHz
Memory statistics: 2569436 available out of 3837184 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
Virtualization detected: None; is VM: None
Graphics devices detected: dict_keys(['Intel Corporation GeminiLake [UHD Graphics 600] (rev 06)'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '866.3M'}, {'name': 'sda', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_GUI_XFCE_202207', 'uuid': '2022-07-19-10-53-45-00', 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/bootmnt'], 'type': 'disk', 'size': '1.8T', 'children': [{'name': 'sda2', 'fstype': 'vfat', 'fsver': 'FAT16', 'label': 'ARCHISO_EFI', 'uuid': 'DB27-ED1B', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '80M'}]}, {'name': 'mmcblk0', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '58.2G'}, {'name': 'mmcblk0boot0', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '4M'}, {'name': 'mmcblk0boot1', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '4M'}]}
Testing connectivity to the Arch Linux mirrors ...
Setting font: LatGrkCyr-8x16
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot0
Could not get free space on /dev/mmcblk0boot0: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot0', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot0: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot0:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot1
Could not get free space on /dev/mmcblk0boot1: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot1', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot1: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot1:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Password strength: blahblahblah
 -- Chosen configuration --
{
    "HSM": null,
    "__separator__": null,
    "additional-repositories": [],
    "archinstall-language": "English",
    "audio": null,
    "bootloader": "systemd-bootctl",
    "config_version": "2.5.1",
    "debug": false,
    "gfx_driver": "Intel (open-source)",
    "harddrives": [
        "/dev/mmcblk0"
    ],
    "hostname": "arch",
    "kernels": [
        "linux"
    ],
    "keyboard-layout": "us",
    "mirror-region": {
        "United States": {
            "http://arch.hu.fo/archlinux/$repo/os/$arch": true,
            "http://arch.mirror.constant.com/$repo/os/$arch": true,
            "http://archmirror1.octyl.net/$repo/os/$arch": true,
            "http://arlm.tyzoid.com/$repo/os/$arch": true,
            "http://codingflyboy.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "http://coresite.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "http://dfw.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
            "http://distro.ibiblio.org/archlinux/$repo/os/$arch": true,
            "http://forksystems.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "http://ftp.osuosl.org/pub/archlinux/$repo/os/$arch": true,
            "http://ftp.sudhip.com/archlinux/$repo/os/$arch": true,
            "http://iad.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
            "http://iad.mirrors.misaka.one/archlinux/$repo/os/$arch": true,
            "http://il.us.mirror.archlinux-br.org/$repo/os/$arch": true,
            "http://mirror.arizona.edu/archlinux/$repo/os/$arch": true,
            "http://mirror.clarkson.edu/archlinux/$repo/os/$arch": true,
            "http://mirror.cs.pitt.edu/archlinux/$repo/os/$arch": true,
            "http://mirror.cs.vt.edu/pub/ArchLinux/$repo/os/$arch": true,
            "http://mirror.dal10.us.leaseweb.net/archlinux/$repo/os/$arch": true,
            "http://mirror.ette.biz/archlinux/$repo/os/$arch": true,
            "http://mirror.fcix.net/archlinux/$repo/os/$arch": true,
            "http://mirror.fossable.org/archlinux/$repo/os/$arch": true,
            "http://mirror.hackingand.coffee/arch/$repo/os/$arch": true,
            "http://mirror.lty.me/archlinux/$repo/os/$arch": true,
            "http://mirror.math.princeton.edu/pub/archlinux/$repo/os/$arch": true,
            "http://mirror.metrocast.net/archlinux/$repo/os/$arch": true,
            "http://mirror.mia11.us.leaseweb.net/archlinux/$repo/os/$arch": true,
            "http://mirror.phx1.us.spryservers.net/archlinux/$repo/os/$arch": true,
            "http://mirror.pit.teraswitch.com/archlinux/$repo/os/$arch": true,
            "http://mirror.sfo12.us.leaseweb.net/archlinux/$repo/os/$arch": true,
            "http://mirror.siena.edu/archlinux/$repo/os/$arch": true,
            "http://mirror.stephen304.com/archlinux/$repo/os/$arch": true,
            "http://mirror.umd.edu/archlinux/$repo/os/$arch": true,
            "http://mirror.vtti.vt.edu/archlinux/$repo/os/$arch": true,
            "http://mirror.wdc1.us.leaseweb.net/archlinux/$repo/os/$arch": true,
            "http://mirrors.acm.wpi.edu/archlinux/$repo/os/$arch": true,
            "http://mirrors.advancedhosters.com/archlinux/$repo/os/$arch": true,
            "http://mirrors.aggregate.org/archlinux/$repo/os/$arch": true,
            "http://mirrors.bloomu.edu/archlinux/$repo/os/$arch": true,
            "http://mirrors.cat.pdx.edu/archlinux/$repo/os/$arch": true,
            "http://mirrors.gigenet.com/archlinux/$repo/os/$arch": true,
            "http://mirrors.kernel.org/archlinux/$repo/os/$arch": true,
            "http://mirrors.lug.mtu.edu/archlinux/$repo/os/$arch": true,
            "http://mirrors.mit.edu/archlinux/$repo/os/$arch": true,
            "http://mirrors.ocf.berkeley.edu/archlinux/$repo/os/$arch": true,
            "http://mirrors.radwebhosting.com/archlinux/$repo/os/$arch": true,
            "http://mirrors.rit.edu/archlinux/$repo/os/$arch": true,
            "http://mirrors.rutgers.edu/archlinux/$repo/os/$arch": true,
            "http://mirrors.sonic.net/archlinux/$repo/os/$arch": true,
            "http://mirrors.vectair.net/archlinux/$repo/os/$arch": true,
            "http://mirrors.xmission.com/archlinux/$repo/os/$arch": true,
            "http://mirrors.xtom.com/archlinux/$repo/os/$arch": true,
            "http://mnvoip.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "http://ord.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
            "http://plug-mirror.rcac.purdue.edu/archlinux/$repo/os/$arch": true,
            "http://repo.ialab.dsu.edu/archlinux/$repo/os/$arch": true,
            "http://repo.miserver.it.umich.edu/archlinux/$repo/os/$arch": true,
            "http://ridgewireless.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "http://wcbmedia.io:8000/$repo/os/$arch": true,
            "http://www.gtlib.gatech.edu/pub/archlinux/$repo/os/$arch": true,
            "https://america.mirror.pkgbuild.com/$repo/os/$arch": true,
            "https://arch.hu.fo/archlinux/$repo/os/$arch": true,
            "https://arch.mirror.constant.com/$repo/os/$arch": true,
            "https://arch.mirror.ivo.st/$repo/os/$arch": true,
            "https://archmirror1.octyl.net/$repo/os/$arch": true,
            "https://arlm.tyzoid.com/$repo/os/$arch": true,
            "https://codingflyboy.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "https://coresite.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "https://dfw.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
            "https://forksystems.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "https://ftp.osuosl.org/pub/archlinux/$repo/os/$arch": true,
            "https://ftp.sudhip.com/archlinux/$repo/os/$arch": true,
            "https://iad.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
            "https://iad.mirrors.misaka.one/archlinux/$repo/os/$arch": true,
            "https://mirror.arizona.edu/archlinux/$repo/os/$arch": true,
            "https://mirror.clarkson.edu/archlinux/$repo/os/$arch": true,
            "https://mirror.ette.biz/archlinux/$repo/os/$arch": true,
            "https://mirror.fcix.net/archlinux/$repo/os/$arch": true,
            "https://mirror.hackingand.coffee/arch/$repo/os/$arch": true,
            "https://mirror.lty.me/archlinux/$repo/os/$arch": true,
            "https://mirror.mia11.us.leaseweb.net/archlinux/$repo/os/$arch": true,
            "https://mirror.phx1.us.spryservers.net/archlinux/$repo/os/$arch": true,
            "https://mirror.pit.teraswitch.com/archlinux/$repo/os/$arch": true,
            "https://mirror.sfo12.us.leaseweb.net/archlinux/$repo/os/$arch": true,
            "https://mirror.stephen304.com/archlinux/$repo/os/$arch": true,
            "https://mirror.the-repo.org/ArchMirror/$repo/os/$arch": true,
            "https://mirror.theash.xyz/arch/$repo/os/$arch": true,
            "https://mirror.tmmworkshop.com/archlinux/$repo/os/$arch": true,
            "https://mirror.umd.edu/archlinux/$repo/os/$arch": true,
            "https://mirror.wdc1.us.leaseweb.net/archlinux/$repo/os/$arch": true,
            "https://mirror.zackmyers.io/archlinux/$repo/os/$arch": true,
            "https://mirror2.sandyriver.net/pub/archlinux/$repo/os/$arch": true,
            "https://mirrors.bloomu.edu/archlinux/$repo/os/$arch": true,
            "https://mirrors.kernel.org/archlinux/$repo/os/$arch": true,
            "https://mirrors.lug.mtu.edu/archlinux/$repo/os/$arch": true,
            "https://mirrors.mit.edu/archlinux/$repo/os/$arch": true,
            "https://mirrors.ocf.berkeley.edu/archlinux/$repo/os/$arch": true,
            "https://mirrors.radwebhosting.com/archlinux/$repo/os/$arch": true,
            "https://mirrors.rit.edu/archlinux/$repo/os/$arch": true,
            "https://mirrors.sonic.net/archlinux/$repo/os/$arch": true,
            "https://mirrors.vectair.net/archlinux/$repo/os/$arch": true,
            "https://mirrors.xtom.com/archlinux/$repo/os/$arch": true,
            "https://mnvoip.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "https://ord.mirror.rackspace.com/archlinux/$repo/os/$arch": true,
            "https://plug-mirror.rcac.purdue.edu/archlinux/$repo/os/$arch": true,
            "https://repo.ialab.dsu.edu/archlinux/$repo/os/$arch": true,
            "https://ridgewireless.mm.fcix.net/archlinux/$repo/os/$arch": true,
            "https://zxcvfdsa.com/arch/$repo/os/$arch": true
        }
    },
    "nic": {},
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [],
    "parallel downloads": 0,
    "profile": {
        "path": "/usr/lib/python3.10/site-packages/archinstall/profiles/xorg.py"
    },
    "save_config": null,
    "script": "guided",
    "silent": false,
    "swap": true,
    "sys-encoding": "UTF-8",
    "sys-language": "en_US",
    "timezone": "UTC",
    "version": "2.5.1"
}
{
    "/dev/mmcblk0": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "mountpoint": "/boot",
                "size": "512MiB",
                "start": "1MiB",
                "type": "primary",
                "wipe": true
            },
            {
                "encrypted": false,
                "filesystem": {
                    "format": "ext4",
                    "mount_options": []
                },
                "mountpoint": "/",
                "size": "20GiB",
                "start": "513MiB",
                "type": "primary",
                "wipe": true
            },
            {
                "encrypted": false,
                "filesystem": {
                    "format": "ext4",
                    "mount_options": []
                },
                "mountpoint": "/home",
                "size": "100%",
                "start": "20GiB",
                "type": "primary",
                "wipe": true
            }
        ],
        "wipe": true
    }
}
Creating a new partition label on /dev/mmcblk0
Adding partition to BlockDevice(/dev/mmcblk0, size=58.2GB, free_space=62.5GB, bus_type=None), 1MiB->512MiB
Adding partition using the following parted command: /dev/mmcblk0 mkpart primary fat32 1MiB 512MiB
Could not get UUID for partition. Waiting 0s before retrying.
Could not get UUID for partition. Waiting 1s before retrying.
Formatting /dev/mmcblk0p1 -> vfat
/usr/bin/mkfs.vfat -F32 /dev/mmcblk0p1
Marking partition Partition(path=/dev/mmcblk0p1, size=0.5, PARTUUID=6bc9f849-ce93-4309-b46d-58703c6bfa70, fs=vfat) as bootable.
Setting boot on on (parted) partition index 1
Adding partition to BlockDevice(/dev/mmcblk0, size=58.2GB, free_space=62.5GB, bus_type=None), 513MiB->20GiB
Adding partition using the following parted command: /dev/mmcblk0 mkpart primary ext4 513MiB 20GiB
Formatting /dev/mmcblk0p2 -> ext4
Adding partition to BlockDevice(/dev/mmcblk0, size=58.2GB, free_space=62.5GB, bus_type=None), 20GiB->100%
Adding partition using the following parted command: /dev/mmcblk0 mkpart primary ext4 20GiB 100%
Could not get UUID for partition. Waiting 0s before retrying.
Formatting /dev/mmcblk0p3 -> ext4
Mounting / to /mnt/archinstall/ using Partition(path=/dev/mmcblk0p2, size=19.5, PARTUUID=c14b3108-c45e-4c98-9946-025f4ad136ee, fs=ext4)
Mounting /boot to /mnt/archinstall/boot using Partition(path=/dev/mmcblk0p1, size=0.5, PARTUUID=6bc9f849-ce93-4309-b46d-58703c6bfa70, fs=vfat)
Mounting /home to /mnt/archinstall/home using Partition(path=/dev/mmcblk0p3, size=38.2, PARTUUID=0e11c93d-767f-4358-8c20-bc63bce303f7, fs=ext4)
Using mount order: [('/', <function Installer.mount_ordered_layout.<locals>.<lambda> at 0x7f794e69cdc0>), ('/boot', <function Installer.mount_ordered_layout.<locals>.<lambda> at 0x7f794e69ce50>), ('/home', <function Installer.mount_ordered_layout.<locals>.<lambda> at 0x7f794e69cf70>)]
Mounting Partition(path=/dev/mmcblk0p2, size=19.5, PARTUUID=c14b3108-c45e-4c98-9946-025f4ad136ee, fs=ext4) to /mnt/archinstall/
Getting mount information for device path /mnt/archinstall
Mounting Partition(path=/dev/mmcblk0p1, size=0.5, PARTUUID=6bc9f849-ce93-4309-b46d-58703c6bfa70, fs=vfat) to /mnt/archinstall/boot
Getting mount information for device path /mnt/archinstall/boot
Mounting Partition(path=/dev/mmcblk0p3, size=38.2, PARTUUID=0e11c93d-767f-4358-8c20-bc63bce303f7, fs=ext4) to /mnt/archinstall/home
Getting mount information for device path /mnt/archinstall/home
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot0
Could not get free space on /dev/mmcblk0boot0: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot0', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot0: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot0:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot1
Could not get free space on /dev/mmcblk0boot1: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot1', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot1: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot1:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot0
Could not get free space on /dev/mmcblk0boot0: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot0', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot0: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot0:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot0
Could not get free space on /dev/mmcblk0boot0: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot0', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot0: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot0:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot1
Could not get free space on /dev/mmcblk0boot1: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot1', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot1: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot1:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot0
Could not get free space on /dev/mmcblk0boot0: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot0', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot0: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot0:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot1
Could not get free space on /dev/mmcblk0boot1: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot1', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot1: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot1:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot1
Could not get free space on /dev/mmcblk0boot1: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot1', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot1: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot1:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot0
Could not get free space on /dev/mmcblk0boot0: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot0', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot0: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot0:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot1
Could not get free space on /dev/mmcblk0boot1: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot1', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot1: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot1:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Filtering available mounts {PosixPath('/mnt/archinstall/home'): Partition(path=/dev/mmcblk0p3, size=38.2, PARTUUID=0e11c93d-767f-4358-8c20-bc63bce303f7, fs=ext4, mounted=/mnt/archinstall/home), PosixPath('/mnt/archinstall/boot'): Partition(path=/dev/mmcblk0p1, size=0.5, PARTUUID=6bc9f849-ce93-4309-b46d-58703c6bfa70, fs=vfat, mounted=/mnt/archinstall/boot), PosixPath('/mnt/archinstall'): Partition(path=/dev/mmcblk0p2, size=19.5, PARTUUID=c14b3108-c45e-4c98-9946-025f4ad136ee, fs=ext4, mounted=/mnt/archinstall)} to those under /mnt/archinstall
Available partitions: {PosixPath('/mnt/archinstall'): Partition(path=/dev/mmcblk0p2, size=19.5, PARTUUID=c14b3108-c45e-4c98-9946-025f4ad136ee, fs=ext4, mounted=/mnt/archinstall), PosixPath('/mnt/archinstall/boot'): Partition(path=/dev/mmcblk0p1, size=0.5, PARTUUID=6bc9f849-ce93-4309-b46d-58703c6bfa70, fs=vfat, mounted=/mnt/archinstall/boot), PosixPath('/mnt/archinstall/home'): Partition(path=/dev/mmcblk0p3, size=38.2, PARTUUID=0e11c93d-767f-4358-8c20-bc63bce303f7, fs=ext4, mounted=/mnt/archinstall/home)}
Waiting for automatic mirror selection (reflector) to complete.
Waiting for dbus-org.freedesktop.timesync1.service to enter running state
A new package mirror-list has been created: /etc/pacman.d/mirrorlist
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot0
Could not get free space on /dev/mmcblk0boot0: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot0', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot0: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot0:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot1
Could not get free space on /dev/mmcblk0boot1: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot1', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot1: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot1:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot0
Could not get free space on /dev/mmcblk0boot0: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot0', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot0: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot0:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot0
Could not get free space on /dev/mmcblk0boot0: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot0', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot0: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot0:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot1
Could not get free space on /dev/mmcblk0boot1: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot1', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot1: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot1:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot0
Could not get free space on /dev/mmcblk0boot0: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot0', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot0: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot0:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot1
Could not get free space on /dev/mmcblk0boot1: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot1', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot1: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot1:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot1
Could not get free space on /dev/mmcblk0boot1: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot1', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot1: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot1:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot0
Could not get free space on /dev/mmcblk0boot0: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot0', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot0: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot0:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Could not get block device information using blkid() using command blkid -p -o export /dev/mmcblk0boot1
Could not get free space on /dev/mmcblk0boot1: ['/usr/bin/parted', '-s', '--machine', '/dev/mmcblk0boot1', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/mmcblk0boot1: unrecognised disk label\r\nBYT;\r\n/dev/mmcblk0boot1:4194kB:sd/mmc:512:512:unknown:Generic SD/MMC Storage Card:;\r\n'
Filtering available mounts {PosixPath('/mnt/archinstall/home'): Partition(path=/dev/mmcblk0p3, size=38.2, PARTUUID=0e11c93d-767f-4358-8c20-bc63bce303f7, fs=ext4, mounted=/mnt/archinstall/home), PosixPath('/mnt/archinstall/boot'): Partition(path=/dev/mmcblk0p1, size=0.5, PARTUUID=6bc9f849-ce93-4309-b46d-58703c6bfa70, fs=vfat, mounted=/mnt/archinstall/boot), PosixPath('/mnt/archinstall'): Partition(path=/dev/mmcblk0p2, size=19.5, PARTUUID=c14b3108-c45e-4c98-9946-025f4ad136ee, fs=ext4, mounted=/mnt/archinstall)} to those under /mnt/archinstall
Available partitions: {PosixPath('/mnt/archinstall'): Partition(path=/dev/mmcblk0p2, size=19.5, PARTUUID=c14b3108-c45e-4c98-9946-025f4ad136ee, fs=ext4, mounted=/mnt/archinstall), PosixPath('/mnt/archinstall/boot'): Partition(path=/dev/mmcblk0p1, size=0.5, PARTUUID=6bc9f849-ce93-4309-b46d-58703c6bfa70, fs=vfat, mounted=/mnt/archinstall/boot), PosixPath('/mnt/archinstall/home'): Partition(path=/dev/mmcblk0p3, size=38.2, PARTUUID=0e11c93d-767f-4358-8c20-bc63bce303f7, fs=ext4, mounted=/mnt/archinstall/home)}
System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
The multilib flag is not set. This system will be installed without multilib repositories enabled.
The testing flag is not set. This system will be installed without testing repositories enabled.
Installing packages: ['base', 'base-devel', 'linux-firmware', 'linux', 'intel-ucode']
Enabling periodic TRIM
Enabling service fstrim.timer
['/usr/bin/arch-chroot', '/mnt/archinstall', 'systemctl', 'enable', 'fstrim.timer'] exited with abnormal exit code [256]: b'mount: /mnt/archinstall/dev: udev already mounted on /mnt/archinstall/dev.\r\n       dmesg(1) may have more information after failed mount system call.\r\n==> ERROR: failed to setup chroot /mnt/archinstall\r\n'
```

**Comment by Torxed** [comment] 2022-10-06 06:26
duplicate of #1495 but this has a better title :) Thanks for submitting!

**Closed by Torxed** 2022-10-06 06:26 UTC
