### ISSUE TITLE
Something happen when i try install arch

### ISSUE THREAD

**Issue by ImStoleYourCheese** [archlinux/archinstall#2559] opened 2024-07-01 13:48 UTC
i cant undestand

```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/bin/archinstall", line 5, in <module>
fron archinstall import run_as_a_module
File "/usr/lib/python3.12/site-packages/archinstall/_init_.py", line 11, in <module> from lib import disk
File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/_init__.py", line 1, in <module> fron device handler import device handler, disk_layouts
File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 649, in <module> device handler = DeviceHandler()
File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 38, in _init_
self.load devices() File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 74, in load devices Isbik_info = get_isbik_info(partition.path)
File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_nodel.py", line 1136, in get Isblk info if infos: fetch_isbik_info(deu_path):
File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device nodel.py", line 1121, in _fetch_lsblk_info
raise DiskError(f'Failed to read disk "(deu_path)" with isbik') archinstall.lib.exceptions. DiskError: Failed to read disk "/dev/sdb1" with Isbik
```
![image](https://github.com/archlinux/archinstall/assets/130311040/2a74cd9b-3afe-4f93-a62f-b39acf455b91)

**Comment by svartkanin** [comment] 2024-07-02 10:50
Can you please provide the log file /var/log/archinstall/install.log

**Comment by arlsdk** [comment] 2024-07-04 19:05
Could you try to reformat your disks with **cfdisk** and try again? Had the same issue.

**Comment by codefiles** [comment] 2024-07-06 13:34
Duplicate of #1993

**Closed** 2024-08-24 07:30 UTC
