### ISSUE TITLE
systemd-boot  and linux-zen are problem

### ISSUE THREAD

**Issue by mumin16** [archlinux/archinstall#683] opened 2021-11-01 17:17 UTC
boot section is not modify for linux-zen.

**Comment by Torxed** [comment] 2021-11-02 08:44
Did you test latest master or the official version on the official ISO? I believe this is a duplicate of #541

**Comment by mumin16** [comment] 2021-11-02 10:16
/boot/loader/entries/2021-11-01_06-18-16.conf
linux /vmlinuz-linux
initrd /initramfs-linux.img
-> convert
linux /vmlinuz-linux-zen
initrd /initramfs-linux-zen.img

**Comment by Torxed** [comment] 2021-11-02 10:21
This is fixed in `master` (https://github.com/archlinux/archinstall/pull/534) and will be released in the upcoming version :)

**Closed** 2023-09-17 08:36 UTC
