### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by dsx120209** [archlinux/archinstall#2795] opened 2024-11-10 00:46 UTC
### Which ISO version are you using?

2024.11.01

### The installation log

```json
Could not determine the filesystem: None
Hardware model detected: ASUSTeK COMPUTER INC. X550JK; UEFI mode: True
Processor model detected: Intel(R) Core(TM) i5-4200H CPU @ 2.80GHz
Memory statistics: 6673020 available out of 8010612 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

Virtualization detected: None; is VM: False
Graphics devices detected: dict_keys(['Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)', 'NVIDIA Corporation GM107M [GeForce GTX 850M] (rev a2)'])
Disk states before installing: [
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "squashfs",
        "fsuse_percentage": "100%",
        "fsver": "4.0",
        "log_sec": 512,
        "mountpoint": "/run/archiso/airootfs",
        "mountpoints": [
            "/run/archiso/airootfs"
        ],
        "name": "loop0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/loop0",
        "pkname": null,
        "pttype": null,
        "ptuuid": null,
        "rota": false,
        "size": "810 MiB",
        "tran": null,
        "type": "loop",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda1",
                "partn": 1,
                "parttype": "c12a7328-f81f-11d2-ba4b-00a0c93ec93b",
                "partuuid": "f743a711-a8d5-4ff4-a816-ea6c6a46b1f5",
                "path": "/dev/sda1",
                "pkname": "sda",
                "pttype": "gpt",
                "ptuuid": "c6be7f48-a7f7-4297-81eb-44bfba0a4b8c",
                "rota": false,
                "size": "1024 MiB",
                "tran": null,
                "type": "part",
                "uuid": "B72E-BECE"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ext4",
                "fsuse_percentage": null,
                "fsver": "1.0",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda2",
                "partn": 2,
                "parttype": "4f68bce3-e8cd-4db1-96e7-fbcaf984b709",
                "partuuid": "78975444-7bab-4b86-8a49-8ebe5590cb13",
                "path": "/dev/sda2",
                "pkname": "sda",
                "pttype": "gpt",
                "ptuuid": "c6be7f48-a7f7-4297-81eb-44bfba0a4b8c",
                "rota": false,
                "size": "33792 MiB",
                "tran": null,
                "type": "part",
                "uuid": "d5b5565d-8fbc-4adf-95f3-fd144340c176"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ext4",
                "fsuse_percentage": null,
                "fsver": "1.0",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda3",
                "partn": 3,
                "parttype": "0fc63daf-8483-4772-8e79-3d69d8477de4",
                "partuuid": "4a4b22da-11cf-49d6-90d3-3d9425d291dd",
                "path": "/dev/sda3",
                "pkname": "sda",
                "pttype": "gpt",
                "ptuuid": "c6be7f48-a7f7-4297-81eb-44bfba0a4b8c",
                "rota": false,
                "size": "308581 MiB",
                "tran": null,
                "type": "part",
                "uuid": "8a9c2276-4d9c-40f0-9d20-79da8036efe6"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sda",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sda",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "c6be7f48-a7f7-4297-81eb-44bfba0a4b8c",
        "rota": false,
        "size": "343399 MiB",
        "tran": "sata",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sdb1",
                "partn": 1,
                "parttype": "c12a7328-f81f-11d2-ba4b-00a0c93ec93b",
                "partuuid": "298b5d82-81c9-443a-b2fd-07fff4127289",
                "path": "/dev/sdb1",
                "pkname": "sdb",
                "pttype": "gpt",
                "ptuuid": "70c3231a-fbad-4ee6-ab02-92cfdafd14be",
                "rota": false,
                "size": "300 MiB",
                "tran": null,
                "type": "part",
                "uuid": "3D59-E43F"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": null,
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sdb2",
                "partn": 2,
                "parttype": "e3c9e316-0b5c-4db8-817d-f92df00215ae",
                "partuuid": "e690490c-edc4-4d57-babf-c22f1e5bf6e3",
                "path": "/dev/sdb2",
                "pkname": "sdb",
                "pttype": "gpt",
                "ptuuid": "70c3231a-fbad-4ee6-ab02-92cfdafd14be",
                "rota": false,
                "size": "16 MiB",
                "tran": null,
                "type": "part",
                "uuid": null
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ntfs",
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sdb3",
                "partn": 3,
                "parttype": "ebd0a0a2-b9e5-4433-87c0-68b6b72699c7",
                "partuuid": "98e9f2eb-8b6b-4584-ac28-2ef4befbc08b",
                "path": "/dev/sdb3",
                "pkname": "sdb",
                "pttype": "gpt",
                "ptuuid": "70c3231a-fbad-4ee6-ab02-92cfdafd14be",
                "rota": false,
                "size": "131073 MiB",
                "tran": null,
                "type": "part",
                "uuid": "DAF4A498F4A47901"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ntfs",
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sdb4",
                "partn": 4,
                "parttype": "ebd0a0a2-b9e5-4433-87c0-68b6b72699c7",
                "partuuid": "7ad0054b-c209-44ed-9c50-0e9a5ce74024",
                "path": "/dev/sdb4",
                "pkname": "sdb",
                "pttype": "gpt",
                "ptuuid": "70c3231a-fbad-4ee6-ab02-92cfdafd14be",
                "rota": false,
                "size": "356996 MiB",
                "tran": null,
                "type": "part",
                "uuid": "118DE95AB4562F3E"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sdb",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sdb",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "70c3231a-fbad-4ee6-ab02-92cfdafd14be",
        "rota": false,
        "size": "488386 MiB",
        "tran": "sata",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [
                    {
                        "children": [],
                        "fsavail": null,
                        "fsroots": [],
                        "fstype": "iso9660",
                        "fsuse_percentage": null,
                        "fsver": "Joliet Extension",
                        "log_sec": 512,
                        "mountpoint": null,
                        "mountpoints": [],
                        "name": "ventoy",
                        "partn": null,
                        "parttype": null,
                        "partuuid": null,
                        "path": "/dev/mapper/ventoy",
                        "pkname": "sdc1",
                        "pttype": "dos",
                        "ptuuid": "211019da",
                        "rota": false,
                        "size": "1154 MiB",
                        "tran": null,
                        "type": "dm",
                        "uuid": "2024-11-01-10-09-22-00"
                    }
                ],
                "fsavail": null,
                "fsroots": [],
                "fstype": "exfat",
                "fsuse_percentage": null,
                "fsver": "1.0",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sdc1",
                "partn": 1,
                "parttype": "0x7",
                "partuuid": "f9c4345e-01",
                "path": "/dev/sdc1",
                "pkname": "sdc",
                "pttype": "dos",
                "ptuuid": "f9c4345e",
                "rota": false,
                "size": "244165 MiB",
                "tran": null,
                "type": "part",
                "uuid": "4E21-0000"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT16",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sdc2",
                "partn": 2,
                "parttype": "0xef",
                "partuuid": "f9c4345e-02",
                "path": "/dev/sdc2",
                "pkname": "sdc",
                "pttype": "dos",
                "ptuuid": "f9c4345e",
                "rota": false,
                "size": "32 MiB",
                "tran": null,
                "type": "part",
                "uuid": "223C-F3F8"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sdc",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sdc",
        "pkname": null,
        "pttype": "dos",
        "ptuuid": "f9c4345e",
        "rota": false,
        "size": "244198 MiB",
        "tran": "usb",
        "type": "disk",
        "uuid": null
    }
]
Checking version...
Failed determine pacman version: ['/usr/bin/pacman', '-Qu', 'archinstall'] exited with abnormal exit code [1]: [?25l[?25h
    score: 2
Loaded mirror mirror.aarnet.edu.au with current score of 2
    score: 4
Loaded mirror mirror.aarnet.edu.au with current score of 4
    score: 3
Loaded mirror mir.archlinux.fr with current score of 3
    score: 14
Loaded mirror ftp.tu-chemnitz.de with current score of 14
    score: 83
Loaded mirror ftp.hosteurope.de with current score of 83
    score: 85
Loaded mirror ftp.hosteurope.de with current score of 85
    score: 1
Loaded mirror mirrors.rit.edu with current score of 1
    score: 1
Loaded mirror mirrors.rit.edu with current score of 1
    score: 3
Loaded mirror mirrors.rit.edu with current score of 3
    score: 3
Loaded mirror ftp.ek-cer.hu with current score of 3
    score: 1
Loaded mirror ftp.nluug.nl with current score of 1
    score: 3
Loaded mirror ftp.nluug.nl with current score of 3
    score: 2
Loaded mirror ftp.gwdg.de with current score of 2
    score: 4
Loaded mirror ftp.gwdg.de with current score of 4
    score: 1
Loaded mirror mirror.puzzle.ch with current score of 1
    score: 2
Loaded mirror mirror.puzzle.ch with current score of 2
    score: 4
Loaded mirror mirror.puzzle.ch with current score of 4
    score: 6
Loaded mirror ftp.linux.org.tr with current score of 6
    score: 13
Loaded mirror www.gtlib.gatech.edu with current score of 13
Loaded mirror rsync.gtlib.gatech.edu
    score: 14
Loaded mirror ftp.uni-kl.de with current score of 14
    score: 16
Loaded mirror ftp.uni-kl.de with current score of 16
    score: 13
Loaded mirror ftp.uni-bayreuth.de with current score of 13
    score: 3
Loaded mirror mirror.csclub.uwaterloo.ca with current score of 3
    score: 3
Loaded mirror mirror.csclub.uwaterloo.ca with current score of 3
    score: 5
Loaded mirror mirror.csclub.uwaterloo.ca with current score of 5
    score: 4
Loaded mirror mirror.umd.edu with current score of 4
    score: 4
Loaded mirror mirror.umd.edu with current score of 4
    score: 7
Loaded mirror mirror.umd.edu with current score of 7
    score: 5
Loaded mirror ftp.iinet.net.au with current score of 5
    score: 9
Loaded mirror ftp.iinet.net.au with current score of 9
    score: 5
Loaded mirror ftp-stud.hs-esslingen.de with current score of 5
    score: 7
Loaded mirror ftp-stud.hs-esslingen.de with current score of 7
    score: 2
Loaded mirror mirror.archlinux.no with current score of 2
    score: 2
Loaded mirror mirror.archlinux.no with current score of 2
    score: 5
Loaded mirror mirror.internode.on.net with current score of 5
    score: 9
Loaded mirror mirror.internode.on.net with current score of 9
    score: 7
Loaded mirror mirror.isoc.org.il with current score of 7
    score: 6
Loaded mirror mirror.isoc.org.il with current score of 6
    score: 7
Loaded mirror ftp.osuosl.org with current score of 7
    score: 7
Loaded mirror ftp.osuosl.org with current score of 7
    score: 9
Loaded mirror ftp.osuosl.org with current score of 9
    score: 2
Loaded mirror archlinux.c3sl.ufpr.br with current score of 2
    score: 2
Loaded mirror archlinux.c3sl.ufpr.br with current score of 2
    score: 6
Loaded mirror archlinux.c3sl.ufpr.br with current score of 6
    score: 83
Loaded mirror mirror.yandex.ru with current score of 83
    score: 84
Loaded mirror mirror.yandex.ru with current score of 84
    score: 3
Loaded mirror ftp.spline.inf.fu-berlin.de with current score of 3
    score: 3
Loaded mirror ftp.spline.inf.fu-berlin.de with current score of 3
    score: 12
Loaded mirror rsync.spline.inf.fu-berlin.de with current score of 12
    score: 2
Loaded mirror mirror.selfnet.de with current score of 2
    score: 2
Loaded mirror mirror.selfnet.de with current score of 2
    score: 5
Loaded mirror mirror.selfnet.de with current score of 5
    score: 1
Loaded mirror mirrors.lug.mtu.edu with current score of 1
    score: 1
Loaded mirror mirrors.lug.mtu.edu with current score of 1
    score: 3
Loaded mirror mirrors.lug.mtu.edu with current score of 3
    score: 8
Loaded mirror ftp.rediris.es with current score of 8
    score: 5
Loaded mirror archlinux.nautile.nc with current score of 5
    score: 4
Loaded mirror archlinux.nautile.nc with current score of 4
    score: 24
Loaded mirror rsync.archlinux.nautile.nc with current score of 24
    score: 4
Loaded mirror ftp.otenet.gr with current score of 4
Loaded mirror mirror.cse.iitk.ac.in
    score: 4
Loaded mirror mirrors.xmission.com with current score of 4
    score: 4
Loaded mirror ftp.cc.uoc.gr with current score of 4
    score: 2
Loaded mirror ftp.tku.edu.tw with current score of 2
    score: 5
Loaded mirror ftp.tku.edu.tw with current score of 5
    score: 1
Loaded mirror mirrors.kernel.org with current score of 1
    score: 2
Loaded mirror mirrors.kernel.org with current score of 2
    score: 3
Loaded mirror mirrors.kernel.org with current score of 3
    score: 12
Loaded mirror mirrors.163.com with current score of 12
Loaded mirror archlinux.mirror.kangaroot.net
    score: 2
Loaded mirror ftp.rnl.tecnico.ulisboa.pt with current score of 2
    score: 3
Loaded mirror ftp.rnl.tecnico.ulisboa.pt with current score of 3
    score: 5
Loaded mirror ftp.rnl.tecnico.ulisboa.pt with current score of 5
    score: 1
Loaded mirror mirrors.dotsrc.org with current score of 1
    score: 1
Loaded mirror mirrors.dotsrc.org with current score of 1
    score: 4
Loaded mirror mirrors.dotsrc.org with current score of 4
    score: 7
Loaded mirror mirror.its.dal.ca with current score of 7
    score: 10
Loaded mirror mirror.its.dal.ca with current score of 10
    score: 14
Loaded mirror archlinux.mirrors.ovh.net with current score of 14
    score: 14
Loaded mirror archlinux.mirrors.ovh.net with current score of 14
    score: 3
Loaded mirror ftp.jaist.ac.jp with current score of 3
    score: 4
Loaded mirror ftp.jaist.ac.jp with current score of 4
    score: 6
Loaded mirror ftp.jaist.ac.jp with current score of 6
    score: 1
Loaded mirror ftp.halifax.rwth-aachen.de with current score of 1
    score: 1
Loaded mirror ftp.halifax.rwth-aachen.de with current score of 1
    score: 3
Loaded mirror ftp.halifax.rwth-aachen.de with current score of 3
    score: 14
Loaded mirror artfiles.org with current score of 14
    score: 2
Loaded mirror mirror.datacenter.by with current score of 2
    score: 4
Loaded mirror mirror.datacenter.by with current score of 4
    score: 5
Loaded mirror archlinux.uib.no with current score of 5
    score: 1
Loaded mirror mirrors.cat.pdx.edu with current score of 1
    score: 4
Loaded mirror mirrors.cat.pdx.edu with current score of 4
    score: 2
Loaded mirror mirror.vpsfree.cz with current score of 2
    score: 3
Loaded mirror archlinux.cs.nycu.edu.tw with current score of 3
    score: 4
Loaded mirror archlinux.cs.nycu.edu.tw with current score of 4
    score: 7
Loaded mirror archlinux.cs.nycu.edu.tw with current score of 7
    score: 2
Loaded mirror ftp.byfly.by with current score of 2
    score: 4
Loaded mirror ftp.byfly.by with current score of 4
Loaded mirror archlinux.mirror.root.lu
    score: 2
Loaded mirror mirrors.rutgers.edu with current score of 2
Loaded mirror mirrors.rutgers.edu
    score: 2
Loaded mirror ftp.ntua.gr with current score of 2
    score: 4
Loaded mirror ftp.ntua.gr with current score of 4
    score: 7
Loaded mirror mirrors.nix.org.ua with current score of 7
    score: 7
Loaded mirror mirrors.nix.org.ua with current score of 7
    score: 9
Loaded mirror mirrors.nix.org.ua with current score of 9
    score: 2
Loaded mirror mirrors.ustc.edu.cn with current score of 2
    score: 3
Loaded mirror mirrors.ustc.edu.cn with current score of 3
    score: 5
Loaded mirror rsync.mirrors.ustc.edu.cn with current score of 5
    score: 2
Loaded mirror ftp.lysator.liu.se with current score of 2
    score: 3
Loaded mirror ftp.lysator.liu.se with current score of 3
    score: 4
Loaded mirror ftp.lysator.liu.se with current score of 4
    score: 1
Loaded mirror mirror.ams1.nl.leaseweb.net with current score of 1
    score: 1
Loaded mirror mirror.dal10.us.leaseweb.net with current s
```

#### Description of the issue

I was installing on X hardware ...

Then X Y Z happened and archinstall crashed ...

#### Virtual machine config:

```xml
<domain type="kvm">
  <name>my-arch-machine</name>
  ...
  </devices>
</domain>
```

```console
/usr/bin/qemu-system-x86_64 -name guest=my-arch-machine,debug-threads=on -object ...
```

**Comment by svartkanin** [comment] 2024-11-10 06:12
What is the problem?

**Comment by dsx120209** [comment] 2024-11-10 09:52
> What is the problem?

An error occurred while installing using the archinstall command. The above is the log. I don't know what happened.

**Comment by Torxed** [comment] 2024-11-10 12:51
The log appears to be cut short, we would need the stack trace as well.

**Comment by dsx120209** [comment] 2024-11-10 13:25
> The log appears to be cut short, we would need the stack trace as well.

How can I do this?

**Comment by Torxed** [comment] 2024-11-10 14:11
> > The log appears to be cut short, we would need the stack trace as well.
> 
> How can I do this?

It should be in `/var/log/archinstall/install.log` at the very end.
Or worst case, take a photo with a phone of the screen and post a picture.

**Comment by dsx120209** [comment] 2024-11-11 08:02
> > > The log appears to be cut short, we would need the stack trace as well.
> > 
> > How can I do this?
> 
> It should be in `/var/log/archinstall/install.log` at the very end.
> Or worst case, take a photo with a phone of the screen and post a picture.

![IMG_20241111_160220.jpg](https://github.com/user-attachments/assets/c94c57f3-6311-4957-a02c-3366c0f64881)

I'm not sure if this is it

**Comment by dsx120209** [comment] 2024-11-11 08:03
> > > The log appears to be cut short, we would need the stack trace as well.
> > 
> > How can I do this?
> 
> It should be in `/var/log/archinstall/install.log` at the very end.
> Or worst case, take a photo with a phone of the screen and post a picture.

![IMG_20241111_160220.jpg](https://github.com/user-attachments/assets/c94c57f3-6311-4957-a02c-3366c0f64881)

I'm not sure if this is it

**Comment by Torxed** [comment] 2024-11-11 08:57
Perfect, yes that is the error!
Luckily it's a duplicate of #2764 so I'll close this one.

**Closed by Torxed** 2024-11-11 08:57 UTC
