### ISSUE TITLE
Custom mirror .... bug or can not connect local mirror  ?

### ISSUE THREAD

**Issue by Maziar123** [archlinux/archinstall#1997] opened 2023-08-08 15:53 UTC
Hi

My ver 2.6

I try to use a **custom mirror** to connect to my local mirror similar mirrorlist :
My local mirror:  http://xx.xx.xx.xx:8080/archlinux/

The wizard must get the name [MUST ENTER] I entering: mirror1
get address: http://xx.xx.xx.xx:8080/archlinux/$repo/os/$arch

But this has unexpected behavior and a custom repo with the name mirror1 to pacman.conf!

**Comment by Dlinuigh** [comment] 2023-09-04 01:40
I have a similar problem, reflector always fails to work, but actually I do not want to use the mirror chosen by the software.

Is there a way to use custom mirrors and avoid updating the list with reflector?

**Comment by svartkanin** [comment] 2023-09-04 12:06
@Maziar123 @Dlinuigh would you mind sharing what exactly the problem is? Is there an error that you see or what is the resulting behavior? 
If you could provide the log file in /var/log/archinstall/install.log that would be helpful

**Comment by svartkanin** [comment] 2023-09-16 23:45
As this isn't reproducible and there are no logs to debug I'll close this for now

**Closed by svartkanin** 2023-09-16 23:45 UTC

**Comment by Torxed** [comment] 2023-09-17 06:10
There is also a `--offline` flag that should make custom/offline mirrors work better by not verifying against archlinux.org
