### ISSUE TITLE
/boot being mounted before / and its causing a crash

### ISSUE THREAD

**Issue by malta-rf** [archlinux/archinstall#2566] opened 2024-07-08 22:49 UTC
### Which ISO version are you using?

2024-07-01

### The installation log

```json
https://0x0.st/XB50.log
```

### describe the problem

I need to dualboot arch/windows, using a SSD for root partition and the windows EFI for the boot partition on a HDD. 

/boot => /dev/sda1 (windows EFI partition) 
/ =>  /dev/sdb1 (SSD)

but archinstall is mounting boot before the root (arch-chroot) and this is causing the script to crash. the fix is simple: just mount the root partition first.
 
every time I need to install arch I have to save the config file, change the disk order in the json file and then load the script again for it to work.

**Comment by svartkanin** [comment] 2024-07-09 08:26
Looks like a duplicate of https://github.com/archlinux/archinstall/issues/2441

**Comment by malta-rf** [comment] 2024-07-09 08:49
> Did you follow the instructions in the readme for dual boot?

I read the instructions but the problem only happens when using 2 differents disks for /boot and / and if boot disk is listed first. if both partitions are in the same disk the installation runs smooth. plus changing the disk orders in the json file also fix the problem.

**Comment by Torxed** [comment] 2024-07-11 18:58
We should ensure that the order in the struct is sorted by mount point.

**Comment by codefiles** [comment] 2024-07-29 00:27
> Looks like a duplicate of #2441

I agree @svartkanin.

Thanks @malta-rf for the info and log.

**Comment by Torxed** [comment] 2024-07-29 06:26
A fix has been merged, so I'll go ahead and close this one for now.

**Closed by Torxed** 2024-07-29 06:26 UTC
