### ISSUE TITLE
Does the installer install microcode for intel/amd machines?

### ISSUE THREAD

**Issue by adnan449** [archlinux/archinstall#284] opened 2021-04-11 23:34 UTC

**Comment by dylanmtaylor** [comment] 2021-04-12 00:23
The answer is no, it's a feature coming in 2.2.0 and is already implemented in that branch.

**Comment by dylanmtaylor** [comment] 2021-04-12 00:32
Duplicate of https://github.com/archlinux/archinstall/issues/177

**Closed** 2021-04-12 04:44 UTC
