### ISSUE TITLE
Keyring error on 2022.10.01 ISO without running pacman-key commands first

### ISSUE THREAD

**Issue by planet36** [archlinux/archinstall#1511] opened 2022-10-06 22:37 UTC
Using archlinux-2022.10.01-x86_64.iso, archinstall fails to install packages unless some `pacman-key` commands are run first.

In archinstall I configured a simple configuration, and these error messages were printed after I started the install.

```
warning: Public keyring not found; have you run 'pacman-key --init'?
downloading required keys...
error: keyring is not writable
...
error: required key missing from keyring
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
==> ERROR: Failed to install packages to new root
```

Running these commands before archinstall yields success.
```
pacman-key --init
pacman-key --populate
```

**Comment by Torxed** [comment] 2022-10-07 05:18
Duplicate of https://github.com/archlinux/archinstall/issues/1389

**Closed by Torxed** 2022-10-07 05:18 UTC
