### ISSUE TITLE
Failed to read disk "/dev/sdb1" with lsblk

### ISSUE THREAD

**Issue by critkitten** [archlinux/archinstall#1578] opened 2022-11-28 23:20 UTC
archinstall 2.5.1 archlinux-2022.11.01-x86_64.iso

1. boot in bios mode
2. /dev/**sda** is target ssd to install archlinux.
3. /dev/**sdb** a usb device created with "dd if=archlinux-2022.11.01-x86_64.iso of=/dev/sdb && sync"
4. Error only appear the first time run archinstall.

**Error if select ">Drive(s)" and press ENTER first time**
```
Could not decode JSON: lsblk: /dev/sdb1: not a block device
{
   "blockdevices": [

   ]
}

Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 311, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 301, in <module>
    ask_user_questions()
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 107, in ask_user_questions
    global_menu.run()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/selection_menu.py", line 336, in run
    if not self._process_selection(value):
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/selection_menu.py", line 353, in _process_selection
    return self.exec_option(config_name, selector)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/selection_menu.py", line 373, in exec_option
    result = selector.func(presel_val)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/global_menu.py", line 79, in <lambda>
    lambda preset: self._select_harddrives(preset),
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/global_menu.py", line 345, in _select_harddrives
    harddrives = select_harddrives(old_harddrives)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/user_interaction/system_conf.py", line 52, in select_harddrives
    hard_drives = all_blockdevices(partitions=False).values()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/helpers.py", line 275, in all_blockdevices
    instances[path] = BlockDevice(path, path_info)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/blockdevice.py", line 53, in __init__
    self._load_partitions()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/blockdevice.py", line 131, in _load_partitions
    self._partitions[part_id] = Partition(root + part_id, block_device=self, part_id=part_id)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/partition.py", line 102, in __init__
    self._partition_info = self._fetch_information()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/partition.py", line 213, in _fetch_information
    lsblk_info = self._call_lsblk()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/partition.py", line 195, in _call_lsblk
    raise DiskError(f'Failed to read disk "{self.device_path}" with lsblk')
archinstall.lib.exceptions.DiskError: Failed to read disk "/dev/sdb1" with lsblk
archinstall  5.52s user 3.79s system 11% cpu 1:18.06 total
```

**lsblk**
```
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0    7:0    0   671M  1 loop /run/archiso/airootfs
sda      8:0    0 111.8G  0 disk 
sdb      8:16   1  29.3G  0 disk 
└─sdb2   8:18   1    15M  0 part 
```

**fdisk /dev/sdb** 
```
Disk /dev/sdb: 29.3 GiB, 31457280000 bytes, 61440000 sectors
Disk model: Basic Line      
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x8802a288

Device     Boot   Start     End Sectors  Size Id Type
/dev/sdb1  *         64 1570815 1570752  767M  0 Empty
/dev/sdb2       1570816 1601535   30720   15M ef EFI (FAT-12/16/32)
```

**Comment by zangwill** [comment] 2022-11-29 07:55
Same Problem. 
lsblk:
![20221129155156](https://user-images.githubusercontent.com/19372775/204470958-2874ff9c-6a9c-4510-9f36-5ef5e8ef2bce.jpg)

Error:
![202211291551561](https://user-images.githubusercontent.com/19372775/204470991-3ce86644-ddd3-4b2b-beb8-98390b01e7ec.jpg)

**Comment by ATamblingPoder** [comment] 2022-11-30 05:34
Seems to be the same issue as #1557

**Comment by Torxed** [comment] 2022-11-30 07:17
Correct, duplicate of https://github.com/archlinux/archinstall/issues/1557

**Closed by Torxed** 2022-11-30 07:17 UTC
