### ISSUE TITLE
Archinstall encounters Error when starting - "/dev/sda3: not a block device"

### ISSUE THREAD

**Issue by SlenLen** [archlinux/archinstall#1993] opened 2023-08-06 20:41 UTC
`exited with abnormal exit code [32]: lsblk: /dev/sda3: not a block device`

When I start archinstall, it exists after a few seconds with the mentioned error.
I tried the newest package from the Arch Repos, and I tried the scripts from the master branch, but regardless this error occurrs.
![IMG_20230806_222932](https://github.com/archlinux/archinstall/assets/68658538/c8ae274b-3af5-4055-af75-690cfc6d39d5)

Running lsblk shows that sda doesn't have a 3rd partition which puzzles me.
sda isn't even relevant I  what I was going to do. I want to install Arch on a different device. Is there any way to make archinstall ignore this or is temporarily removing the drive the only solution?

**Comment by fabianmuehlberger** [comment] 2023-08-18 12:19
Looks like the same issue as #1971 and should be merged if it is.

**Comment by svartkanin** [comment] 2023-09-03 08:15
@fabianmuehlberger this isn't related. 
@SlenLen I'm aware that it's quite a while already, but any chance you have the log file still available, under /var/log/archinstall/install.log

**Comment by svartkanin** [comment] 2023-09-16 23:45
@SlenLen archinstall is reading all available disks at startup, that's to be able to display all possible options to the user what devices they can choose from. It isn't possible to filter them away.
I'd say that the error isn't related to archinstall as lsblk has issues reading the device all together which could indicate that there is some issue with it. A restart might help to resolve it. In any case to debug this more info would be required

**Comment by codefiles** [comment] 2024-07-06 14:08
This bug is still present though the code has changed a little so it looks slightly different in the latest reports of it.

A `DiskError` is raised like the following:

```
archinstall.lib.exceptions.DiskError: Failed to read disk "/dev/sda1" with lsblk
```

This will appear in the log as:

```
Error calling lsblk: lsblk: /dev/sda1: not a block device
{
   "blockdevices": [

   ]
}
```

I can't reproduce the bug but I have seen logs for other issues where this is present, for example #2540 and #2563. In those cases the logs show that the partitions that lsblk failed for are valid as their lsblk information is listed later in the logs under _Disk states before installing_.

**Closed** 2024-08-23 15:22 UTC
