### ISSUE TITLE
[2.3.0-RC1] --config file parsing regressions

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#710] opened 2021-11-10 18:08 UTC
When specifying a config file generated from /var/log/archinstall/user_configuration.json to attempt to retry the same installation, I ran into hardware related import errors until I dropped gfx_driver from the config file, and then once I did, the installer was prompting me to re-enter a lot of entries (not imported properly), even though they seemed to be in the configuration file.

**Comment by Torxed** [comment] 2021-11-18 15:50
I've confirmed the issue but still haven't figured out where the issue is.
I'll fix this before RC2 is released. This is the last and final issue before RC2 can get out.

**Comment by Torxed** [comment] 2021-11-18 16:14
Using the following configuration:
![screenshot](https://user-images.githubusercontent.com/861439/142452727-c9c2836d-f765-49be-8f49-35a1f5607e83.jpg)

I think I'm only getting expected questions *(if `--disk-layout` and `--creds` is omitted)*:
* What to do with the harddrives
* Which filesystem to use
  * To use BTRFS subvolumes or not *(if BTRFS was selected)*
  * To use recommended BTRFS structure or not *(if BTRFS was selected)*
* Disk encryption password
* Desired hostname
* root password
* Super-users *(if root was skipped)*
* Which profile to install
* Which audio server to use
* Additional packages

Audio-server gets asked because we store `None`, and that's what `ask_user_questions()` trigger on.
Additional packages is more or less the same thing.

I think we can go ahead and close this?
There will be some release notes surrounding the split into `--disk-layout` and `--creds` as I think this is why most people will think there's to many questions being asked.

**Closed** 2021-11-18 16:15 UTC

**Comment by hkaancaliskan** [comment] 2021-11-19 20:29
@Torxed https://github.com/archlinux/archinstall/blob/9b944b90b151a616e36f7361c7cf3c6951e61970/examples/guided.py#L50 at this line that should have been `archinstall.lib.hardware.AVAILABLE_GFX_DRIVERS`, right?

When i change like that, problem is solved for me

**Comment by Torxed** [comment] 2021-11-20 09:27
> AVAILABLE_GFX_DRIVERS

You are correct, or even better just `archinstall.AVAILABLE_GFX_DRIVERS` as it's exposed in the general library root.

**Comment by Torxed** [comment] 2021-11-20 09:32
Fixed in `master` through 627b6b5
