### ISSUE TITLE
Hyprland desktop profile with nvidia. No nvidia packages installed

### ISSUE THREAD

**Issue by JaKooLit** [archlinux/archinstall#2053] opened 2023-09-13 01:31 UTC
Ive chose hyprland desktop profile with nvidia proprietary drivers.

Upon booting, no nvidia packages installed.

**Comment by Torxed** [comment] 2023-09-20 09:23
Closing as I think it's a duplicate of #2002

**Closed by Torxed** 2023-09-20 09:23 UTC

**Comment by ThijsGaming** [comment] 2023-11-14 19:46
doesn't it also need hyprland-nvidia instead of hyprland
or are you on a laptop?

**Comment by JaKooLit** [comment] 2023-11-14 23:20
> doesn't it also need hyprland-nvidia instead of hyprland
> or are you on a laptop?

are you asking me? 

first off, archinstall dont or cannot install anything outside official repo. And certainly cant compile from source.... atleast thats what I know.

**Comment by ThijsGaming** [comment] 2023-12-05 18:37
> > doesn't it also need hyprland-nvidia instead of hyprland
> > or are you on a laptop?
> 
> are you asking me?
> 
> first off, archinstall dont or cannot install anything outside official repo. And certainly cant compile from source.... atleast thats what I know.

what about using the choatic aur package maybe?
