### ISSUE TITLE
vfat could not get UUID for partition.

### ISSUE THREAD

**Issue by allycatty** [archlinux/archinstall#1522] opened 2022-10-12 08:40 UTC
Issue is persistent even after switching nvme drives. 

`root@archiso ~ # cat /var/log/archinstall/install.log
Hardware model detected: Intel Corporation NUC7i5BNK; UEFI mode: True
Processor model detected: Intel(R) Core(TM) i5-7260U CPU @ 2.20GHz
Memory statistics: 6210096 available out of 8022624 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
Virtualization detected: None; is VM: None
Graphics devices detected: dict_keys(['Intel Corporation Iris Plus Graphics 640 (rev 06)'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '686.9M'}, {'name': 'nvme0n1', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '465.8G', 'children': [{'name': 'nvme0n1p1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': None, 'uuid': '7A87-F390', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '511M'}, {'name': 'nvme0n1p2', 'fstype': 'ext4', 'fsver': '1.0', 'label': None, 'uuid': '0972e4ef-3c7e-4e94-9358-280ad80894da', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '465.3G'}]}]}
Testing connectivity to the Arch Linux mirrors ...
Setting font: LatGrkCyr-8x16
Password strength: very weak
 -- Chosen configuration --
{
    "HSM": null,
    "__separator__": null,
    "additional-repositories": [],
    "archinstall-language": "English",
    "audio": null,
    "bootloader": "systemd-bootctl",
    "config_version": "2.5.1",
    "debug": false,
    "harddrives": [
        "/dev/nvme0n1"
    ],
    "hostname": "nussy",
    "kernels": [
        "linux"
    ],
    "keyboard-layout": "us",
    "mirror-region": {},
    "nic": {
        "dhcp": true,
        "dns": null,
        "gateway": null,
        "iface": null,
        "ip": null,
        "type": "iso"
    },
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [],
    "parallel downloads": 0,
    "profile": null,
    "save_config": null,
    "script": "guided",
    "silent": false,
    "swap": true,
    "sys-encoding": "UTF-8",
    "sys-language": "en_US",
    "timezone": "America/Los_Angeles",
    "version": "2.5.1"
}
{
    "/dev/nvme0n1": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "mountpoint": "/boot",
                "size": "512MiB",
                "start": "1MiB",
                "type": "primary",
                "wipe": true
            },
            {
                "encrypted": false,
                "filesystem": {
                    "format": "ext4",
                    "mount_options": []
                },
                "mountpoint": "/",
                "size": "100%",
                "start": "513MiB",
                "type": "primary",
                "wipe": true
            }
        ],
        "wipe": true
    }
}
Creating a new partition label on /dev/nvme0n1
Adding partition to BlockDevice(/dev/nvme0n1, size=465.8GB, free_space=1031kB+1049kB+7680B, bus_type=nvme), 1MiB->512MiB
Adding partition using the following parted command: /dev/nvme0n1 mkpart primary fat32 1MiB 512MiB
Could not get UUID for partition. Waiting 0s before retrying.
Could not get UUID for partition. Waiting 1s before retrying.
Could not get UUID for partition. Waiting 2s before retrying.
Could not get UUID for partition. Waiting 3s before retrying.
Could not get UUID for partition. Waiting 4s before retrying.
Could not find the new PARTUUID after adding the partition.
Previous partitions: []
New partitions: {None}
Hardware model detected: Intel Corporation NUC7i5BNK; UEFI mode: True
Processor model detected: Intel(R) Core(TM) i5-7260U CPU @ 2.20GHz
Memory statistics: 6219368 available out of 8022624 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
Virtualization detected: None; is VM: None
Graphics devices detected: dict_keys(['Intel Corporation Iris Plus Graphics 640 (rev 06)'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '686.9M'}, {'name': 'nvme0n1', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '465.8G'}]}
Testing connectivity to the Arch Linux mirrors ...
Setting font: LatGrkCyr-8x16
Could not get block device information using blkid() using command blkid -p -o export /dev/nvme0n1
Could not get free space on /dev/nvme0n1: ['/usr/bin/parted', '-s', '--machine', '/dev/nvme0n1', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/nvme0n1: unrecognised disk label\r\nBYT;\r\n/dev/nvme0n1:500GB:nvme:512:512:unknown:Samsung SSD 960 EVO 500GB:;\r\n'
Password strength: very weak
Hardware model detected: Intel Corporation NUC7i5BNK; UEFI mode: True
Processor model detected: Intel(R) Core(TM) i5-7260U CPU @ 2.20GHz
Memory statistics: 6171816 available out of 8022624 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
Virtualization detected: None; is VM: None
Graphics devices detected: dict_keys(['Intel Corporation Iris Plus Graphics 640 (rev 06)'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '686.9M'}, {'name': 'nvme0n1', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '465.8G'}]}
Testing connectivity to the Arch Linux mirrors ...
Setting font: LatGrkCyr-8x16
Could not get block device information using blkid() using command blkid -p -o export /dev/nvme0n1
Could not get free space on /dev/nvme0n1: ['/usr/bin/parted', '-s', '--machine', '/dev/nvme0n1', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/nvme0n1: unrecognised disk label\r\nBYT;\r\n/dev/nvme0n1:500GB:nvme:512:512:unknown:Samsung SSD 960 EVO 500GB:;\r\n'
Password strength: very weak
 -- Chosen configuration --
{
    "HSM": null,
    "__separator__": null,
    "additional-repositories": [],
    "archinstall-language": "English",
    "audio": null,
    "bootloader": "systemd-bootctl",
    "config_version": "2.5.1",
    "debug": false,
    "harddrives": [
        "/dev/nvme0n1"
    ],
    "hostname": "nussy",
    "kernels": [
        "linux"
    ],
    "keyboard-layout": "us",
    "mirror-region": {},
    "nic": {
        "dhcp": true,
        "dns": null,
        "gateway": null,
        "iface": null,
        "ip": null,
        "type": "iso"
    },
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [],
    "parallel downloads": 0,
    "profile": null,
    "save_config": null,
    "script": "guided",
    "silent": false,
    "swap": true,
    "sys-encoding": "UTF-8",
    "sys-language": "en_US",
    "timezone": "America/Los_Angeles",
    "version": "2.5.1"
}
{
    "/dev/nvme0n1": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "mountpoint": "/boot",
                "size": "512MiB",
                "start": "1MiB",
                "type": "primary",
                "wipe": true
            },
            {
                "encrypted": false,
                "filesystem": {
                    "format": "ext4",
                    "mount_options": []
                },
                "mountpoint": "/",
                "size": "100%",
                "start": "513MiB",
                "type": "primary",
                "wipe": true
            }
        ],
        "wipe": true
    }
}
Creating a new partition label on /dev/nvme0n1
Adding partition to BlockDevice(/dev/nvme0n1, size=465.8GB, free_space=?, bus_type=nvme), 1MiB->512MiB
Adding partition using the following parted command: /dev/nvme0n1 mkpart primary fat32 1MiB 512MiB
Could not get UUID for partition. Waiting 0s before retrying.
Could not get UUID for partition. Waiting 1s before retrying.
Could not get UUID for partition. Waiting 2s before retrying.
Formatting /dev/nvme0n1p1 -> vfat
/usr/bin/mkfs.vfat -F32 /dev/nvme0n1p1
Marking partition Partition(path=/dev/nvme0n1p1, size=0.5, PARTUUID=0698c0f5-6262-4ea3-8f31-3677b8d53053, fs=vfat) as bootable.
Setting boot on on (parted) partition index 1
Adding partition to BlockDevice(/dev/nvme0n1, size=465.8GB, free_space=?, bus_type=nvme), 513MiB->100%
Adding partition using the following parted command: /dev/nvme0n1 mkpart primary ext4 513MiB 100%
Could not get UUID for partition. Waiting 0s before retrying.
uuid None or 0698c0f5-6262-4ea3-8f31-3677b8d53053 not found. Waiting 0s for next attempt
uuid None or 0698c0f5-6262-4ea3-8f31-3677b8d53053 not found. Waiting 1s for next attempt
Formatting /dev/nvme0n1p1 -> ext4
Mounting / to /mnt/archinstall/ using Partition(path=/dev/nvme0n1p1, size=0.5, PARTUUID=0698c0f5-6262-4ea3-8f31-3677b8d53053, fs=ext4)
Mounting /boot to /mnt/archinstall/boot using Partition(path=/dev/nvme0n1p1, size=0.5, PARTUUID=0698c0f5-6262-4ea3-8f31-3677b8d53053, fs=vfat)
Using mount order: [('/', <function Installer.mount_ordered_layout.<locals>.<lambda> at 0x7fee4b4af2e0>), ('/boot', <function Installer.mount_ordered_layout.<locals>.<lambda> at 0x7fee4b4afac0>)]
Mounting Partition(path=/dev/nvme0n1p1, size=0.5, PARTUUID=0698c0f5-6262-4ea3-8f31-3677b8d53053, fs=ext4) to /mnt/archinstall/
Getting mount information for device path /mnt/archinstall
Mounting Partition(path=/dev/nvme0n1p1, size=0.5, PARTUUID=0698c0f5-6262-4ea3-8f31-3677b8d53053, fs=vfat) to /mnt/archinstall/boot
['/usr/bin/mount', '-t', 'vfat', '/dev/nvme0n1p1', '/mnt/archinstall/boot'] exited with abnormal exit code [8192]: b'mount: /mnt/archinstall/boot: /dev/nvme0n1p1 already mounted on /mnt/archinstall.\r\n       dmesg(1) may have more information after failed mount system call.\r\n'

1 root@archiso ~ # lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0         7:0    0 686.9M  1 loop /run/archiso/airootfs
nvme0n1     259:0    0 465.8G  0 disk 
├─nvme0n1p1 259:2    0   511M  0 part /mnt/archinstall
└─nvme0n1p2 259:3    0 465.3G  0 part 
root@archiso ~ # ls /mnt/archinstall
boot  lost+found`

`[!] A log file has been created here: /var/log/archinstall/install.log
    Please submit this issue (and file) to https://github.com/archlinux/archinstall/issues
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 311, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 316, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', '/mnt'))
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 141, in perform_installation
    with archinstall.Installer(mountpoint, kernels=archinstall.arguments.get('kernels', ['linux'])) as installation:
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 160, in __exit__
    raise args[1]
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 145, in perform_installation
    installation.mount_ordered_layout(archinstall.arguments['disk_layouts'])
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 303, in mount_ordered_layout
    frozen_func()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 297, in <lambda>
    mount_queue[mountpoint] = lambda instance=partition['device_instance'], target=f"{self.target}{mountpoint}": instance.mount(target)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/partition.py", line 569, in mount
    raise err
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/partition.py", line 563, in mount
    mnt_handle = SysCommand(f"/usr/bin/mount -t {fs_type} {device_path} {target}")
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 435, in __init__
    self.create_session()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 486, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.10/site-packages/archinstall/lib/general.py", line 275, in __exit__
    raise SysCallError(f"{self.cmd} exited with abnormal exit code [{self.exit_code}]: {self._trace_log[-500:]}", self.exit_code, worker=self)
archinstall.lib.exceptions.SysCallError: ['/usr/bin/mount', '-t', 'vfat', '/dev/nvme0n1p1', '/mnt/archinstall/boot'] exited with abnormal exit code [8192]: b'mount: /mnt/archinstall/boot: /dev/nvme0n1p1 already mounted on /mnt/archinstall.\r\n       dmesg(1) may have more information after failed mount system call.\r\n'`

**Comment by Torxed** [comment] 2022-10-12 12:16
Duplicate of #1495 I'm pretty sure.

**Closed by Torxed** 2022-10-12 12:16 UTC
