### ISSUE TITLE
Pacman broke

### ISSUE THREAD

**Issue by Enderxity** [archlinux/archinstall#2339] opened 2024-01-19 09:52 UTC
Newbie here
Just tried to install arch with archinstall
And it just gave errors 
On January iso

https://0x0.st/H0xE.log
https://0x0.st/H0xY.log

**Comment by svartkanin** [comment] 2024-01-20 23:33
Duplicate of https://github.com/archlinux/archinstall/issues/2305

**Closed by svartkanin** 2024-01-20 23:33 UTC
