### ISSUE TITLE
['/usr/bin/partprobe', '/dev/sdb'] exited with abnormal exit code [256]

### ISSUE THREAD

**Issue by mateuszmetz** [archlinux/archinstall#1083] opened 2022-04-25 12:29 UTC
I've encountered this issue while trying to install Arch from USB pendrive, using 2.4.0.RC2 version from git.
It seems to be related to the /dev/sdb pendrive.

2.3.3 version from the Arch ISO works without this problem on my laptop and goes through with the install of Arch.

Here's the logfile:
[install.log](https://github.com/archlinux/archinstall/files/8554441/install.log)

I'm not sure why partprobe has some issue with USB pendrive in 2.4.0. I'm just a noob user trying to install Arch quickly.

Thank you for archinstall, it's really nice tool :)

**Comment by Torxed** [comment] 2022-04-25 15:43
Glad you like it! We'll investigate why before we release v2.4.0! Thank you for reporting it.

**Comment by Torxed** [comment] 2022-04-26 15:14
I've merged a PR that should fix this (#1088), if nothing else it should give a bit more clear error message of *where* the issue happens in the code if the issue remains.

I've also tweaked a bunch of partprobe calls and made the timing more efficient.
It's in `master` and will be out in `v2.4.0` in the next couple of days if you want to try it out.

**Comment by mateuszmetz** [comment] 2022-04-26 18:27
I've tested your new commit, the log is the same as the last one (at least to my eye ;)

[install_new.log](https://github.com/archlinux/archinstall/files/8565926/install_new.log)

Here's a photo of the traceback:

![bugScreen](https://user-images.githubusercontent.com/6099571/165367211-f30aa5b7-47d2-44c4-a69a-a23b5d877671.jpg)

**Comment by Torxed** [comment] 2022-04-26 18:42
What the hell. Ok I'll take a deeper look.
Traceback is super helpful this time around!

We won't be able to release v2.4.0 anyway until I figure out why the menu system acting up. So I have some more time to solve this.

**Comment by Torxed** [comment] 2022-04-26 19:22
Out of curiosity, what model of USB stick is it?
Could you do `lsusb --verbose --tree` and grab the relevant tree for that USB stick?
```
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 10000M
    ID 1d6b:0003 Linux Foundation 3.0 root hub
    |__ Port 3: Dev 3, If 0, Class=Mass Storage, Driver=usb-storage, 5000M
        ID 0951:1666 Kingston Technology DataTraveler 100 G3/G4/SE9 G2/50
```
And once you found it, do `lsusb --verbose -d 0951:1666` *(0951:1666 being the ID of my usb stick that I'm trying to reproduce this with)*:
```
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               3.20
  bDeviceClass            0
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0         9
  idVendor           0x0951 Kingston Technology
  idProduct          0x1666 DataTraveler 100 G3/G4/SE9 G2/50
  bcdDevice            0.01
  iManufacturer           1 Kingston
  iProduct                2 DataTraveler 3.0
  iSerial                 3 <serial>
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x002c
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              296mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         8 Mass Storage
      bInterfaceSubClass      6 SCSI
      bInterfaceProtocol     80 Bulk-Only
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0400  1x 1024 bytes
        bInterval               0
        bMaxBurst              15
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0400  1x 1024 bytes
        bInterval               0
        bMaxBurst              15
```

Mask `iSerial` if you want to be careful.

**Comment by Torxed** [comment] 2022-04-26 19:58
#1090 Should fix that very specific issue along with better error handling in `Partition()` overall. The ISO won't build at the moment due to issues with key signatures on a package but it would be epic if you could try that code out.

**Comment by mateuszmetz** [comment] 2022-04-26 23:12
For some reason I had trouble downloading ISO file that you've linked, but using official ISO and building version with your last commit, the install went through this time!

I haven't thought about the "quality" of the pendrive I've used for ISO, it's actually some old "business card" university give-out 4GB pendrive, yep, it might be shitty ;)

```Bus 001 Device 002: ID 058f:6387 Alcor Micro Corp. Flash Drive
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x058f Alcor Micro Corp.
  idProduct          0x6387 Flash Drive
  bcdDevice            1.01
  iManufacturer           1 Generic
  iProduct                2 Mass Storage
  iSerial                 3 <serial>
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0020
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         8 Mass Storage
      bInterfaceSubClass      6 SCSI
      bInterfaceProtocol     80 Bulk-Only
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0

**Comment by Torxed** [comment] 2022-04-27 05:00
Sadly there are a lot of hardware types that cause edge cases. This might be one of those, or the USB hub might be differet making it impossible to probe, no idea which but i'll try to get a hold of a similar setup for my testing setup.

I'm very greatful for your time and info with this and happy we could figure it out! Thank you and glad you like it :)

**Closed by Torxed** 2022-04-27 05:00 UTC
Labels: bug

**Comment by Oman395** [comment] 2022-10-02 19:24
Just want to throw on my findings, had the same issue-- for whatever reason, arch had mounted nvme0n1p1, which was causing issues because archinstall wasn't able to handle it. I didn't notice at first because umount /dev/nvme0n1 said it wasn't mounted, but running umount /dev/nvme0n1p1 fixed it, and I was able to install successfully.
