### ISSUE TITLE
Problem with partitioning

### ISSUE THREAD

**Issue by mesteryui** [archlinux/archinstall#1599] opened 2022-12-17 19:40 UTC
![IMG_20221217_202938](https://user-images.githubusercontent.com/108957859/208263474-6b7ca7a0-d541-4fd0-87d3-f0520f907961.jpg)

**Comment by critkitten** [comment] 2022-12-18 19:42
duplicate of https://github.com/archlinux/archinstall/issues/1557

**Comment by Confuze** [comment] 2022-12-18 22:44
> duplicate of https://github.com/archlinux/archinstall/issues/1557

Yup, should fix itself with retries. If not, try installing a different version of the installer. (Guide in readme) If none of that works, try using the solution in #1557 which involved changing the code with a command.

**Comment by svartkanin** [comment] 2023-09-17 11:13
This is resolved with the latest rewrites

**Closed by svartkanin** 2023-09-17 11:13 UTC
