### ISSUE TITLE
Archinstall is doing weird stuff with the locale settings

### ISSUE THREAD

**Issue by kassindornelles** [archlinux/archinstall#1401] opened 2022-07-31 20:22 UTC
i did set my language to pt-br (portugues brasil) when installing with archinstall and it generated a lot of garbage that caused several different types of bugs in my system, this is what the script did:

/etc/locale.conf
![image](https://user-images.githubusercontent.com/40970965/182043858-8d86849a-ce72-4a5b-978b-98f6e1ebc316.png)

/etc/locale.gen
![image](https://user-images.githubusercontent.com/40970965/182043828-e1ebed99-4439-49a3-9f73-70455e54afaf.png)

**Comment by kassindornelles** [comment] 2022-07-31 20:26
i was asking myself why accents were not working on wine
i fixed everything myself, but would be cool to have all of that sorted out!

locale.gen fixed:
pt_BR.UTF-8 UTF-8
en_US.UTF-8 UTF-8

/etc/locale.conf fixed:
LANG="pt_BR.UTF-8"

**Comment by 0xShree** [comment] 2022-08-02 04:09
Hi there @kassindornelles, please attach `/var/log/archinstall/install.log` and also mention which version you used :)

**Comment by Torxed** [comment] 2022-08-02 09:51
It appears that it set the english locale correctly, so I wonder if you supplied `locale` to `pt_BR.UTF-8` instead of just `pt_BR`? Because we have a `encoding` variable as well which is the `UTF-8`. THe `install.log` should be helpful here to avoid having to ask these type of questions :)

**Comment by kassindornelles** [comment] 2022-08-02 13:39
[install.tar.gz](https://github.com/archlinux/archinstall/files/9242668/install.tar.gz)


i did choose UTF-8 and then pt_BR-UTF8

**Comment by grazzolini** [comment] 2022-08-09 19:47
This is a duplicate of #1200

**Closed by grazzolini** 2022-08-09 19:47 UTC
