### ISSUE TITLE
Follow Discoverable Partitions Specification when using systemd-boot

### ISSUE THREAD

**Issue by akay** [archlinux/archinstall#1334] opened 2022-06-16 17:58 UTC
I wasn't able to find any discussion regarding this. Please let me know if I somehow missed it.

The benefits of automatically discovering partitions are listed on the [DPS webpage](https://systemd.io/DISCOVERABLE_PARTITIONS/).

Any interest?

**Comment by Torxed** [comment] 2022-06-16 19:55
I think we talked about this *somewhere* but I cannot recall where. Do we have an arch wiki on the subject? *(I'm on my phone and on vacation. I can find it later if it exists but would appreciate a link if there is one)*

**Comment by weilbith** [comment] 2022-07-24 18:02
I'm very interested in this too. But unfortunately it seems like I can't even set the respective UUID by hand in the disk layout configuration. That would be simple first step. 🙂

**Comment by Torxed** [comment] 2022-10-05 14:49
Closing as a duplicate of #862 just to clean up.
But we'll reference this ticket when implementing :)

**Closed by Torxed** 2022-10-05 14:49 UTC
