### ISSUE TITLE
Work around for:  Installation fails: "error: unresolvable package conflicts detected" issue

### ISSUE THREAD

**Issue by FigmentEntity** [archlinux/archinstall#1990] opened 2023-08-06 02:54 UTC
I do not exactly know why this is happening, but you can work around this issue by selecting no audio server. No pulse audio, no pipewire. Install it after installation. Hope this helps.

**Comment by fabianmuehlberger** [comment] 2023-08-17 06:40
This seems to be a duplicate of   #1996 and should be closed

**Closed** 2023-09-14 09:59 UTC
