### ISSUE TITLE
Error: type object Menu has no attribute 'yes_no'

### ISSUE THREAD

**Issue by i2** [archlinux/archinstall#1184] opened 2022-05-14 16:21 UTC
The most recent merge in master seems to have broken the post-install functionality in guided.py. When I run the same (default config files from archinstall) using:
1. official archinstall that comes in archiso
2. master branch of archinstall from github

The former one installs without any issues, but the latter results in a bad error just at the end!
![Menu-yes_no](https://user-images.githubusercontent.com/3228126/168440203-18ca90ca-ad78-429f-af9b-9b4781018aa6.png)

The lines with issue maybe here: https://github.com/archlinux/archinstall/blob/a748f3fba04e771a3c18e66efcd2cf48b42c778e/examples/guided.py#L257-L265

In both scenarios, I have silent: false.

Please discard the custom commands, they don't make a difference as I have commented them out.

**Comment by svartkanin** [comment] 2022-05-15 09:17
Hmm I'm very confused about that one, first there's no stack trace which is a bit odd unless we're capturing the exception and just printing the reason? 

I checked all `Menu.yes_no()` occurrences in the code and they seem implemented correclty :thinking:

**Comment by Torxed** [comment] 2022-05-16 08:26
I think this is fixed? I got it as well but after a `git pull` to the latest master I can't reproduce this.

**Comment by svartkanin** [comment] 2022-05-16 11:03
in that case I'd say lets close it and if it happens again lets reopen it.

**Closed** 2022-05-16 11:27 UTC
Labels: bug
