### ISSUE TITLE
Installation failure on master, latest commit.

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#1227] opened 2022-05-21 15:15 UTC
Unlike the previous failure I reported, this one didn't have encryption enabled at all.

configuration:

![image](https://user-images.githubusercontent.com/277927/169657872-8be56723-37e3-44ad-9be8-432205f4ba2e.png)
![image](https://user-images.githubusercontent.com/277927/169657877-0e512373-9ad4-4e7d-a284-ac0eec92bb82.png)

cmd history:
![image](https://user-images.githubusercontent.com/277927/169657882-074ac181-14d2-4738-b9a7-f6ecf83f80c8.png)

install.log:

![image](https://user-images.githubusercontent.com/277927/169657902-4dffa8a6-4727-41ce-bd67-09379bfeff2c.png)

stack trace:

![image](https://user-images.githubusercontent.com/277927/169657905-72d99065-556b-4bc9-89e1-d0d684b47369.png)

**Comment by Torxed** [comment] 2022-05-22 07:51
So I've reproduced the issue, and boiled it down to `device_instance` being the culprit.
It's the only non-standard object in the `deepcopy(partition)` step.

I'm trying to figure out why this happens.
Because to me the code for this particular config and code path hasn't changed much at all..

But some underlying variables appears to have.
After solving this bug, by implementing my own `deepcopy` *(just a recursive dict copier)* we'll get this:
![bug](https://user-images.githubusercontent.com/861439/169684641-224b37f0-7a39-4b9e-96e0-e779faf053ca.png)

Which indicates that `.real_device` or something similar isn't stripping subvolume names correctly anymore.
I'll get this sorted but I need to figure out the root cause first.

**Comment by Torxed** [comment] 2022-05-22 08:08
The path some how gets mangled up by: https://github.com/archlinux/archinstall/blob/33ce7dbd8baf5402a20e850f503390b9c229e698/archinstall/lib/disk/btrfs.py#L225

I understand why, as `.path` inserts `.path` + `new_subvolume`, appending on the already given path.
I think I will have to re-write this logic to handle it elsewhere, as string management is probably not the best fit here.

This will take a day or so. But for now setting: https://github.com/archlinux/archinstall/blob/33ce7dbd8baf5402a20e850f503390b9c229e698/archinstall/lib/disk/partition.py#L492-L493

To:
```python
	def unmount(self) -> bool:
		worker = SysCommand(f"/usr/bin/umount {self.device_path}")
```

But that will cause:
![screen_test](https://user-images.githubusercontent.com/861439/169685137-5f290914-43ac-48fd-adc9-c0c1375d156f.png)

Which brings me back to re-write hehe.
So I'll have to go back and do a bit of cleanup here.

**Comment by Torxed** [comment] 2022-05-22 17:36
So I'm halfway done with a more permanent fix to the overall problem described here.
However, they contain a lot of breaking changes. Most of which users won't even notice because as per usual it's surrounding the partition/subvolume handling internally. But if by any chance people use the API to manage partitioning this will break some stuff.

The some what funny PR id of #1234 is the intended implementation.

**Comment by Torxed** [comment] 2022-05-26 16:36
PR is ready to go in.
I've tested encrypted and un-encrypted and they both appear to work just fine now.

I've removed the need for parsing `SysCommand("findmnt")` result data, mainly the `source` which was parsed in a few places through functions that had multiple tasks per call. Instead, there's now a `findmnt` function which simply calls and returns data as-is, and each respective `lib.btrfs.*` structure now has the task of parsing that data in the way they expect it to be.

Subsequently `luks.unlock()` and other various functions now returns a `BtrfsPartition` instead of `Partition` which, inherits `Partition` and thus behaves exactly the same, with the slight difference that it extends some functionalities such as `.subvolumes` and `.create_subvolume`.. Something `Partition` doesn't have *(Yea `Partition.subvolumes` do exist, but I'm planning on deprecating it next release)*.

I doubt that this is perfect by any means, and I'll continue to run tests.
But this specific bug should be fixed with this at least :)

**Closed** 2022-05-26 16:46 UTC
