### ISSUE TITLE
Multiple network services activated make network connection unreliable - iwd crashes

### ISSUE THREAD

**Issue by erus** [archlinux/archinstall#956] opened 2022-02-10 08:55 UTC
Hi, please have a look at https://bbs.archlinux.org/viewtopic.php?id=273965 : multiple topics on this issue seem to come from having used archinstall without double-checking the final results.

**Comment by svartkanin** [comment] 2022-02-10 09:19
@Torxed I can dig into that since it's the issue I've actually got on my machine

**Comment by erus** [comment] 2022-02-10 09:32
> Hehe that's the issue I've asked there ;) I uninstalled iwd and things seem to work fine again

Thanks for chiming in :) I've seen @jprestwo complain about your issue on IRC, since the common point was archinstall and not reported yet I figured I might as well open an issue even if I'm not affected :)

**Comment by svartkanin** [comment] 2022-03-05 07:15
@Torxed I can't reproduce this, on a clean installation with `Copy ISO` the only thing I get is `systemd-networkd.service`. 
When choosing `Use NetworkManager` I only the the NM service running. 

It might have been human error (myself) installing either `iwd` or `NM` post installation...
I think we can close this

**Closed** 2022-03-05 08:16 UTC
