### ISSUE TITLE
archinstall does not work with nvme drives.

### ISSUE THREAD

**Issue by heliophane** [archlinux/archinstall#1587] opened 2022-12-05 16:29 UTC
Hi. I'm currently typing this on my phone so excuse my poor formatting. I attempted to use archinstall on my laptop, an XPS13 9300 and ny desktop. Both have nvme drives. During both install processes, I get an error stating 
Could not decode JSON: lsblk: /dev/sdc1: not a block device
{
   "blockdevices":[

   ]
}
This error occurs when I try to set disk or when I attempt to install. I'm trying to install a desktop profile with KDE on btrfs with encryption.

I have tried multiple times with several methods of writing my USB stick on multiple PCs. I have use DD, balena etcher, and Rufus. I thought it may be an issue with the November arch iso so I waited until the December iso was out and I'm still having this issue.

**Comment by binakot** [comment] 2022-12-05 16:36
I just got this error too on my regular pc and got python stacktrace right in my case 👿 
Please provide your stacktrace here.
Btw I used balena etcher with usb stick and latest arch iso.

But if you try one more time it will work. 
There is some magic, because it works sometimes and sometimes doesn't work ;)
Try to configure other settings, then save it and try to select drives one more time. And one more time. And one more...

**Comment by binakot** [comment] 2022-12-05 16:38
Also it duplicate #1573 which duplicate #1557

**Comment by binakot** [comment] 2022-12-05 16:41
And there is "my solution": just retries https://github.com/archlinux/archinstall/issues/1557#issuecomment-1312573799

**Comment by nimafanniasl** [comment] 2022-12-08 22:18
Yup, i had that exact issue, i came to report it and saw the issue is already here :)))

**Comment by David7ce** [comment] 2023-01-17 18:44
I think it's because in nvme disk the partition is in /dev/nvmenX and not /dev/sdX

**Comment by svartkanin** [comment] 2023-09-17 11:16
This should be resolved with the recent rewrites and swtiches to pyparted

**Closed by svartkanin** 2023-09-17 11:16 UTC
