### ISSUE TITLE
Failed installation: pipewire-pulse.service could not be started

### ISSUE THREAD

**Issue by pkoscik** [archlinux/archinstall#2764] opened 2024-11-01 12:41 UTC
### Which ISO version are you using?

2024.11.01

### The installation log

```json
Hardware model detected: ASUS System Product Name; UEFI mode: True
Processor model detected: AMD Ryzen 7 7700X 8-Core Processor
Memory statistics: 30078524 available out of 32053248 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

Virtualization detected: None; is VM: False
Graphics devices detected: dict_keys(['Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] (rev c1)', 'Advanced Micro Devices, Inc. [AMD/ATI] Raphael (rev c3)'])


# snip


 -- Chosen configuration --
{
    "__separator__": null,
    "additional-repositories": [],
    "archinstall-language": "English",
    "audio_config": {
        "audio": "pipewire"
    },
    "bootloader": "Grub",
    "config_version": "2.8.6",
    "debug": false,
    "disk_config": {
        "config_type": "default_layout",
        "device_modifications": [
            {
                "device": "/dev/nvme1n1",
                "partitions": [
                    {
                        "btrfs": [],
                        "dev_path": null,
                        "flags": [
                            "Boot",
                            "ESP"
                        ],
                        "fs_type": "fat32",
                        "mount_options": [],
                        "mountpoint": "/boot",
                        "obj_id": "7c47961c-0ce4-4606-802f-2e7e3165800e",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "GiB",
                            "value": 1
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "MiB",
                            "value": 1
                        },
                        "status": "create",
                        "type": "primary"
                    },
                    {
                        "btrfs": [
                            {
                                "mountpoint": "/",
                                "name": "@"
                            },
                            {
                                "mountpoint": "/home",
                                "name": "@home"
                            },
                            {
                                "mountpoint": "/var/log",
                                "name": "@log"
                            },
                            {
                                "mountpoint": "/var/cache/pacman/pkg",
                                "name": "@pkg"
                            },
                            {
                                "mountpoint": "/.snapshots",
                                "name": "@.snapshots"
                            }
                        ],
                        "dev_path": null,
                        "flags": [],
                        "fs_type": "btrfs",
                        "mount_options": [
                            "compress=zstd"
                        ],
                        "mountpoint": null,
                        "obj_id": "a07a2b5d-00d8-4889-b586-53c92897bc6f",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 1023133704192
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 1074790400
                        },
                        "status": "create",
                        "type": "primary"
                    }
                ],
                "wipe": true
            }
        ]
    },
    "disk_encryption": null,
    "hostname": "hellfire-arch",
    "kernels": [
        "linux"
    ],
    "locale_config": {
        "kb_layout": "us",
        "sys_enc": "UTF-8",
        "sys_lang": "en_US"
    },
    "mirror_config": {
        "custom_mirrors": [],
        "mirror_regions": {
            "Poland": [
                "http://arch.sakamoto.pl/$repo/os/$arch",
                "https://mirror.juniorjpdj.pl/archlinux/$repo/os/$arch",
                "http://mirror.juniorjpdj.pl/archlinux/$repo/os/$arch",
                "http://arch.midov.pl/arch/$repo/os/$arch",
                "http://ftp.psnc.pl/linux/archlinux/$repo/os/$arch",
                "https://arch.midov.pl/arch/$repo/os/$arch",
                "https://ftp.psnc.pl/linux/archlinux/$repo/os/$arch",
                "https://arch.sakamoto.pl/$repo/os/$arch",
                "https://ftp.icm.edu.pl/pub/Linux/dist/archlinux/$repo/os/$arch",
                "http://ftp.icm.edu.pl/pub/Linux/dist/archlinux/$repo/os/$arch",
                "http://mirroronet.pl/pub/mirrors/archlinux/$repo/os/$arch",
                "https://mirroronet.pl/pub/mirrors/archlinux/$repo/os/$arch"
            ]
        }
    },
    "network_config": {},
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [
        "helix",
        "git",
        "neofetch"
    ],
    "parallel downloads": 0,
    "profile_config": {
        "gfx_driver": "AMD / ATI (open-source)",
        "greeter": null,
        "profile": {
            "custom_settings": {},
            "details": [],
            "main": "Xorg"
        }
    },
    "save_config": null,
    "script": "guided",
    "silent": false,
    "skip_ntp": false,
    "skip_version_check": false,
    "swap": true,
    "timezone": "Europe/Warsaw",
    "uki": false,
    "version": "2.8.6"
}

# snip


Installing audio server: Pipewire
Installing packages: ['pipewire', 'pipewire-alsa', 'pipewire-jack', 'pipewire-pulse', 'gst-plugin-pipewire', 'libpulse', 'wireplumber']
['/usr/bin/arch-chroot', '/mnt/archinstall', 'su', '-', 'pkoscik', '-c', 'systemctl enable --user pipewire-pulse.service'] exited with abnormal exit code [1]: [0;1;31mFailed to connect to bus: No medium found[0m


Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 356, in run_as_a_module
    main()
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 331, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 246, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', Path('/mnt')))
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 116, in perform_installation
    with Installer(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 111, in __exit__
    raise exc_val
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 173, in perform_installation
    audio_config.install_audio_config(installation)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/models/audio_configuration.py", line 46, in install_audio_config
    PipewireProfile().install(installation)
  File "/usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py", line 40, in install
    self._enable_pipewire_for_all(install_session)
  File "/usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py", line 35, in _enable_pipewire_for_all
    install_session.arch_chroot('systemctl enable --user pipewire-pulse.service', run_as=user.username)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 632, in arch_chroot
    return self.run_command(cmd)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/installer.py", line 626, in run_command
    return SysCommand(f'/usr/bin/arch-chroot {self.target} {cmd}')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 366, in __init__
    self.create_session()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 415, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 198, in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'su', '-', 'pkoscik', '-c', 'systemctl enable --user pipewire-pulse.service'] exited with abnormal exit code [1]: [0;1;31mFailed to connect to bus: No medium found[0m
```

#### Description of the issue

Running any `systemctl` command with the `--user` flag causes the the error. Observed when attempting to activate the `pipewire-pulse.service`.

```sh
arch-chroot /mnt/archinstall
su - pkoscik

# works
systemctl status

# crashes
systemctl --user status
``` 

The log is snipped (maximum 65536 chars), full text: https://0x0.st/XGb8.log

#### Virtual machine config:

Not used - bare metal installation

**Comment by FredBezies** [comment] 2024-11-01 13:08
I faced the same issue. Workaround is to not select pipewire in the setup part of the installer.

See this forum thread: https://bbs.archlinux.org/viewtopic.php?pid=2205881

**Comment by pkoscik** [comment] 2024-11-01 13:19
>Workaround is to not select pipewire in the setup part of the installer.

Can confirm. Attaching manual installation for the lazy ones (like me) 😄  

```sh
pacman -S pipewire wireplumber pipewire-pulse pipewire-alsa
systemctl --user enable --now pipewire.service wireplumber.service pipewire-pulse.service 
```

**Comment by BraveSam** [comment] 2024-11-01 13:30
If you git clone the archinstall master and use it, it doesn't have the issue. That's what I did.

**Comment by amrtn30** [comment] 2024-11-01 22:02
Indeed I had the problem when installing. Do no choose an audio profile makes it work. 
But still, I have my sound perfectly working without adding pipewire afterward.

**Comment by andresroliveira** [comment] 2024-11-02 02:58
Same issue here. Even installing pulseaudio, when selecting the Gnome Desktop, the problem persists.

**Comment by erikdubois** [comment] 2024-11-02 14:34
Arch Linux iso 24-11-01 can not be installed via archinstall - tried pulseaudio and pipewire
https://youtu.be/oUWiu5Um1eo

Is there an easy way to get the log file on the net via terminal?

**Comment by Neo-29** [comment] 2024-11-02 17:06
> I faced the same issue. Workaround is to not select pipewire in the setup part of the installer.
> 
> See this forum thread: https://bbs.archlinux.org/viewtopic.php?pid=2205881

I think I already saw this bug, some months ago.. 'it sure.

**Comment by Niwau** [comment] 2024-11-02 19:44
Same problem here, I could install without selecting an audio profile

**Comment by ledufff** [comment] 2024-11-03 02:01
same here, can it be reproduced easily on a vm

**Comment by gfriesen98** [comment] 2024-11-03 06:15
same problem, tried both pulseaudio and pipewire on my laptop

**Comment by dbaxps2024** [comment] 2024-11-03 07:21
> > Workaround is to not select pipewire in the setup part of the installer.
> 
> Can confirm. Attaching manual installation for the lazy ones (like me) 😄
> 
> ```shell
> pacman -S pipewire wireplumber pipewire-pulse pipewire-alsa
> systemctl --user enable --now pipewire.service wireplumber.service pipewire-pulse.service 
> ```

Your proposal been executed on Arch Linux Plasma 6.2.2 KVM Guest still didn't help , regardless all icons looked nice audio test failed. No sound had been heard.

**Comment by dbaxps2024** [comment] 2024-11-03 07:27
Just a notice, Arch Linux Plasma 6.2.2 KVM Guest  was deployed via Virt-manager, thus Spice Console should be able to translate to external speakers any movie's fragment . I got failure once again. Video went fine without any sound.

**Comment by DarkXero-dev** [comment] 2024-11-03 12:18
Same here. 

Selecting no Audio, then installing Pipewire or Pulse works. And if you get message about jack2/pipewire-jack conflict just replace. Dunno where jack2 is coming from.

I hope this is fixed soon.

**Comment by svartkanin** [comment] 2024-11-03 20:30
Just to clarify, there has not been a new release of archinstall published recently so this may be an issue beyond archinstall. Nevertheless, it could be addressed inside archinstall and a workaround produced

**Comment by Torxed** [comment] 2024-11-04 14:30
I've begun debugging what's actually going on.
But I suspect the pipewire code needs to use: https://github.com/archlinux/archinstall/blob/11987a06d62d509c40c3ffdea28aee52d6ae6f54/archinstall/lib/boot.py#L10

Instead of calling `arch-chroot` directly: https://github.com/archlinux/archinstall/blob/11987a06d62d509c40c3ffdea28aee52d6ae6f54/archinstall/default_profiles/applications/pipewire.py#L35

As this will spawn a `systemd` instance enabling us to talk to it via dbus.
But I'm not quite sure why this happens all of a sudden, as we haven't changed anything and neither has [arch-chroot](https://gitlab.archlinux.org/archlinux/arch-install-scripts/-/blob/master/arch-chroot.in?ref_type=heads), that's the weird part.

**Comment by 4Sitam4** [comment] 2024-11-04 21:22
+1, same probleme here.

**Comment by martinvarbanov96** [comment] 2024-11-05 08:37
+1 here.
I hit this issue, so I installed my arch with archinstall with KDE wayland but without any audio. After that I tried to install pipewire on my own.

```
[marto@archlinux ~]$ systemctl status --user pipewire  pipewire.socket wireplumber  pipewire-pulse.socket pipewire-pulse
● pipewire.service - PipeWire Multimedia Service
     Loaded: loaded (/usr/lib/systemd/user/pipewire.service; enabled; preset: 
enabled)
     Active: active (running) since Tue 2024-11-05 10:04:53 EET; 10min ago
 Invocation: d1414172db4b45caa788f43388172dc8
TriggeredBy: ● pipewire.socket
   Main PID: 1356 (pipewire)
      Tasks: 3 (limit: 38115)
     Memory: 7.9M (peak: 9.1M)
        CPU: 11.572s
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/pipewire.service
             └─1356 /usr/bin/pipewire

Nov 05 10:04:53 archlinux systemd[1346]: Started PipeWire Multimedia Service.

● pipewire.socket - PipeWire Multimedia System Sockets
     Loaded: loaded (/usr/lib/systemd/user/pipewire.socket; enabled; preset: 
enabled)
     Active: active (running) since Tue 2024-11-05 10:04:53 EET; 10min ago
 Invocation: 00ce9670d4404c4d90b5d1af7522205f
   Triggers: ● pipewire.service
     Listen: /run/user/1000/pipewire-0 (Stream)
             /run/user/1000/pipewire-0-manager (Stream)
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/pipewire.socket

Nov 05 10:04:53 archlinux systemd[1346]: Listening on PipeWire Multimedia System Sockets.

● wireplumber.service - Multimedia Service Session Manager
     Loaded: loaded (/usr/lib/systemd/user/wireplumber.service; enabled; pr
eset: enabled)
     Active: active (running) since Tue 2024-11-05 10:04:53 EET; 10min ago
 Invocation: b56e4c365b9e4a809b339389c76f488d
   Main PID: 1357 (wireplumber)
      Tasks: 6 (limit: 38115)
     Memory: 10.3M (peak: 11.1M)
        CPU: 553ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/wireplumber.service
             └─1357 /usr/bin/wireplumber

Nov 05 10:04:53 archlinux systemd[1346]: Started Multimedia Service Session Manager.
Nov 05 10:04:53 archlinux wireplumber[1357]: wp-internal-comp-loader: Loading profile 'main'
Nov 05 10:04:53 archlinux wireplumber[1357]: wp-device: SPA handle 'api.libcamera.enum.manager' could not be loaded; is it inst
alled?
Nov 05 10:04:53 archlinux wireplumber[1357]: s-monitors-libcamera: PipeWire's libcamera SPA plugin is missing or broken. Some c
amera types may not be supported.
Nov 05 10:04:53 archlinux wireplumber[1357]: default: Failed to get percentage from UPower: org.freedesktop.DBus.Er
ror.NameHasNoOwner
Nov 05 10:04:53 archlinux wireplumber[1357]: spa.bluez5: BlueZ system service is not available
Nov 05 10:05:11 archlinux wireplumber[1357]: wp-event-dispatcher: <WpAsyncEventHook:0x5b0d64d7b740> failed: <WpSiStandardLink:0
x5b0d64e884c0> link failed: 1 of 1 PipeWire links failed to activate
Nov 05 10:06:12 archlinux wireplumber[1357]: wp-event-dispatcher: <WpAsyncEventHook:0x5b0d64d7b740> failed: <WpSiStandardLink:0
x5b0d64d0af60> link failed: some node was destroyed before the link was created

● pipewire-pulse.socket - PipeWire PulseAudio
     Loaded: loaded (/usr/lib/systemd/user/pipewire-pulse.socket; enabled
; preset: enabled)
     Active: active (running) since Tue 2024-11-05 10:04:53 EET; 10min ago
 Invocation: 5c6320dc81d240bd8ba7c0ebcc92cc00
   Triggers: ● pipewire-pulse.service
     Listen: /run/user/1000/pulse/native (Stream)
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/pipewire-pulse.socket

Nov 05 10:04:53 archlinux systemd[1346]: Listening on PipeWire PulseAudio.

● pipewire-pulse.service - PipeWire PulseAudio
     Loaded: loaded (/usr/lib/systemd/user/pipewire-pulse.service; enabled
; preset: enabled)
     Active: active (running) since Tue 2024-11-05 10:04:53 EET; 10min ago
 Invocation: 1b764af42d9c4ccf800304766bebe08e
TriggeredBy: ● pipewire-pulse.socket
   Main PID: 1359 (pipewire-pulse)
      Tasks: 3 (limit: 38115)
     Memory: 8.6M (peak: 9.3M)
        CPU: 14.192s
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/pipewire-pulse.service
             └─1359 /usr/bin/pipewire-pulse

Nov 05 10:04:53 archlinux systemd[1346]: Started PipeWire PulseAudio.
```

However after:
```
[marto@archlinux ~]$ pactl info
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 160
Tile Size: 65472
User Name: marto
Host Name: archlinux
Server Name: PulseAudio (on PipeWire 1.2.6)
Server Version: 15.0.0
Default Sample Specification: float32le 2ch 48000Hz
Default Channel Map: front-left,front-right
Default Sink: auto_null
Default Source: auto_null.monitor
Cookie: d9e5:fbe8
```

I Default Sink and default source should contain some bus info, however mine does not. Could this be the problem?  Could this problem be with the kernel? 

I can see that alsa mixer and pavucontrol registers some input but there is no sound.  I am comming from another linux distro in which there was audio.

```
[marto@archlinux ~]$ pactl list sinks    # get sink name
Sink #34
    State: IDLE
    Name: auto_null
    Description: Dummy Output
    Driver: PipeWire
    Sample Specification: float32le 2ch 48000Hz
    Channel Map: front-left,front-right
    Owner Module: 4294967295
    Mute: no
    Volume: front-left: 30802 /  47% / -19.67 dB,   front-right: 29618 /  45% / -20.70 dB
            balance -0.04
    Base Volume: 65536 / 100% / 0.00 dB
    Monitor Source: auto_null.monitor
    Latency: 0 usec, configured 0 usec
    Flags: DECIBEL_VOLUME LATENCY 
    Properties:
        node.name = "auto_null"
        device.description = "Dummy Output"
        audio.rate = "48000"
        audio.channels = "2"
        audio.position = "FL,FR"
        media.class = "Audio/Sink"
        factory.name = "support.null-audio-sink"
        node.virtual = "true"
        monitor.channel-volumes = "true"
        factory.id = "19"
        clock.quantum-limit = "8192"
        client.id = "33"
        node.driver = "true"
        port.group = "stream.0"
        node.loop.name = "data-loop.0"
        library.name = "audioconvert/libspa-audioconvert"
        object.id = "34"
        object.serial = "34"
    Formats:
        pcm
```

**Comment by svartkanin** [comment] 2024-11-06 10:25
Okay I manged to reproduce the problem in a VM with the current release. Even doing a manual `arch-chroot` after the error terminates archinstall leads to the same above error 
```
Failed to connect to bus: No medium found
```

I then pulled the latest master and run another installation and that worked just fine. So there are 2 solutions at the moment
* Don't pick any audio server during installation and install it manually afterwards
* Use the latest master instead 
```
pacman -Sy git
git clone https://github.com/archlinux/archinstall.git
cd archinstall
python -m archinstall
```

@Torxed as master seems to have somehow fixed this shall we do a new release?

**Comment by Torxed** [comment] 2024-11-06 12:18
I'm wondering if it's too many `arch-chroot` calls that cause the issue? Because we have fewer in `master`...

Because it mounts in a few related sys/proc mounts

**Comment by dbaxps2024** [comment] 2024-11-06 13:02
pacman -Sy git
git clone https://github.com/archlinux/archinstall.git
cd archinstall
python -m archinstall
I did it twice on Arch Plasma 6.2.3 KVM Guests (@F41 KVM Hypervisor and @Arch KVM Hypervisor Bare metal ) . Installation completed smoothly. However, Sound test still failed.  Hack for F41 Plasma Spin  KVM Guest is also known and works fine @F41 KVM Hypervisor.

**Comment by lowcraft** [comment] 2024-11-06 13:36
Hello,
I came across the same bug in version 2024.11.01. I disabled the audio driver in the JSON configuration like so:
`"audio_config": false,`
Afterward, I initiated the installation again using:
`archinstall --config user_configuration.json`

Desktop Environment: GNOME/X11
I plan to verify that everything is operational before proceeding with the audio driver installation.

"One moment later..."

Following the installation and system reboot, the audio is unexpectedly working.
At present, I'm uncertain of the cause, but it appears to be operating correctly. The pulse package is installed yet not activated (encountering the same error):

```
sudo systemctl enable pipewire-pulse.service
Failed to enable unit: Unit file pipewire-pulse.service does not exist.
```

I will need to investigate this further, but currently, after so many Arch installations with various window managers/desktop managers (and other distributions), I stop the investigation.
It's a challenge I've noted in my #ToDo list (a man of courage)

**Comment by nightridex** [comment] 2024-11-06 17:52
I had same problem but when i install arch without sound for some reason when i boot into arch i have pipewire installed and sound working.

**Comment by gfriesen98** [comment] 2024-11-06 19:19
on i3wm, after selecting no audio from archinstall audio just werks after installing Firefox (which installed jack2) 🤷. Havent done further testing as to why arch-chroot wasnt working with pipewire

**Comment by dev-aphex** [comment] 2024-11-06 22:48
> Without verifying, I wouldn't be surprised if some DE's _(looking at you Gnome, and maybe KDE)_ has pipewire as a dependency and manages the user service during login in the greeter.

when straight up installing plasma as desktop, pipewire will be automatically installed  anyway

**Comment by namarrgon** [comment] 2024-11-07 21:43
archinstall shouldn't be enabling these pipewire/pulseaudio units, their post_install() scriptlets already handle this: https://gitlab.archlinux.org/archlinux/packaging/packages/pipewire/-/blob/main/pipewire-pulse.install

**Comment by Torxed** [comment] 2024-11-07 22:20
> archinstall shouldn't be enabling these pipewire/pulseaudio units, their post_install() scriptlets already handle this: https://gitlab.archlinux.org/archlinux/packaging/packages/pipewire/-/blob/main/pipewire-pulse.install

I don't mind changing it, but this code has been there for [around three years](https://github.com/archlinux/archinstall/blob/240f688ccefa7bddb56efe5bc41a457c96792e42/profiles/applications/pipewire.py#L14) and I'm curious why it stopped working out of the blue.

A fix *(pushing a new release and potentially removing this)* we can do quite easy, but understanding it would be good too!

**Comment by gauravmandall** [comment] 2024-11-08 14:20
Has anyone found the solution.

**Comment by 4Sitam4** [comment] 2024-11-08 14:26
> Has anyone found the solution.

if install with a DE -> Then simply don't select one.  Gnome or KDE will install one for you. 
Else -> install what you want after. It's not like you can't do it without sound ^^ (except blind people i guess :/ )

**Comment by gauravmandall** [comment] 2024-11-08 14:32
> > Has anyone found the solution.
> 
> if install with a DE -> Then simply don't select one. Gnome or KDE will install one for you. Else -> install what you want after. It's not like you can't do it without sound ^^ (except blind people i guess :/ )

I'm using archinstall script and chose minimal and no audio as well but this issue still persist should I go with earlier versions of arch or it's happening because of archinstall only ??

**Comment by hozzaq** [comment] 2024-11-08 16:17
> > > Has anyone found the solution.
> > 
> > 
> > if install with a DE -> Then simply don't select one. Gnome or KDE will install one for you. Else -> install what you want after. It's not like you can't do it without sound ^^ (except blind people i guess :/ )
> 
> I'm using archinstall script and chose minimal and no audio as well but this issue still persist should I go with earlier versions of arch or it's happening because of archinstall only ??

just install it manually after archinstall

> pacman -S pipewire wireplumber pipewire-pulse pipewire-alsa
> systemctl --user enable --now pipewire.service wireplumber.service pipewire-pulse.service

**Comment by Torxed** [comment] 2024-11-10 18:45
A good idea for a workaround/solution was proposed here: https://www.reddit.com/r/archlinux/comments/1go2ott/comment/lwfij4e/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

Doing `ln -s` instead of calling `systemctl enable` might be a good idea.

**Comment by dbaxps2024** [comment] 2024-11-13 09:03
The most recent deployment of Arch Plasma 6.2.3 (KVM Guest) works fine via Spice Console at Fedora 41 KVM Hypervisor Host (bare metal). I mean translation sound of youtube's  video to external speakers. I pushed forward to current status Arch Linux Plasma 6.2.3 as KVM Host ( and rebooted ) on bare metal . However, same Guest deployment doesn't provide me  same stability as Fedora 41 KVM Hypervisor does. I might be missing some tuning of KVM config  of Arch Linux KVM Hypervisor host on bare metal.

**Comment by shawnyeager** [comment] 2024-11-13 20:15
Same problem here, on both my Framework 13" AMD and my Thinkpad X1 Carbon Generation 8. I assumed it was a glitch on my Thinkpad (last night), so tried again without selecting Pipewire, and succeeded. The same thing just happened on my Framework, so I capture the log:

https://0x0.st/Xkpm.log

**Comment by ruisuantonio** [comment] 2024-11-14 17:03
Same problem, iso 2024.11.01

https://0x0.st/XkvJ.log

**Comment by evlogii** [comment] 2024-11-15 16:36
Yup. Same for me. Why has this problem not been caught during testing?

http://[0x0.st/Xkkl.log](http://0x0.st/Xkkl.log)

**Comment by Torxed** [comment] 2024-11-16 17:56
Switched to using `ln -s` manually, instead of utilizing `systemctl enable --user`.
I would like to use native tooling, but the additional complex use of `Boot()` is not worth it currently.

**Closed by Torxed** 2024-11-16 17:56 UTC

**Comment by serial02** [comment] 2024-11-17 14:43
Here the same problem!

https://github.com/archlinux/archinstall/issues/2846

[install.log](https://github.com/user-attachments/files/17790920/install.log)

**Comment by Torxed** [comment] 2024-11-18 10:46
It's been fixed, hence the issue is closed.

**Comment by pkoscik** [comment] 2024-11-18 12:06
Thanks for figuring this out!

**Comment by SnorreSelmer** [comment] 2024-11-20 20:12
In what version will this fix be released? 3.0.1?

**Comment by svartkanin** [comment] 2024-11-20 20:52
This fix should already be in 3.0.0

**Comment by SnorreSelmer** [comment] 2024-11-21 10:31
I installed Arch yesterday, from ISO 2024.11.1, with archinstall 3.0.0-1, and it crashed hard on this step with the above error.

**Comment by SnorreSelmer** [comment] 2024-11-21 10:47
Come to think of it, the archinstall I got had none of your nurses magic. Maybe it pulls the new version but doesn't actually use it? I'll have to investigate this a bit more

**Comment by SnorreSelmer** [comment] 2024-11-21 10:56
Apologies! It says there's a new version, it doesn't actually grab it. My bad, I misunderstood the output of the version check.
