### ISSUE TITLE
dos this script suitable for arch32? i486

### ISSUE THREAD

**Issue by youxiaojie** [archlinux/archinstall#2251] opened 2023-11-23 07:43 UTC
dos this script suitable for arch32?

**Comment by Torxed** [comment] 2023-11-23 08:24
I'll close this and reference [known issues](https://archinstall.archlinux.page/help/known_issues.html#arm-32bit-and-other-cpu-types-error-out-1686-2185). If you have questions feel free to post them here even after the issue is closed - I will get notified and I will answer what I can answer :)

**Closed by Torxed** 2023-11-23 08:24 UTC
